USE DW_Workspace
GO

BEGIN TRY
	BEGIN TRAN

	SELECT DISTINCT BB.* 
	INTO DW_Workspace..customer_ar_history_TFS_173729_RemovedData
	FROM ista.dbo.customer_ar_history AA WITH (NOLOCK)
	INNER JOIN ista.dbo.customer_ar_history BB WITH (NOLOCK)
	ON ISNULL(BB.Customer_Tkn,0)			= ISNULL(AA.Customer_Tkn,0)	
	AND ISNULL(BB.Customer_Acct_Tkn,0)		= ISNULL(AA.Customer_Acct_Tkn,0)	
	AND ISNULL(BB.Account_Pkg_Tkn,0)		= ISNULL(AA.Account_Pkg_Tkn,0)	
	AND ISNULL(BB.REVENUE_CLASS_DESC,'')	= ISNULL(AA.REVENUE_CLASS_DESC,'')	
	AND ISNULL(BB.CUSTOMER_NAME,'')			= ISNULL(AA.CUSTOMER_NAME,'')	
	AND ISNULL(BB.STATUS_DESC,'')			= ISNULL(AA.STATUS_DESC,'')	
	AND ISNULL(BB.TERRITORY_CODE,'')		= ISNULL(AA.TERRITORY_CODE,'')	
	AND ISNULL(BB.LDC_ACCOUNT_NUM,'')		= ISNULL(AA.LDC_ACCOUNT_NUM,'')	
	AND ISNULL(BB.BillingAccountNumber,'')	= ISNULL(AA.BillingAccountNumber,'')
	AND ISNULL(BB.ACCOUNT,'')				= ISNULL(AA.ACCOUNT,'')	
	AND ISNULL(BB.TOTAL,0)					= ISNULL(AA.TOTAL,0)	
	AND ISNULL(BB.UNSTATEMENTED,0)			= ISNULL(AA.UNSTATEMENTED,0)	
	AND ISNULL(BB.[CURRENT],0)				= ISNULL(AA.[CURRENT],0)	
	AND ISNULL(BB.DAYS_1_30,0)				= ISNULL(AA.DAYS_1_30,0)	
	AND ISNULL(BB.DAYS_31_60,0)				= ISNULL(AA.DAYS_31_60,0)	
	AND ISNULL(BB.DAYS_61_90,0)				= ISNULL(AA.DAYS_61_90,0)	
	AND ISNULL(BB.DAYS_91_120,0)			= ISNULL(AA.DAYS_91_120,0)	
	AND ISNULL(BB.DAYS_OVER_120,0)			= ISNULL(AA.DAYS_OVER_120,0)	
	AND BB.AR_Aging_EffDate					= '20170314'
	WHERE AA.AR_Aging_EffDate				= '20170312'
	ORDER BY 1 DESC 

	DELETE ista.dbo.customer_ar_history
	FROM ista.dbo.customer_ar_history AA WITH (NOLOCK)
	INNER JOIN DW_Workspace..customer_ar_history_TFS_173729_RemovedData BB WITH (NOLOCK)
	ON ISNULL(BB.Customer_Tkn,0)			= ISNULL(AA.Customer_Tkn,0)	
	AND ISNULL(BB.Customer_Acct_Tkn,0)		= ISNULL(AA.Customer_Acct_Tkn,0)	
	AND ISNULL(BB.Account_Pkg_Tkn,0)		= ISNULL(AA.Account_Pkg_Tkn,0)	
	AND ISNULL(BB.REVENUE_CLASS_DESC,'')	= ISNULL(AA.REVENUE_CLASS_DESC,'')	
	AND ISNULL(BB.CUSTOMER_NAME,'')			= ISNULL(AA.CUSTOMER_NAME,'')	
	AND ISNULL(BB.STATUS_DESC,'')			= ISNULL(AA.STATUS_DESC,'')	
	AND ISNULL(BB.TERRITORY_CODE,'')		= ISNULL(AA.TERRITORY_CODE,'')	
	AND ISNULL(BB.LDC_ACCOUNT_NUM,'')		= ISNULL(AA.LDC_ACCOUNT_NUM,'')	
	AND ISNULL(BB.BillingAccountNumber,'')	= ISNULL(AA.BillingAccountNumber,'')
	AND ISNULL(BB.ACCOUNT,'')				= ISNULL(AA.ACCOUNT,'')	
	AND ISNULL(BB.TOTAL,0)					= ISNULL(AA.TOTAL,0)	
	AND ISNULL(BB.UNSTATEMENTED,0)			= ISNULL(AA.UNSTATEMENTED,0)	
	AND ISNULL(BB.[CURRENT],0)				= ISNULL(AA.[CURRENT],0)	
	AND ISNULL(BB.DAYS_1_30,0)				= ISNULL(AA.DAYS_1_30,0)	
	AND ISNULL(BB.DAYS_31_60,0)				= ISNULL(AA.DAYS_31_60,0)	
	AND ISNULL(BB.DAYS_61_90,0)				= ISNULL(AA.DAYS_61_90,0)	
	AND ISNULL(BB.DAYS_91_120,0)			= ISNULL(AA.DAYS_91_120,0)	
	AND ISNULL(BB.DAYS_OVER_120,0)			= ISNULL(AA.DAYS_OVER_120,0)	
	
	COMMIT TRAN
	PRINT 'COMMIT'
END TRY
BEGIN CATCH
	
	SELECT 
        ERROR_NUMBER() AS ErrorNumber,
        ERROR_SEVERITY() AS ErrorSeverity,
        ERROR_STATE() as ErrorState,
        ERROR_PROCEDURE() as ErrorProcedure,
        ERROR_LINE() as ErrorLine,
        ERROR_MESSAGE() as ErrorMessage;

	ROLLBACK TRAN
	PRINT 'ROLLBACK'
END CATCH

