CREATE VIEW [dbo].[VW_ESIIDSERVICESHIST_DELETE_FAIL]
AS
	SELECT *
	FROM ESIIDSERVICEHIST_DELETE
	WHERE ROW_ID NOT IN (
		SELECT DELETE_ID FROM ESIIDSERVICEHIST
		WHERE DELETE_ID IS NOT NULL
	)
