CREATE TABLE [dbo].[CMZONE] (
    [CMZONECODE]   VARCHAR (64) NULL,
    [CMZONENAME]   VARCHAR (64) NULL,
    [STARTTIME]    DATETIME     NULL,
    [STOPTIME]     DATETIME     NULL,
    [ADDTIME]      DATETIME     NULL,
    [ENTITY_ID]    CHAR (15)    NOT NULL,
    [CREATED]      DATETIME     CONSTRAINT [DF_CMZONE_CREATED] DEFAULT (getdate()) NULL,
    [ROW_ID]       INT          IDENTITY (1, 1) NOT NULL,
    [PROCESSED_ID] INT          NULL,
    CONSTRAINT [PK_CMZONE] PRIMARY KEY CLUSTERED ([ROW_ID] ASC),
    CONSTRAINT [FK_CMZONE_LOG_FILE_PROCESSED] FOREIGN KEY ([PROCESSED_ID]) REFERENCES [dbo].[LOG_FILE_PROCESSED] ([ROW_ID]),
    CONSTRAINT [IX_CMZONE] UNIQUE NONCLUSTERED ([CMZONECODE] ASC, [ENTITY_ID] ASC)
);

