CREATE TABLE [dbo].[DAM_PRICE_15MIN] (
    [DELIVERY_DATE]    DATETIME       NOT NULL,
    [SETTLEMENT_POINT] VARCHAR (20)   NULL,
    [INT001]           NUMERIC (9, 4) NULL,
    [INT002]           NUMERIC (9, 4) NULL,
    [INT003]           NUMERIC (9, 4) NULL,
    [INT004]           NUMERIC (9, 4) NULL,
    [INT005]           NUMERIC (9, 4) NULL,
    [INT006]           NUMERIC (9, 4) NULL,
    [INT007]           NUMERIC (9, 4) NULL,
    [INT008]           NUMERIC (9, 4) NULL,
    [INT009]           NUMERIC (9, 4) NULL,
    [INT010]           NUMERIC (9, 4) NULL,
    [INT011]           NUMERIC (9, 4) NULL,
    [INT012]           NUMERIC (9, 4) NULL,
    [INT013]           NUMERIC (9, 4) NULL,
    [INT014]           NUMERIC (9, 4) NULL,
    [INT015]           NUMERIC (9, 4) NULL,
    [INT016]           NUMERIC (9, 4) NULL,
    [INT017]           NUMERIC (9, 4) NULL,
    [INT018]           NUMERIC (9, 4) NULL,
    [INT019]           NUMERIC (9, 4) NULL,
    [INT020]           NUMERIC (9, 4) NULL,
    [INT021]           NUMERIC (9, 4) NULL,
    [INT022]           NUMERIC (9, 4) NULL,
    [INT023]           NUMERIC (9, 4) NULL,
    [INT024]           NUMERIC (9, 4) NULL,
    [INT025]           NUMERIC (9, 4) NULL,
    [INT026]           NUMERIC (9, 4) NULL,
    [INT027]           NUMERIC (9, 4) NULL,
    [INT028]           NUMERIC (9, 4) NULL,
    [INT029]           NUMERIC (9, 4) NULL,
    [INT030]           NUMERIC (9, 4) NULL,
    [INT031]           NUMERIC (9, 4) NULL,
    [INT032]           NUMERIC (9, 4) NULL,
    [INT033]           NUMERIC (9, 4) NULL,
    [INT034]           NUMERIC (9, 4) NULL,
    [INT035]           NUMERIC (9, 4) NULL,
    [INT036]           NUMERIC (9, 4) NULL,
    [INT037]           NUMERIC (9, 4) NULL,
    [INT038]           NUMERIC (9, 4) NULL,
    [INT039]           NUMERIC (9, 4) NULL,
    [INT040]           NUMERIC (9, 4) NULL,
    [INT041]           NUMERIC (9, 4) NULL,
    [INT042]           NUMERIC (9, 4) NULL,
    [INT043]           NUMERIC (9, 4) NULL,
    [INT044]           NUMERIC (9, 4) NULL,
    [INT045]           NUMERIC (9, 4) NULL,
    [INT046]           NUMERIC (9, 4) NULL,
    [INT047]           NUMERIC (9, 4) NULL,
    [INT048]           NUMERIC (9, 4) NULL,
    [INT049]           NUMERIC (9, 4) NULL,
    [INT050]           NUMERIC (9, 4) NULL,
    [INT051]           NUMERIC (9, 4) NULL,
    [INT052]           NUMERIC (9, 4) NULL,
    [INT053]           NUMERIC (9, 4) NULL,
    [INT054]           NUMERIC (9, 4) NULL,
    [INT055]           NUMERIC (9, 4) NULL,
    [INT056]           NUMERIC (9, 4) NULL,
    [INT057]           NUMERIC (9, 4) NULL,
    [INT058]           NUMERIC (9, 4) NULL,
    [INT059]           NUMERIC (9, 4) NULL,
    [INT060]           NUMERIC (9, 4) NULL,
    [INT061]           NUMERIC (9, 4) NULL,
    [INT062]           NUMERIC (9, 4) NULL,
    [INT063]           NUMERIC (9, 4) NULL,
    [INT064]           NUMERIC (9, 4) NULL,
    [INT065]           NUMERIC (9, 4) NULL,
    [INT066]           NUMERIC (9, 4) NULL,
    [INT067]           NUMERIC (9, 4) NULL,
    [INT068]           NUMERIC (9, 4) NULL,
    [INT069]           NUMERIC (9, 4) NULL,
    [INT070]           NUMERIC (9, 4) NULL,
    [INT071]           NUMERIC (9, 4) NULL,
    [INT072]           NUMERIC (9, 4) NULL,
    [INT073]           NUMERIC (9, 4) NULL,
    [INT074]           NUMERIC (9, 4) NULL,
    [INT075]           NUMERIC (9, 4) NULL,
    [INT076]           NUMERIC (9, 4) NULL,
    [INT077]           NUMERIC (9, 4) NULL,
    [INT078]           NUMERIC (9, 4) NULL,
    [INT079]           NUMERIC (9, 4) NULL,
    [INT080]           NUMERIC (9, 4) NULL,
    [INT081]           NUMERIC (9, 4) NULL,
    [INT082]           NUMERIC (9, 4) NULL,
    [INT083]           NUMERIC (9, 4) NULL,
    [INT084]           NUMERIC (9, 4) NULL,
    [INT085]           NUMERIC (9, 4) NULL,
    [INT086]           NUMERIC (9, 4) NULL,
    [INT087]           NUMERIC (9, 4) NULL,
    [INT088]           NUMERIC (9, 4) NULL,
    [INT089]           NUMERIC (9, 4) NULL,
    [INT090]           NUMERIC (9, 4) NULL,
    [INT091]           NUMERIC (9, 4) NULL,
    [INT092]           NUMERIC (9, 4) NULL,
    [INT093]           NUMERIC (9, 4) NULL,
    [INT094]           NUMERIC (9, 4) NULL,
    [INT095]           NUMERIC (9, 4) NULL,
    [INT096]           NUMERIC (9, 4) NULL,
    [INT097]           NUMERIC (9, 4) NULL,
    [INT098]           NUMERIC (9, 4) NULL,
    [INT099]           NUMERIC (9, 4) NULL,
    [INT100]           NUMERIC (9, 4) NULL,
    [CREATED]          DATETIME       CONSTRAINT [DF_DAM_PRICE_15MIN_CREATED] DEFAULT (getdate()) NULL,
    [ROW_ID]           INT            IDENTITY (1, 1) NOT NULL,
    [PROCESSED_ID]     INT            NULL,
    [CREATED_BY]       VARCHAR (50)   NULL,
    [LOG_ID]           INT            NULL,
    CONSTRAINT [PK_DAM_PRICE_15MIN] PRIMARY KEY CLUSTERED ([ROW_ID] ASC),
    CONSTRAINT [FK_DAM_PRICE_15MIN_LOG_DAM_PRICE_DROPPED] FOREIGN KEY ([LOG_ID]) REFERENCES [dbo].[LOG_DAM_PRICE_DROPPED] ([ROW_ID])
);

