CREATE TABLE [dbo].[MARKET_FILE_MAP] (
    [ROW_ID]       INT           IDENTITY (1, 1) NOT NULL,
    [FILE_LOOKUP]  VARCHAR (100) NOT NULL,
    [HAS_STAMP]    BIT           CONSTRAINT [DF_MARKET_FILE_MAP_HAS_STAMP] DEFAULT ((0)) NOT NULL,
    [STAMP_REGEX]  VARCHAR (100) NULL,
    [STAMP_FORMAT] VARCHAR (100) NULL,
    [ENABLED]      BIT           CONSTRAINT [DF_MARKET_FILE_MAP_DISABLED] DEFAULT ((0)) NOT NULL,
    [SEQUENTIAL]   BIT           CONSTRAINT [DF_MARKET_FILE_MAP_SEQUENTIAL] DEFAULT ((1)) NOT NULL,
    [CREATED]      DATETIME      CONSTRAINT [DF_MARKET_FILE_MAP_CREATED] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY]   VARCHAR (50)  NULL,
    CONSTRAINT [PK_MARKET_FILE_MAP] PRIMARY KEY CLUSTERED ([ROW_ID] ASC)
);

