



-- =============================================
-- Author:		Rick Deigsler
-- Create date: 2/22/2008
-- Description:	
-- =============================================
CREATE PROCEDURE [dbo].[usp_pricing_request_offers_sel]

@p_pricing_request_id		varchar(50)

AS

SELECT		a.ID, a.OFFER_ID, 
			ISNULL(a.PRODUCT, '') AS PRODUCT, 
			ISNULL(a.POWER_INDEX, '') AS POWER_INDEX, 
			ISNULL(a.BLOCK_SIZE, '') AS BLOCK_SIZE, 
			ISNULL(a.PEAK_VALUE, 0) AS PEAK_VALUE, 
			ISNULL(a.PEAK_UNIT, '') AS PEAK_UNIT, 
			ISNULL(a.OFF_PEAK_VALUE, 0) AS OFF_PEAK_VALUE, 
			ISNULL(a.OFF_PEAK_UNIT, '') AS OFF_PEAK_UNIT, 
			ISNULL(a.VALUE_24_7, 0) AS VALUE_24_7, 
			ISNULL(a.UNIT_24_7, '') AS UNIT_24_7, 
			ISNULL(a.HENRY_HUB_DAILY, 0) AS HENRY_HUB_DAILY, 
			ISNULL(a.HENRY_HUB_MONTHLY, 0) AS HENRY_HUB_MONTHLY, 
			ISNULL(a.LOOSES_INCLUDED, '') AS LOOSES_INCLUDED, 
			ISNULL(a.ANCILLARY_SERVICES_INCLUDED, '') AS ANCILLARY_SERVICES_INCLUDED, 
			ISNULL(a.ANCILLARY_SERVICES_OPERATING_RESERVE_INCLUDED, '') AS ANCILLARY_SERVICES_OPERATING_RESERVE_INCLUDED, 
			ISNULL(a.CAPACITY, '') AS CAPACITY, 
			ISNULL(a.NETWORK_TRANSMISSION_INCLUDED, '') AS NETWORK_TRANSMISSION_INCLUDED, 
			ISNULL(a.RENEWABLES_INCLUDED, '') AS RENEWABLES_INCLUDED, 
			ISNULL(a.BAND_WITH_INCLUDED, '') AS BAND_WITH_INCLUDED, 
			ISNULL(a.GAS_INDEX_INCUDED, '') AS GAS_INDEX_INCUDED, 
			ISNULL(a.CONSULTANTS_FEE_INCLUDED, '') AS CONSULTANTS_FEE_INCLUDED, 
			ISNULL(a.OTHERS_INCLUDED, '') AS OTHERS_INCLUDED, 
			ISNULL(a.RENEWABLES_VALUE, 0) AS RENEWABLES_VALUE, 
			ISNULL(a.BAND_WITH_VALUE, 0) AS BAND_WITH_VALUE, 
			ISNULL(a.CONSULTANTS_FEE_VALUE, 0) AS CONSULTANTS_FEE_VALUE, 
			ISNULL(a.OTHERS_VALUE, '') AS OTHERS_VALUE, 
			ISNULL(a.LOSSES, 0) AS LOSSES,
			ISNULL(a.STATUS, '') AS STATUS,
			DATE_CREATED,
			IS_REFRESH
FROM		OE_OFFER a WITH (NOLOCK) INNER JOIN OE_PRICING_REQUEST_OFFER b WITH (NOLOCK) ON a.OFFER_ID = b.OFFER_ID
WHERE		b.REQUEST_ID = @p_pricing_request_id
ORDER BY	a.OFFER_ID







