//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4062
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4062.
// 
#pragma warning disable 1591

namespace LibertyPower.DataAccess.WebServiceAccess.IstaWebService.IstaCustomerService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerServiceSoap", Namespace="https://ws.libertypowerbilling.com/CustomerService")]
    public partial class CustomerService : Microsoft.Web.Services2.WebServicesClientProtocol {
        
        private System.Threading.SendOrPostCallback UpdateCustomerGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCustomerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDropRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDropStatusCodeInfoListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CustomerService() {
            this.Url = global::LibertyPower.DataAccess.WebServiceAccess.IstaWebService.Properties.Settings.Default.IstaWebService_IstaCustomerService_CustomerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UpdateCustomerGroupCompletedEventHandler UpdateCustomerGroupCompleted;
        
        /// <remarks/>
        public event UpdateCustomerInfoCompletedEventHandler UpdateCustomerInfoCompleted;
        
        /// <remarks/>
        public event CreateDropRequestCompletedEventHandler CreateDropRequestCompleted;
        
        /// <remarks/>
        public event GetDropStatusCodeInfoListCompletedEventHandler GetDropStatusCodeInfoListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.libertypowerbilling.com/CustomerService/UpdateCustomerGroup", RequestNamespace="https://ws.libertypowerbilling.com/CustomerService", ResponseNamespace="https://ws.libertypowerbilling.com/CustomerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateCustomerGroup(CustomerGroup[] CustomerGroupList) {
            object[] results = this.Invoke("UpdateCustomerGroup", new object[] {
                        CustomerGroupList});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCustomerGroupAsync(CustomerGroup[] CustomerGroupList) {
            this.UpdateCustomerGroupAsync(CustomerGroupList, null);
        }
        
        /// <remarks/>
        public void UpdateCustomerGroupAsync(CustomerGroup[] CustomerGroupList, object userState) {
            if ((this.UpdateCustomerGroupOperationCompleted == null)) {
                this.UpdateCustomerGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCustomerGroupOperationCompleted);
            }
            this.InvokeAsync("UpdateCustomerGroup", new object[] {
                        CustomerGroupList}, this.UpdateCustomerGroupOperationCompleted, userState);
        }
        
        private void OnUpdateCustomerGroupOperationCompleted(object arg) {
            if ((this.UpdateCustomerGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCustomerGroupCompleted(this, new UpdateCustomerGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.libertypowerbilling.com/CustomerService/UpdateCustomerInfo", RequestNamespace="https://ws.libertypowerbilling.com/CustomerService", ResponseNamespace="https://ws.libertypowerbilling.com/CustomerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateCustomerInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Customer Customer) {
            object[] results = this.Invoke("UpdateCustomerInfo", new object[] {
                        Customer});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCustomerInfoAsync(Customer Customer) {
            this.UpdateCustomerInfoAsync(Customer, null);
        }
        
        /// <remarks/>
        public void UpdateCustomerInfoAsync(Customer Customer, object userState) {
            if ((this.UpdateCustomerInfoOperationCompleted == null)) {
                this.UpdateCustomerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCustomerInfoOperationCompleted);
            }
            this.InvokeAsync("UpdateCustomerInfo", new object[] {
                        Customer}, this.UpdateCustomerInfoOperationCompleted, userState);
        }
        
        private void OnUpdateCustomerInfoOperationCompleted(object arg) {
            if ((this.UpdateCustomerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCustomerInfoCompleted(this, new UpdateCustomerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.libertypowerbilling.com/CustomerService/CreateDropRequest", RequestNamespace="https://ws.libertypowerbilling.com/CustomerService", ResponseNamespace="https://ws.libertypowerbilling.com/CustomerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateDropRequest([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] DropRequest DropRequest) {
            this.Invoke("CreateDropRequest", new object[] {
                        DropRequest});
        }
        
        /// <remarks/>
        public void CreateDropRequestAsync(DropRequest DropRequest) {
            this.CreateDropRequestAsync(DropRequest, null);
        }
        
        /// <remarks/>
        public void CreateDropRequestAsync(DropRequest DropRequest, object userState) {
            if ((this.CreateDropRequestOperationCompleted == null)) {
                this.CreateDropRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDropRequestOperationCompleted);
            }
            this.InvokeAsync("CreateDropRequest", new object[] {
                        DropRequest}, this.CreateDropRequestOperationCompleted, userState);
        }
        
        private void OnCreateDropRequestOperationCompleted(object arg) {
            if ((this.CreateDropRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDropRequestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.libertypowerbilling.com/CustomerService/GetDropStatusCodeInfoList", RequestNamespace="https://ws.libertypowerbilling.com/CustomerService", ResponseNamespace="https://ws.libertypowerbilling.com/CustomerService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DropStatusCodeInfo[] GetDropStatusCodeInfoList() {
            object[] results = this.Invoke("GetDropStatusCodeInfoList", new object[0]);
            return ((DropStatusCodeInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDropStatusCodeInfoListAsync() {
            this.GetDropStatusCodeInfoListAsync(null);
        }
        
        /// <remarks/>
        public void GetDropStatusCodeInfoListAsync(object userState) {
            if ((this.GetDropStatusCodeInfoListOperationCompleted == null)) {
                this.GetDropStatusCodeInfoListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDropStatusCodeInfoListOperationCompleted);
            }
            this.InvokeAsync("GetDropStatusCodeInfoList", new object[0], this.GetDropStatusCodeInfoListOperationCompleted, userState);
        }
        
        private void OnGetDropStatusCodeInfoListOperationCompleted(object arg) {
            if ((this.GetDropStatusCodeInfoListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDropStatusCodeInfoListCompleted(this, new GetDropStatusCodeInfoListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/CustomerService")]
    public partial class CustomerGroup {
        
        private int customerIDField;
        
        private string customerGroupNameField;
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerGroupName {
            get {
                return this.customerGroupNameField;
            }
            set {
                this.customerGroupNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/CustomerService")]
    public partial class DropStatusCodeInfo {
        
        private DropStatusCodeOptions statusCodeField;
        
        private string statusReasonField;
        
        /// <remarks/>
        public DropStatusCodeOptions StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusReason {
            get {
                return this.statusReasonField;
            }
            set {
                this.statusReasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/CustomerService")]
    public enum DropStatusCodeOptions {
        
        /// <remarks/>
        A13,
        
        /// <remarks/>
        B38,
        
        /// <remarks/>
        CHA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/CustomerService")]
    public partial class DropRequest {
        
        private int customerIDField;
        
        private string eSIIDField;
        
        private System.DateTime requestDateField;
        
        private DropStatusCodeOptions statusCodeField;
        
        private string statusReasonField;
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string ESIID {
            get {
                return this.eSIIDField;
            }
            set {
                this.eSIIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
            }
        }
        
        /// <remarks/>
        public DropStatusCodeOptions StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusReason {
            get {
                return this.statusReasonField;
            }
            set {
                this.statusReasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/CustomerService")]
    public partial class Customer {
        
        private int customerIDField;
        
        private string customerNameField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string dBAField;
        
        private System.Nullable<int> billingCustomerIDField;
        
        private int masterCustomerIDField;
        
        private string billingContactField;
        
        private string billingAddress1Field;
        
        private string billingAddress2Field;
        
        private string billingCityField;
        
        private string billingStateField;
        
        private string billingZipField;
        
        private string billingPhoneField;
        
        private string billingEmailField;
        
        private string customerGroupNameField;
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string DBA {
            get {
                return this.dBAField;
            }
            set {
                this.dBAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BillingCustomerID {
            get {
                return this.billingCustomerIDField;
            }
            set {
                this.billingCustomerIDField = value;
            }
        }
        
        /// <remarks/>
        public int MasterCustomerID {
            get {
                return this.masterCustomerIDField;
            }
            set {
                this.masterCustomerIDField = value;
            }
        }
        
        /// <remarks/>
        public string BillingContact {
            get {
                return this.billingContactField;
            }
            set {
                this.billingContactField = value;
            }
        }
        
        /// <remarks/>
        public string BillingAddress1 {
            get {
                return this.billingAddress1Field;
            }
            set {
                this.billingAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string BillingAddress2 {
            get {
                return this.billingAddress2Field;
            }
            set {
                this.billingAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string BillingCity {
            get {
                return this.billingCityField;
            }
            set {
                this.billingCityField = value;
            }
        }
        
        /// <remarks/>
        public string BillingState {
            get {
                return this.billingStateField;
            }
            set {
                this.billingStateField = value;
            }
        }
        
        /// <remarks/>
        public string BillingZip {
            get {
                return this.billingZipField;
            }
            set {
                this.billingZipField = value;
            }
        }
        
        /// <remarks/>
        public string BillingPhone {
            get {
                return this.billingPhoneField;
            }
            set {
                this.billingPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string BillingEmail {
            get {
                return this.billingEmailField;
            }
            set {
                this.billingEmailField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerGroupName {
            get {
                return this.customerGroupNameField;
            }
            set {
                this.customerGroupNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void UpdateCustomerGroupCompletedEventHandler(object sender, UpdateCustomerGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCustomerGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCustomerGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void UpdateCustomerInfoCompletedEventHandler(object sender, UpdateCustomerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCustomerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCustomerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void CreateDropRequestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetDropStatusCodeInfoListCompletedEventHandler(object sender, GetDropStatusCodeInfoListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDropStatusCodeInfoListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDropStatusCodeInfoListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DropStatusCodeInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DropStatusCodeInfo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591