//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityManagmentService.Tests.UtiltyManagementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UtiltyManagementService.IUtilityManagementService")]
    public interface IUtilityManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetData", ReplyAction="http://tempuri.org/IUtilityManagementService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetData", ReplyAction="http://tempuri.org/IUtilityManagementService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetAllUtilities", ReplyAction="http://tempuri.org/IUtilityManagementService/GetAllUtilitiesResponse")]
        UtilityManagementServiceData.GetAllUtilitiesResponse GetAllUtilities(string messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetAllUtilities", ReplyAction="http://tempuri.org/IUtilityManagementService/GetAllUtilitiesResponse")]
        System.Threading.Tasks.Task<UtilityManagementServiceData.GetAllUtilitiesResponse> GetAllUtilitiesAsync(string messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetAllUtilitiesNoTrace", ReplyAction="http://tempuri.org/IUtilityManagementService/GetAllUtilitiesNoTraceResponse")]
        UtilityManagementServiceData.GetAllUtilitiesResponse GetAllUtilitiesNoTrace();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetAllUtilitiesNoTrace", ReplyAction="http://tempuri.org/IUtilityManagementService/GetAllUtilitiesNoTraceResponse")]
        System.Threading.Tasks.Task<UtilityManagementServiceData.GetAllUtilitiesResponse> GetAllUtilitiesNoTraceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetAllRequestModeEnrollmentTypes", ReplyAction="http://tempuri.org/IUtilityManagementService/GetAllRequestModeEnrollmentTypesResp" +
            "onse")]
        UtilityManagementServiceData.GetAllRequestModeEnrollmentTypesResponse GetAllRequestModeEnrollmentTypes(string messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetAllRequestModeEnrollmentTypes", ReplyAction="http://tempuri.org/IUtilityManagementService/GetAllRequestModeEnrollmentTypesResp" +
            "onse")]
        System.Threading.Tasks.Task<UtilityManagementServiceData.GetAllRequestModeEnrollmentTypesResponse> GetAllRequestModeEnrollmentTypesAsync(string messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetAllRequestModeEnrollmentTypesNoTr" +
            "ace", ReplyAction="http://tempuri.org/IUtilityManagementService/GetAllRequestModeEnrollmentTypesNoTr" +
            "aceResponse")]
        UtilityManagementServiceData.GetAllRequestModeEnrollmentTypesResponse GetAllRequestModeEnrollmentTypesNoTrace();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetAllRequestModeEnrollmentTypesNoTr" +
            "ace", ReplyAction="http://tempuri.org/IUtilityManagementService/GetAllRequestModeEnrollmentTypesNoTr" +
            "aceResponse")]
        System.Threading.Tasks.Task<UtilityManagementServiceData.GetAllRequestModeEnrollmentTypesResponse> GetAllRequestModeEnrollmentTypesNoTraceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetHistoricalUsageRequestModes", ReplyAction="http://tempuri.org/IUtilityManagementService/GetHistoricalUsageRequestModesRespon" +
            "se")]
        UtilityManagementServiceData.GetHistoricalUsageRequestModeResponse GetHistoricalUsageRequestModes(UtilityManagementServiceData.GetHistoricalUsageRequestModesRequest getHistoricalUsageRequestModeRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetHistoricalUsageRequestModes", ReplyAction="http://tempuri.org/IUtilityManagementService/GetHistoricalUsageRequestModesRespon" +
            "se")]
        System.Threading.Tasks.Task<UtilityManagementServiceData.GetHistoricalUsageRequestModeResponse> GetHistoricalUsageRequestModesAsync(UtilityManagementServiceData.GetHistoricalUsageRequestModesRequest getHistoricalUsageRequestModeRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetIcapRequestModes", ReplyAction="http://tempuri.org/IUtilityManagementService/GetIcapRequestModesResponse")]
        UtilityManagementServiceData.GetIcapRequestModeResponse GetIcapRequestModes(UtilityManagementServiceData.GetIcapRequestModesRequest getIcapRequestModesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetIcapRequestModes", ReplyAction="http://tempuri.org/IUtilityManagementService/GetIcapRequestModesResponse")]
        System.Threading.Tasks.Task<UtilityManagementServiceData.GetIcapRequestModeResponse> GetIcapRequestModesAsync(UtilityManagementServiceData.GetIcapRequestModesRequest getIcapRequestModesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetIdrRequestModes", ReplyAction="http://tempuri.org/IUtilityManagementService/GetIdrRequestModesResponse")]
        UtilityManagementServiceData.GetIdrRequestModeResponse GetIdrRequestModes(UtilityManagementServiceData.GetIdrRequestModesRequest getIdrRequestModesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetIdrRequestModes", ReplyAction="http://tempuri.org/IUtilityManagementService/GetIdrRequestModesResponse")]
        System.Threading.Tasks.Task<UtilityManagementServiceData.GetIdrRequestModeResponse> GetIdrRequestModesAsync(UtilityManagementServiceData.GetIdrRequestModesRequest getIdrRequestModesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetPurchaseOfReceivables", ReplyAction="http://tempuri.org/IUtilityManagementService/GetPurchaseOfReceivablesResponse")]
        UtilityManagementServiceData.GetPurchaseOfReceivablesResponse GetPurchaseOfReceivables(UtilityManagementServiceData.GetPurchaseOfReceivablesRequest getPurchaseOfReceivablesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilityManagementService/GetPurchaseOfReceivables", ReplyAction="http://tempuri.org/IUtilityManagementService/GetPurchaseOfReceivablesResponse")]
        System.Threading.Tasks.Task<UtilityManagementServiceData.GetPurchaseOfReceivablesResponse> GetPurchaseOfReceivablesAsync(UtilityManagementServiceData.GetPurchaseOfReceivablesRequest getPurchaseOfReceivablesRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUtilityManagementServiceChannel : UtilityManagmentService.Tests.UtiltyManagementService.IUtilityManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilityManagementServiceClient : System.ServiceModel.ClientBase<UtilityManagmentService.Tests.UtiltyManagementService.IUtilityManagementService>, UtilityManagmentService.Tests.UtiltyManagementService.IUtilityManagementService {
        
        public UtilityManagementServiceClient() {
        }
        
        public UtilityManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilityManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilityManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilityManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public UtilityManagementServiceData.GetAllUtilitiesResponse GetAllUtilities(string messageId) {
            return base.Channel.GetAllUtilities(messageId);
        }
        
        public System.Threading.Tasks.Task<UtilityManagementServiceData.GetAllUtilitiesResponse> GetAllUtilitiesAsync(string messageId) {
            return base.Channel.GetAllUtilitiesAsync(messageId);
        }
        
        public UtilityManagementServiceData.GetAllUtilitiesResponse GetAllUtilitiesNoTrace() {
            return base.Channel.GetAllUtilitiesNoTrace();
        }
        
        public System.Threading.Tasks.Task<UtilityManagementServiceData.GetAllUtilitiesResponse> GetAllUtilitiesNoTraceAsync() {
            return base.Channel.GetAllUtilitiesNoTraceAsync();
        }
        
        public UtilityManagementServiceData.GetAllRequestModeEnrollmentTypesResponse GetAllRequestModeEnrollmentTypes(string messageId) {
            return base.Channel.GetAllRequestModeEnrollmentTypes(messageId);
        }
        
        public System.Threading.Tasks.Task<UtilityManagementServiceData.GetAllRequestModeEnrollmentTypesResponse> GetAllRequestModeEnrollmentTypesAsync(string messageId) {
            return base.Channel.GetAllRequestModeEnrollmentTypesAsync(messageId);
        }
        
        public UtilityManagementServiceData.GetAllRequestModeEnrollmentTypesResponse GetAllRequestModeEnrollmentTypesNoTrace() {
            return base.Channel.GetAllRequestModeEnrollmentTypesNoTrace();
        }
        
        public System.Threading.Tasks.Task<UtilityManagementServiceData.GetAllRequestModeEnrollmentTypesResponse> GetAllRequestModeEnrollmentTypesNoTraceAsync() {
            return base.Channel.GetAllRequestModeEnrollmentTypesNoTraceAsync();
        }
        
        public UtilityManagementServiceData.GetHistoricalUsageRequestModeResponse GetHistoricalUsageRequestModes(UtilityManagementServiceData.GetHistoricalUsageRequestModesRequest getHistoricalUsageRequestModeRequest) {
            return base.Channel.GetHistoricalUsageRequestModes(getHistoricalUsageRequestModeRequest);
        }
        
        public System.Threading.Tasks.Task<UtilityManagementServiceData.GetHistoricalUsageRequestModeResponse> GetHistoricalUsageRequestModesAsync(UtilityManagementServiceData.GetHistoricalUsageRequestModesRequest getHistoricalUsageRequestModeRequest) {
            return base.Channel.GetHistoricalUsageRequestModesAsync(getHistoricalUsageRequestModeRequest);
        }
        
        public UtilityManagementServiceData.GetIcapRequestModeResponse GetIcapRequestModes(UtilityManagementServiceData.GetIcapRequestModesRequest getIcapRequestModesRequest) {
            return base.Channel.GetIcapRequestModes(getIcapRequestModesRequest);
        }
        
        public System.Threading.Tasks.Task<UtilityManagementServiceData.GetIcapRequestModeResponse> GetIcapRequestModesAsync(UtilityManagementServiceData.GetIcapRequestModesRequest getIcapRequestModesRequest) {
            return base.Channel.GetIcapRequestModesAsync(getIcapRequestModesRequest);
        }
        
        public UtilityManagementServiceData.GetIdrRequestModeResponse GetIdrRequestModes(UtilityManagementServiceData.GetIdrRequestModesRequest getIdrRequestModesRequest) {
            return base.Channel.GetIdrRequestModes(getIdrRequestModesRequest);
        }
        
        public System.Threading.Tasks.Task<UtilityManagementServiceData.GetIdrRequestModeResponse> GetIdrRequestModesAsync(UtilityManagementServiceData.GetIdrRequestModesRequest getIdrRequestModesRequest) {
            return base.Channel.GetIdrRequestModesAsync(getIdrRequestModesRequest);
        }
        
        public UtilityManagementServiceData.GetPurchaseOfReceivablesResponse GetPurchaseOfReceivables(UtilityManagementServiceData.GetPurchaseOfReceivablesRequest getPurchaseOfReceivablesRequest) {
            return base.Channel.GetPurchaseOfReceivables(getPurchaseOfReceivablesRequest);
        }
        
        public System.Threading.Tasks.Task<UtilityManagementServiceData.GetPurchaseOfReceivablesResponse> GetPurchaseOfReceivablesAsync(UtilityManagementServiceData.GetPurchaseOfReceivablesRequest getPurchaseOfReceivablesRequest) {
            return base.Channel.GetPurchaseOfReceivablesAsync(getPurchaseOfReceivablesRequest);
        }
    }
}
