CREATE TABLE [dbo].[AD_SYSTEM_PARAMETERS_GROUP] (
    [ID]    INT          NOT NULL,
    [VALUE] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_SYSTEM_PARAMETERS_GROUP] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

