CREATE TABLE [dbo].[AD_USER] (
    [USER_ID]            NUMERIC (18) NOT NULL,
    [USERNAME]           VARCHAR (50) NOT NULL,
    [NAME]               VARCHAR (50) NULL,
    [LASTNAME]           VARCHAR (50) NULL,
    [APPROVAL_THRESHOLD] NUMERIC (6)  NOT NULL,
    [ROL_ID]             NUMERIC (18) NOT NULL,
    [MATPRICE_PATH]      VARCHAR (50) NULL,
    CONSTRAINT [PK_AD_USER] PRIMARY KEY CLUSTERED ([USER_ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_AD_USER_AD_ROLE] FOREIGN KEY ([ROL_ID]) REFERENCES [dbo].[AD_ROLES] ([ROL_ID]),
    CONSTRAINT [UK_AD_USER] UNIQUE NONCLUSTERED ([USERNAME] ASC) WITH (FILLFACTOR = 90)
);

