CREATE TABLE [dbo].[OE_MATPRICE_FILE] (
    [ID]            INT           IDENTITY (1, 1) NOT NULL,
    [REQUEST_ID]    VARCHAR (50)  NOT NULL,
    [OFFER_ID]      VARCHAR (50)  NOT NULL,
    [BYTES]         IMAGE         NULL,
    [CREATION_DATE] DATETIME      NOT NULL,
    [FILE_NAME]     VARCHAR (100) NOT NULL,
    [PRICE_TYPE]    VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

