CREATE TABLE [dbo].[OE_OFFER_UTILITIES] (
    [OFFER_ID] NVARCHAR (50) NOT NULL,
    [UTILITY]  VARCHAR (50)  NOT NULL
);


GO
CREATE CLUSTERED INDEX [_dta_index_OE_OFFER_UTILITIES_c_99_1246627484__K1_K2]
    ON [dbo].[OE_OFFER_UTILITIES]([OFFER_ID] ASC, [UTILITY] ASC) WITH (FILLFACTOR = 90);

