CREATE TABLE [dbo].[OE_OFFER_MARKET_PRICES_DETAIL] (
    [ID]                   INT             IDENTITY (1, 1) NOT NULL,
    [REQUEST_ID]           VARCHAR (50)    NOT NULL,
    [OFFER_ID]             VARCHAR (50)    NOT NULL,
    [MARKET]               VARCHAR (50)    NOT NULL,
    [FLOW_START_DATE]      DATETIME        NOT NULL,
    [TERM]                 INT             NOT NULL,
    [FINAL_PRICE]          DECIMAL (16, 2) NOT NULL,
    [SENT_TO_DEAL_CAPTURE] INT             NOT NULL,
    [PRODUCT_TYPE]         VARCHAR (50)    NULL,
    [OFFER_EXPIRATION]     DATETIME        CONSTRAINT [DF_OE_OFFER_MARKET_PRICES_DETAIL_OFFER_EXPIRATION] DEFAULT ('12/31/9999') NOT NULL,
    [OFFER_CREATED]        DATETIME        CONSTRAINT [DF_OE_OFFER_MARKET_PRICES_DETAIL_OFFER_CREATED] DEFAULT ('1/1/1901') NOT NULL,
    CONSTRAINT [PK_OFFER_MARKET_PRICES_DETAIL] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

