CREATE TABLE [dbo].[OE_OFFER_NEW_USAGE] (
    [OFFER_ID]      VARCHAR (50) NOT NULL,
    [DATE_INSERTED] DATETIME     CONSTRAINT [DF_OE_OFFER_NEW_USAGE_DATE_INSERTED] DEFAULT (getdate()) NOT NULL,
    [PROCCESSED]    TINYINT      CONSTRAINT [DF_OE_OFFER_NEW_USAGE_PROCCESSED] DEFAULT ((0)) NOT NULL
);

