CREATE TABLE [dbo].[OE_PRICING_REQUEST_OFFER_HISTORY_OFFER] (
    [ID]                               INT      IDENTITY (1, 1) NOT NULL,
    [OFFER_ID]                         INT      NOT NULL,
    [PRICING_REQUEST_OFFER_HISTORY_ID] INT      NOT NULL,
    [DATE_CREATED]                     DATETIME CONSTRAINT [DF_OE_PRICING_REQUEST_OFFER_HISTORY_DATE_CREATED] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_OE_PRICING_REQUEST_OFFER_HISTORY_OFFER] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

