CREATE TABLE [dbo].[OE_PRICING_REQUEST] (
    [ID]                       INT             IDENTITY (1, 1) NOT NULL,
    [REQUEST_ID]               NVARCHAR (50)   NOT NULL,
    [CUSTOMER_NAME]            NVARCHAR (50)   NULL,
    [OPPORTUNITY_NAME]         NVARCHAR (50)   NULL,
    [DUE_DATE]                 DATETIME        NULL,
    [CREATION_DATE]            DATETIME        NULL,
    [TYPE]                     NVARCHAR (50)   NULL,
    [SALES_REPRESENTATIVE]     NVARCHAR (150)  NULL,
    [STATUS]                   NVARCHAR (50)   NULL,
    [TOTAL_NUMBER_OF_ACCOUNTS] NUMERIC (18)    NULL,
    [ANNUAL_ESTIMATED_MHW]     NUMERIC (18)    NULL,
    [COMMENTS]                 NVARCHAR (4000) NULL,
    [CHANGE_REASON]            NVARCHAR (250)  NULL,
    [HOLD_TIME]                DATETIME        NULL,
    [ANALYST]                  NVARCHAR (100)  NULL,
    [APPROVE_COMMENTS]         NVARCHAR (250)  NULL,
    [APPROVE_DATE]             DATETIME        NULL,
    [ACCOUNT_TYPE]             NVARCHAR (50)   CONSTRAINT [DF_OE_PRICING_REQUEST_ACCOUNT_TYPE] DEFAULT ('') NOT NULL,
    [REFRESH_STATUS]           VARCHAR (100)   CONSTRAINT [DF_OE_PRICING_REQUEST_REFRESH_STATUS_1] DEFAULT ('New') NOT NULL,
    [SALES_CHANNEL]            VARCHAR (100)   NULL,
    CONSTRAINT [PK_OE_PRICING_REQUEST] PRIMARY KEY CLUSTERED ([REQUEST_ID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OE_PRICING_REQUEST_99_1278627598__K9_2]
    ON [dbo].[OE_PRICING_REQUEST]([STATUS] ASC)
    INCLUDE([REQUEST_ID]) WITH (FILLFACTOR = 90);

