CREATE TABLE [dbo].[OE_PRICE_MATRIX] (
    [ID]              BIGINT          IDENTITY (1, 1) NOT NULL,
    [FLOW_START_DATE] DATETIME        NULL,
    [1]               DECIMAL (10, 5) NULL,
    [2]               DECIMAL (10, 5) NULL,
    [3]               DECIMAL (10, 5) NULL,
    [4]               DECIMAL (10, 5) NULL,
    [5]               DECIMAL (10, 5) NULL,
    [6]               DECIMAL (10, 5) NULL,
    [7]               DECIMAL (10, 5) NULL,
    [8]               DECIMAL (10, 5) NULL,
    [9]               DECIMAL (10, 5) NULL,
    [10]              DECIMAL (10, 5) NULL,
    [11]              DECIMAL (10, 5) NULL,
    [12]              DECIMAL (10, 5) NULL,
    [13]              DECIMAL (10, 5) NULL,
    [14]              DECIMAL (10, 5) NULL,
    [15]              DECIMAL (10, 5) NULL,
    [16]              DECIMAL (10, 5) NULL,
    [17]              DECIMAL (10, 5) NULL,
    [18]              DECIMAL (10, 5) NULL,
    [19]              DECIMAL (10, 5) NULL,
    [20]              DECIMAL (10, 5) NULL,
    [21]              DECIMAL (10, 5) NULL,
    [22]              DECIMAL (10, 5) NULL,
    [23]              DECIMAL (10, 5) NULL,
    [24]              DECIMAL (10, 5) NULL,
    [25]              DECIMAL (10, 5) NULL,
    [26]              DECIMAL (10, 5) NULL,
    [27]              DECIMAL (10, 5) NULL,
    [28]              DECIMAL (10, 5) NULL,
    [29]              DECIMAL (10, 5) NULL,
    [30]              DECIMAL (10, 5) NULL,
    [31]              DECIMAL (10, 5) NULL,
    [32]              DECIMAL (10, 5) NULL,
    [33]              DECIMAL (10, 5) NULL,
    [34]              DECIMAL (10, 5) NULL,
    [35]              DECIMAL (10, 5) NULL,
    [36]              DECIMAL (10, 5) NULL,
    [37]              DECIMAL (10, 5) NULL,
    [38]              DECIMAL (10, 5) NULL,
    [39]              DECIMAL (10, 5) NULL,
    [40]              DECIMAL (10, 5) NULL,
    [41]              DECIMAL (10, 5) NULL,
    [42]              DECIMAL (10, 5) NULL,
    [43]              DECIMAL (10, 5) NULL,
    [44]              DECIMAL (10, 5) NULL,
    [45]              DECIMAL (10, 5) NULL,
    [46]              DECIMAL (10, 5) NULL,
    [47]              DECIMAL (10, 5) NULL,
    [48]              DECIMAL (10, 5) NULL,
    [LOAD_SHAPE_ID]   VARCHAR (50)    NULL,
    [ZONE]            VARCHAR (50)    NULL,
    [MARKET]          VARCHAR (50)    NULL,
    [UTILITY]         VARCHAR (50)    NULL,
    [FILE_DATE]       DATETIME        NULL,
    [LAST_MODIFIED]   DATETIME        CONSTRAINT [DF_OE_PRICE_MATRIX_LAST_MODIFIED] DEFAULT (getdate()) NOT NULL
);


GO
CREATE CLUSTERED INDEX [idx_flow_load_zone_mkt_util]
    ON [dbo].[OE_PRICE_MATRIX]([FLOW_START_DATE] ASC, [LOAD_SHAPE_ID] ASC, [ZONE] ASC, [MARKET] ASC, [UTILITY] ASC, [FILE_DATE] ASC) WITH (FILLFACTOR = 90);

