CREATE TABLE [dbo].[OE_PRICING_REQUEST_ACCOUNTS] (
    [ID]                 INT          IDENTITY (1, 1) NOT NULL,
    [PRICING_REQUEST_ID] VARCHAR (50) NULL,
    [OE_ACCOUNT_ID]      INT          NOT NULL,
    [ACCOUNT_ID]         VARCHAR (50) NULL,
    [ACCOUNT_NUMBER]     VARCHAR (50) NULL,
    [IS_ACTIVE]          BIT          CONSTRAINT [DF_OE_PRICING_REQUEST_ACCOUNTS_IS_ACTIVE] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_OE_PRICING_REQUEST_ACCOUNTS] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OE_PRICING_REQUEST_ACCOUNTS_99_1822629536__K2_K3]
    ON [dbo].[OE_PRICING_REQUEST_ACCOUNTS]([PRICING_REQUEST_ID] ASC, [OE_ACCOUNT_ID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ndx_pr_an]
    ON [dbo].[OE_PRICING_REQUEST_ACCOUNTS]([PRICING_REQUEST_ID] ASC, [ACCOUNT_NUMBER] ASC) WITH (FILLFACTOR = 90);

