//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerEntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ErcotEntities : DbContext
    {
        public ErcotEntities()
            : base("name=ErcotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<usp_ErcotAccountInfoAccounts_GetZoneAndZipByAccountNumber_Result> usp_ErcotAccountInfoAccounts_GetZoneAndZipByAccountNumber(string accountNumber)
        {
            var accountNumberParameter = accountNumber != null ?
                new ObjectParameter("AccountNumber", accountNumber) :
                new ObjectParameter("AccountNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ErcotAccountInfoAccounts_GetZoneAndZipByAccountNumber_Result>("usp_ErcotAccountInfoAccounts_GetZoneAndZipByAccountNumber", accountNumberParameter);
        }
    }
}
