//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PorDriver
    {
        public PorDriver()
        {
            this.PurchaseOfReceivables = new HashSet<PurchaseOfReceivable>();
            this.LpBillingTypes = new HashSet<LpBillingType>();
            this.UtilityBillingTypes = new HashSet<UtilityBillingType>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public bool Inactive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int EnumValue { get; set; }
    
        public virtual ICollection<PurchaseOfReceivable> PurchaseOfReceivables { get; set; }
        public virtual ICollection<LpBillingType> LpBillingTypes { get; set; }
        public virtual ICollection<UtilityBillingType> UtilityBillingTypes { get; set; }
    }
}
