//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchCriteria
    {
        public SearchCriteria()
        {
            this.SearchToSearchCriterias = new HashSet<SearchToSearchCriteria>();
        }
    
        public System.Guid Id { get; set; }
        public string CriteriaName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SearchToSearchCriteria> SearchToSearchCriterias { get; set; }
    }
}
