//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSlouse
    {
        public TimeSlouse()
        {
            this.AccountsPerZipCodeByTimeSlice = new HashSet<AccountsPerZipCodeByTimeSlouse>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> TimeSliceBeginDate { get; set; }
        public Nullable<System.DateTime> TimeSliceEndDate { get; set; }
    
        public virtual ICollection<AccountsPerZipCodeByTimeSlouse> AccountsPerZipCodeByTimeSlice { get; set; }
    }
}
