//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class USState
    {
        public USState()
        {
            this.ZipCodes = new HashSet<ZipCode>();
        }
    
        public System.Guid Id { get; set; }
        public string StateAbbreviation { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<ZipCode> ZipCodes { get; set; }
    }
}
