//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulkAnnualUsageCalculator.UsageSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsageDateRequest", Namespace="http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    [System.SerializableAttribute()]
    public partial class UsageDateRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UtilityIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UtilityId {
            get {
                return this.UtilityIdField;
            }
            set {
                if ((this.UtilityIdField.Equals(value) != true)) {
                    this.UtilityIdField = value;
                    this.RaisePropertyChanged("UtilityId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdrUsageDateRequest", Namespace="http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    [System.SerializableAttribute()]
    public partial class IdrUsageDateRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UtilityCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppName {
            get {
                return this.AppNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AppNameField, value) != true)) {
                    this.AppNameField = value;
                    this.RaisePropertyChanged("AppName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UtilityCode {
            get {
                return this.UtilityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UtilityCodeField, value) != true)) {
                    this.UtilityCodeField = value;
                    this.RaisePropertyChanged("UtilityCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsageDateResponse", Namespace="http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    [System.SerializableAttribute()]
    public partial class UsageDateResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UsageDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UsageDate {
            get {
                return this.UsageDateField;
            }
            set {
                if ((this.UsageDateField.Equals(value) != true)) {
                    this.UsageDateField = value;
                    this.RaisePropertyChanged("UsageDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsageDateRequestV1", Namespace="http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    [System.SerializableAttribute()]
    public partial class UsageDateRequestV1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UtilityCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UtilityCode {
            get {
                return this.UtilityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UtilityCodeField, value) != true)) {
                    this.UtilityCodeField = value;
                    this.RaisePropertyChanged("UtilityCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EdiUsageRequest", Namespace="http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    [System.SerializableAttribute()]
    public partial class EdiUsageRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DunsNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UtilityCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingAccountNumber {
            get {
                return this.BillingAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingAccountNumberField, value) != true)) {
                    this.BillingAccountNumberField = value;
                    this.RaisePropertyChanged("BillingAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DunsNumber {
            get {
                return this.DunsNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DunsNumberField, value) != true)) {
                    this.DunsNumberField = value;
                    this.RaisePropertyChanged("DunsNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterNumber {
            get {
                return this.MeterNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterNumberField, value) != true)) {
                    this.MeterNumberField = value;
                    this.RaisePropertyChanged("MeterNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameKey {
            get {
                return this.NameKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.NameKeyField, value) != true)) {
                    this.NameKeyField = value;
                    this.RaisePropertyChanged("NameKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Strata {
            get {
                return this.StrataField;
            }
            set {
                if ((object.ReferenceEquals(this.StrataField, value) != true)) {
                    this.StrataField = value;
                    this.RaisePropertyChanged("Strata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsageType {
            get {
                return this.UsageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UsageTypeField, value) != true)) {
                    this.UsageTypeField = value;
                    this.RaisePropertyChanged("UsageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UtilityCode {
            get {
                return this.UtilityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UtilityCodeField, value) != true)) {
                    this.UtilityCodeField = value;
                    this.RaisePropertyChanged("UtilityCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScraperUsageRequest", Namespace="http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    [System.SerializableAttribute()]
    public partial class ScraperUsageRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UtilityIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UtilityId {
            get {
                return this.UtilityIdField;
            }
            set {
                if ((this.UtilityIdField.Equals(value) != true)) {
                    this.UtilityIdField = value;
                    this.RaisePropertyChanged("UtilityId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScraperUsageResponse", Namespace="http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    [System.SerializableAttribute()]
    public partial class ScraperUsageResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TransactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((this.TransactionIdField.Equals(value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnnualUsageRequest", Namespace="http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    [System.SerializableAttribute()]
    public partial class AnnualUsageRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UtilityIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UtilityId {
            get {
                return this.UtilityIdField;
            }
            set {
                if ((this.UtilityIdField.Equals(value) != true)) {
                    this.UtilityIdField = value;
                    this.RaisePropertyChanged("UtilityId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsageAccountRequest", Namespace="http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    [System.SerializableAttribute()]
    public partial class UsageAccountRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UtilityIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UtilityId {
            get {
                return this.UtilityIdField;
            }
            set {
                if ((this.UtilityIdField.Equals(value) != true)) {
                    this.UtilityIdField = value;
                    this.RaisePropertyChanged("UtilityId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnnualUsageBulkResponse", Namespace="http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    [System.SerializableAttribute()]
    public partial class AnnualUsageBulkResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BulkAnnualUsageCalculator.UsageSvc.UsageAccountResponse[] UsageAccountListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BulkAnnualUsageCalculator.UsageSvc.UsageAccountResponse[] UsageAccountList {
            get {
                return this.UsageAccountListField;
            }
            set {
                if ((object.ReferenceEquals(this.UsageAccountListField, value) != true)) {
                    this.UsageAccountListField = value;
                    this.RaisePropertyChanged("UsageAccountList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsageAccountResponse", Namespace="http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    [System.SerializableAttribute()]
    public partial class UsageAccountResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UtilityIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Usage {
            get {
                return this.UsageField;
            }
            set {
                if ((this.UsageField.Equals(value) != true)) {
                    this.UsageField = value;
                    this.RaisePropertyChanged("Usage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UtilityId {
            get {
                return this.UtilityIdField;
            }
            set {
                if ((this.UtilityIdField.Equals(value) != true)) {
                    this.UtilityIdField = value;
                    this.RaisePropertyChanged("UtilityId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IsIdrEligibleRequest", Namespace="http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    [System.SerializableAttribute()]
    public partial class IsIdrEligibleRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UtilityIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UtilityId {
            get {
                return this.UtilityIdField;
            }
            set {
                if ((this.UtilityIdField.Equals(value) != true)) {
                    this.UtilityIdField = value;
                    this.RaisePropertyChanged("UtilityId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsageSvc.IUsage")]
    public interface IUsage {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/GetUsageDate", ReplyAction="http://tempuri.org/IUsage/GetUsageDateResponse")]
        System.DateTime GetUsageDate(BulkAnnualUsageCalculator.UsageSvc.UsageDateRequest usageDateRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/GetUsageDate", ReplyAction="http://tempuri.org/IUsage/GetUsageDateResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetUsageDateAsync(BulkAnnualUsageCalculator.UsageSvc.UsageDateRequest usageDateRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/GetIdrUsageDate", ReplyAction="http://tempuri.org/IUsage/GetIdrUsageDateResponse")]
        BulkAnnualUsageCalculator.UsageSvc.UsageDateResponse GetIdrUsageDate(BulkAnnualUsageCalculator.UsageSvc.IdrUsageDateRequest idrUsageDateRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/GetIdrUsageDate", ReplyAction="http://tempuri.org/IUsage/GetIdrUsageDateResponse")]
        System.Threading.Tasks.Task<BulkAnnualUsageCalculator.UsageSvc.UsageDateResponse> GetIdrUsageDateAsync(BulkAnnualUsageCalculator.UsageSvc.IdrUsageDateRequest idrUsageDateRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/GetUsageDateV1", ReplyAction="http://tempuri.org/IUsage/GetUsageDateV1Response")]
        BulkAnnualUsageCalculator.UsageSvc.UsageDateResponse GetUsageDateV1(BulkAnnualUsageCalculator.UsageSvc.UsageDateRequestV1 usageDateRequestV1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/GetUsageDateV1", ReplyAction="http://tempuri.org/IUsage/GetUsageDateV1Response")]
        System.Threading.Tasks.Task<BulkAnnualUsageCalculator.UsageSvc.UsageDateResponse> GetUsageDateV1Async(BulkAnnualUsageCalculator.UsageSvc.UsageDateRequestV1 usageDateRequestV1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/SubmitHistoricalUsageRequest", ReplyAction="http://tempuri.org/IUsage/SubmitHistoricalUsageRequestResponse")]
        string SubmitHistoricalUsageRequest(BulkAnnualUsageCalculator.UsageSvc.EdiUsageRequest ediUsageRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/SubmitHistoricalUsageRequest", ReplyAction="http://tempuri.org/IUsage/SubmitHistoricalUsageRequestResponse")]
        System.Threading.Tasks.Task<string> SubmitHistoricalUsageRequestAsync(BulkAnnualUsageCalculator.UsageSvc.EdiUsageRequest ediUsageRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/RunScraper", ReplyAction="http://tempuri.org/IUsage/RunScraperResponse")]
        string RunScraper(BulkAnnualUsageCalculator.UsageSvc.ScraperUsageRequest scraperUsageRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/RunScraper", ReplyAction="http://tempuri.org/IUsage/RunScraperResponse")]
        System.Threading.Tasks.Task<string> RunScraperAsync(BulkAnnualUsageCalculator.UsageSvc.ScraperUsageRequest scraperUsageRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/RunScraperWithInstantResponse", ReplyAction="http://tempuri.org/IUsage/RunScraperWithInstantResponseResponse")]
        BulkAnnualUsageCalculator.UsageSvc.ScraperUsageResponse RunScraperWithInstantResponse(BulkAnnualUsageCalculator.UsageSvc.ScraperUsageRequest scraperUsageRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/RunScraperWithInstantResponse", ReplyAction="http://tempuri.org/IUsage/RunScraperWithInstantResponseResponse")]
        System.Threading.Tasks.Task<BulkAnnualUsageCalculator.UsageSvc.ScraperUsageResponse> RunScraperWithInstantResponseAsync(BulkAnnualUsageCalculator.UsageSvc.ScraperUsageRequest scraperUsageRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/GetAnnualUsage", ReplyAction="http://tempuri.org/IUsage/GetAnnualUsageResponse")]
        int GetAnnualUsage(BulkAnnualUsageCalculator.UsageSvc.AnnualUsageRequest annualUsageRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/GetAnnualUsage", ReplyAction="http://tempuri.org/IUsage/GetAnnualUsageResponse")]
        System.Threading.Tasks.Task<int> GetAnnualUsageAsync(BulkAnnualUsageCalculator.UsageSvc.AnnualUsageRequest annualUsageRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/GetAnnualUsageBulk", ReplyAction="http://tempuri.org/IUsage/GetAnnualUsageBulkResponse")]
        BulkAnnualUsageCalculator.UsageSvc.AnnualUsageBulkResponse GetAnnualUsageBulk(string messageId, BulkAnnualUsageCalculator.UsageSvc.UsageAccountRequest[] usageAccountList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/GetAnnualUsageBulk", ReplyAction="http://tempuri.org/IUsage/GetAnnualUsageBulkResponse")]
        System.Threading.Tasks.Task<BulkAnnualUsageCalculator.UsageSvc.AnnualUsageBulkResponse> GetAnnualUsageBulkAsync(string messageId, BulkAnnualUsageCalculator.UsageSvc.UsageAccountRequest[] usageAccountList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/IsIdrEligible", ReplyAction="http://tempuri.org/IUsage/IsIdrEligibleResponse")]
        bool IsIdrEligible(BulkAnnualUsageCalculator.UsageSvc.IsIdrEligibleRequest isIdrEligibleRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/IsIdrEligible", ReplyAction="http://tempuri.org/IUsage/IsIdrEligibleResponse")]
        System.Threading.Tasks.Task<bool> IsIdrEligibleAsync(BulkAnnualUsageCalculator.UsageSvc.IsIdrEligibleRequest isIdrEligibleRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/IsServiceRunning", ReplyAction="http://tempuri.org/IUsage/IsServiceRunningResponse")]
        bool IsServiceRunning();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/IsServiceRunning", ReplyAction="http://tempuri.org/IUsage/IsServiceRunningResponse")]
        System.Threading.Tasks.Task<bool> IsServiceRunningAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/Version", ReplyAction="http://tempuri.org/IUsage/VersionResponse")]
        string Version();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsage/Version", ReplyAction="http://tempuri.org/IUsage/VersionResponse")]
        System.Threading.Tasks.Task<string> VersionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsageChannel : BulkAnnualUsageCalculator.UsageSvc.IUsage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsageClient : System.ServiceModel.ClientBase<BulkAnnualUsageCalculator.UsageSvc.IUsage>, BulkAnnualUsageCalculator.UsageSvc.IUsage {
        
        public UsageClient() {
        }
        
        public UsageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime GetUsageDate(BulkAnnualUsageCalculator.UsageSvc.UsageDateRequest usageDateRequest) {
            return base.Channel.GetUsageDate(usageDateRequest);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetUsageDateAsync(BulkAnnualUsageCalculator.UsageSvc.UsageDateRequest usageDateRequest) {
            return base.Channel.GetUsageDateAsync(usageDateRequest);
        }
        
        public BulkAnnualUsageCalculator.UsageSvc.UsageDateResponse GetIdrUsageDate(BulkAnnualUsageCalculator.UsageSvc.IdrUsageDateRequest idrUsageDateRequest) {
            return base.Channel.GetIdrUsageDate(idrUsageDateRequest);
        }
        
        public System.Threading.Tasks.Task<BulkAnnualUsageCalculator.UsageSvc.UsageDateResponse> GetIdrUsageDateAsync(BulkAnnualUsageCalculator.UsageSvc.IdrUsageDateRequest idrUsageDateRequest) {
            return base.Channel.GetIdrUsageDateAsync(idrUsageDateRequest);
        }
        
        public BulkAnnualUsageCalculator.UsageSvc.UsageDateResponse GetUsageDateV1(BulkAnnualUsageCalculator.UsageSvc.UsageDateRequestV1 usageDateRequestV1) {
            return base.Channel.GetUsageDateV1(usageDateRequestV1);
        }
        
        public System.Threading.Tasks.Task<BulkAnnualUsageCalculator.UsageSvc.UsageDateResponse> GetUsageDateV1Async(BulkAnnualUsageCalculator.UsageSvc.UsageDateRequestV1 usageDateRequestV1) {
            return base.Channel.GetUsageDateV1Async(usageDateRequestV1);
        }
        
        public string SubmitHistoricalUsageRequest(BulkAnnualUsageCalculator.UsageSvc.EdiUsageRequest ediUsageRequest) {
            return base.Channel.SubmitHistoricalUsageRequest(ediUsageRequest);
        }
        
        public System.Threading.Tasks.Task<string> SubmitHistoricalUsageRequestAsync(BulkAnnualUsageCalculator.UsageSvc.EdiUsageRequest ediUsageRequest) {
            return base.Channel.SubmitHistoricalUsageRequestAsync(ediUsageRequest);
        }
        
        public string RunScraper(BulkAnnualUsageCalculator.UsageSvc.ScraperUsageRequest scraperUsageRequest) {
            return base.Channel.RunScraper(scraperUsageRequest);
        }
        
        public System.Threading.Tasks.Task<string> RunScraperAsync(BulkAnnualUsageCalculator.UsageSvc.ScraperUsageRequest scraperUsageRequest) {
            return base.Channel.RunScraperAsync(scraperUsageRequest);
        }
        
        public BulkAnnualUsageCalculator.UsageSvc.ScraperUsageResponse RunScraperWithInstantResponse(BulkAnnualUsageCalculator.UsageSvc.ScraperUsageRequest scraperUsageRequest) {
            return base.Channel.RunScraperWithInstantResponse(scraperUsageRequest);
        }
        
        public System.Threading.Tasks.Task<BulkAnnualUsageCalculator.UsageSvc.ScraperUsageResponse> RunScraperWithInstantResponseAsync(BulkAnnualUsageCalculator.UsageSvc.ScraperUsageRequest scraperUsageRequest) {
            return base.Channel.RunScraperWithInstantResponseAsync(scraperUsageRequest);
        }
        
        public int GetAnnualUsage(BulkAnnualUsageCalculator.UsageSvc.AnnualUsageRequest annualUsageRequest) {
            return base.Channel.GetAnnualUsage(annualUsageRequest);
        }
        
        public System.Threading.Tasks.Task<int> GetAnnualUsageAsync(BulkAnnualUsageCalculator.UsageSvc.AnnualUsageRequest annualUsageRequest) {
            return base.Channel.GetAnnualUsageAsync(annualUsageRequest);
        }
        
        public BulkAnnualUsageCalculator.UsageSvc.AnnualUsageBulkResponse GetAnnualUsageBulk(string messageId, BulkAnnualUsageCalculator.UsageSvc.UsageAccountRequest[] usageAccountList) {
            return base.Channel.GetAnnualUsageBulk(messageId, usageAccountList);
        }
        
        public System.Threading.Tasks.Task<BulkAnnualUsageCalculator.UsageSvc.AnnualUsageBulkResponse> GetAnnualUsageBulkAsync(string messageId, BulkAnnualUsageCalculator.UsageSvc.UsageAccountRequest[] usageAccountList) {
            return base.Channel.GetAnnualUsageBulkAsync(messageId, usageAccountList);
        }
        
        public bool IsIdrEligible(BulkAnnualUsageCalculator.UsageSvc.IsIdrEligibleRequest isIdrEligibleRequest) {
            return base.Channel.IsIdrEligible(isIdrEligibleRequest);
        }
        
        public System.Threading.Tasks.Task<bool> IsIdrEligibleAsync(BulkAnnualUsageCalculator.UsageSvc.IsIdrEligibleRequest isIdrEligibleRequest) {
            return base.Channel.IsIdrEligibleAsync(isIdrEligibleRequest);
        }
        
        public bool IsServiceRunning() {
            return base.Channel.IsServiceRunning();
        }
        
        public System.Threading.Tasks.Task<bool> IsServiceRunningAsync() {
            return base.Channel.IsServiceRunningAsync();
        }
        
        public string Version() {
            return base.Channel.Version();
        }
        
        public System.Threading.Tasks.Task<string> VersionAsync() {
            return base.Channel.VersionAsync();
        }
    }
}
