
-- =============================================
-- Author:		Rick Deigsler
-- Create date: 3/11/2008
-- Description:	
-- =============================================
CREATE PROCEDURE [dbo].[usp_offer_component_details_sel]

@p_market_prices_detail_id	int,
@p_price_type				varchar(50)

AS

IF EXISTS (	SELECT	NULL
			FROM	OE_OFFER_COMPONENT_DETAILS
			WHERE	PRICE_TYPE = @p_price_type )
	BEGIN
		SELECT	PEAK_PRICE, OFF_PEAK_PRICE, ATC, PEAK_MWH, OFF_PEAK_MWH, ICAP, TCAP, 
				RISK_1, RISK_2, RISK_3, TRANSMISSION, ANCILLARY_SERVICES, OPERATING_RESERVE, 
				RENEWABLE_REQUIREMENTS, LOSSES, GREEN_FEES, OTHER, TOTAL_COST, CONSULTANT_FEE, FINANCING_FEE, 
				MARKUP, FIXED_PRICE, BLOCK_PRICE, ADDER_PRICE, CONTRIBUTION_MARGIN, GROSS_MARGIN
		FROM	OE_OFFER_COMPONENT_DETAILS WITH (NOLOCK)
		WHERE	MARKET_PRICES_DETAIL_ID = @p_market_prices_detail_id AND PRICE_TYPE = @p_price_type
	END
ELSE -- original price
	BEGIN
		SELECT	PEAK_PRICE, OFF_PEAK_PRICE, ATC, PEAK_MWH, OFF_PEAK_MWH, ICAP, TCAP, 
				RISK_1, RISK_2, RISK_3, TRANSMISSION, ANCILLARY_SERVICES, OPERATING_RESERVE, 
				RENEWABLE_REQUIREMENTS, LOSSES, GREEN_FEES, OTHER, TOTAL_COST, CONSULTANT_FEE, FINANCING_FEE, 
				MARKUP, FIXED_PRICE, BLOCK_PRICE, ADDER_PRICE, CONTRIBUTION_MARGIN, GROSS_MARGIN
		FROM	OE_OFFER_COMPONENT_DETAILS WITH (NOLOCK)
		WHERE	MARKET_PRICES_DETAIL_ID = @p_market_prices_detail_id AND PRICE_TYPE = 'matPrice'
	END


