CREATE PROCEDURE [dbo].[usp_AccountMeterSelect]

@AccountID	int

AS

SELECT	OE_ACCOUNT_ID,
		ACCOUNT_NUMBER,
		METER_NUMBER
FROM	OE_ACCOUNT_METERS WITH (NOLOCK)
WHERE	OE_ACCOUNT_ID = @AccountID
