USE LIBERTYPOWER
GO

IF not EXISTS( SELECT 1 FROM LIBERTYPOWER..UTILITYFILEDELIMITERS(NOLOCK) WHERE UTILITYCODE='BANGOR')
	BEGIN 
			INSERT INTO LIBERTYPOWER.. UTILITYFILEDELIMITERS
			(
			 UTILITYCODE
			,ROWDELIMITER
			,FIELDDELIMITER
			,CREATED
			,CREATEDBY
			)
				VALUES
				(
				  'BANGOR'
				  ,'~'
				  ,'*'
				  ,GETDATE()
				  ,'VSHARMA'
				)
	END
ELSE 
	BEGIN 

UPDATE UTILITYFILEDELIMITERS SET ROWDELIMITER='~',FIELDDELIMITER='*' WHERE UTILITYCODE='BANGOR'
	END
	
	
	