update lp_transactions..[WebConfigurationValues]
set ConfigurationValue='https://secure.comed.com/MyAccount/MyService/Pages/UsageDataTool.aspx'
where WebPageReference='HomePage' and UtilityCode='COMED'

update lp_transactions..[WebConfigurationValues]
set ConfigurationValue='https://secure.comed.com/MyAccount/MyService/Pages/SummaryDataResults.aspx'
where WebPageReference='BillHistoryPage' and UtilityCode='COMED'

update lp_transactions..[WebConfigurationValues]
set ConfigurationValue='_wpcmWpid=&wpcmVal=&MSOWebPartPage_PostbackSource=&MSOTlPn_SelectedWpId=&MSOTlPn_View=0&MSOTlPn_ShowSettings=False&MSOGallery_SelectedLibrary=&MSOGallery_FilterString=&MSOTlPn_Button=none&__EVENTTARGET=#EVENTTARGET#&__EVENTARGUMENT=&__REQUESTDIGEST=#REQUESTDIGEST#&MSOSPWebPartManager_DisplayModeName=Browse&MSOSPWebPartManager_ExitingDesignMode=false&MSOWebPartPage_Shared=&MSOLayout_LayoutChanges=&MSOLayout_InDesignMode=&_wpSelected=&_wzSelected=&MSOSPWebPartManager_OldDisplayModeName=Browse&MSOSPWebPartManager_StartWebPartEditingName=false&MSOSPWebPartManager_EndWebPartEditing=false&__LASTFOCUS=&__VIEWSTATE=%2FwEPDwUJMjQ3NzYxNTU1D2QWAmYPZBYCAgEPZBYEAgEPZBYEAgYPZBYCZg9kFgICAQ8WAh4TUHJldmlvdXNDb250cm9sTW9kZQspiAFNaWNyb3NvZnQuU2hhcmVQb2ludC5XZWJDb250cm9scy5TUENvbnRyb2xNb2RlLCBNaWNyb3NvZnQuU2hhcmVQb2ludCwgVmVyc2lvbj0xNS4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj03MWU5YmNlMTExZTk0MjljAWQCKg9kFgQCAQ9kFgICBQ8WAh8ACysEAWQCAw9kFgJmD2QWAmYPPCsABgBkAgkPZBYIAgEPZBYCAgEPZBYCBSZnXzg2ZGFhZjEwX2ZiMzFfNGY2ZF9hZGYzX2Q3YzM4NGYxMjhhMw9kFgJmD2QWBAIBDxBkZBYAZAIFDxBkZBYAZAITD2QWAgIFD2QWAgIDDxYCHgdWaXNpYmxlaBYCZg9kFgQCAg9kFgYCAQ8WAh8BaGQCAw8WAh8BaGQCBQ8WAh8BaGQCAw8PFgIeCUFjY2Vzc0tleQUBL2RkAjsPZBYCAgIPZBYEAhUPFgIfAAsrBAFkAhcPFgIfAAsrBAFkAncPZBYCAgMPFgIfAAsrBAFkZNxqtlOP1VlB%2Bf0BHQKOpJnIPbio2y0swu2txKmZK1d7&__VIEWSTATEGENERATOR=E3165DA7&__EVENTVALIDATION=#EVENTVALIDATION#&Username=&Password=&ctl00%24ctl72%24g_86daaf10_fb31_4f6d_adf3_d7c384f128a3%24ctl00%24RequestOption=1'
where WebPageReference='HomePageData2' and UtilityCode='COMED'

update lp_transactions..[WebConfigurationValues]
set ConfigurationValue='_wpcmWpid=&wpcmVal=&MSOWebPartPage_PostbackSource=&MSOTlPn_SelectedWpId=&MSOTlPn_View=0&MSOTlPn_ShowSettings=False&MSOGallery_SelectedLibrary=&MSOGallery_FilterString=&MSOTlPn_Button=none&__EVENTTARGET=#EVENTTARGET#&__EVENTARGUMENT=&__REQUESTDIGEST=#REQUESTDIGEST#&MSOSPWebPartManager_DisplayModeName=Browse&MSOSPWebPartManager_ExitingDesignMode=false&MSOWebPartPage_Shared=&MSOLayout_LayoutChanges=&MSOLayout_InDesignMode=&_wpSelected=&_wzSelected=&MSOSPWebPartManager_OldDisplayModeName=Browse&MSOSPWebPartManager_StartWebPartEditingName=false&MSOSPWebPartManager_EndWebPartEditing=false&__LASTFOCUS=&__VIEWSTATE=#VIEWSTATE#&__VIEWSTATEGENERATOR=E3165DA7&__EVENTVALIDATION=#EVENTVALIDATION#&Username=&Password=&ctl00%24ctl72%24g_86daaf10_fb31_4f6d_adf3_d7c384f128a3%24ctl00%24RequestOption=1&ctl00%24ctl72%24g_86daaf10_fb31_4f6d_adf3_d7c384f128a3%24ctl00%24AccountNumber=#ACCOUNTNUMBER#'
where WebPageReference='HomePageData3' and UtilityCode='COMED'

