CREATE TABLE [dbo].[zAuditBillingAccountPattern] (
    [Id]                                          UNIQUEIDENTIFIER NOT NULL,
    [UtilityCompanyId]                            UNIQUEIDENTIFIER NOT NULL,
    [BillingAccountPattern]                       NVARCHAR (255)   NULL,
    [BillingAccountPatternDescription]            NVARCHAR (255)   NOT NULL,
    [BillingAccountAddLeadingZero]                INT              NULL,
    [BillingAccountTruncateLast]                  INT              NULL,
    [BillingAccountRequiredForEDIRequest]         BIT              NOT NULL,
    [Inactive]                                    BIT              NOT NULL,
    [CreatedBy]                                   NVARCHAR (100)   NOT NULL,
    [CreatedDate]                                 DATETIME         NOT NULL,
    [LastModifiedBy]                              NVARCHAR (100)   NOT NULL,
    [LastModifiedDate]                            DATETIME         NOT NULL,
    [IdPrevious]                                  UNIQUEIDENTIFIER NULL,
    [UtilityCompanyIdPrevious]                    UNIQUEIDENTIFIER NULL,
    [BillingAccountPatternPrevious]               NVARCHAR (255)   NULL,
    [BillingAccountPatternDescriptionPrevious]    NVARCHAR (255)   NULL,
    [BillingAccountAddLeadingZeroPrevious]        INT              NULL,
    [BillingAccountTruncateLastPrevious]          INT              NULL,
    [BillingAccountRequiredForEDIRequestPrevious] BIT              NULL,
    [InactivePrevious]                            BIT              NULL,
    [CreatedByPrevious]                           NVARCHAR (100)   NULL,
    [CreatedDatePrevious]                         DATETIME         NULL,
    [LastModifiedByPrevious]                      NVARCHAR (100)   NULL,
    [LastModifiedDatePrevious]                    DATETIME         NULL,
    [SYS_CHANGE_VERSION]                          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION]                 BIGINT           NULL,
    [SYS_CHANGE_OPERATION]                        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]                          NVARCHAR (1000)  NULL,
    [IdPrimary]                                   UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [PK_zAuditBillingAccountPattern] PRIMARY KEY CLUSTERED ([IdPrimary] ASC)
);

