CREATE TABLE [dbo].[zAuditRequestModeIdr] (
    [Id]                                                UNIQUEIDENTIFIER NOT NULL,
    [UtilityCompanyId]                                  UNIQUEIDENTIFIER NOT NULL,
    [RequestModeEnrollmentTypeId]                       UNIQUEIDENTIFIER NOT NULL,
    [RequestModeTypeId]                                 UNIQUEIDENTIFIER NOT NULL,
    [AddressForPreEnrollment]                           NVARCHAR (255)   NOT NULL,
    [EmailTemplate]                                     NVARCHAR (2000)  NOT NULL,
    [Instructions]                                      NVARCHAR (500)   NOT NULL,
    [UtilitysSlaIdrResponseInDays]                      INT              NOT NULL,
    [LibertyPowersSlaFollowUpIdrResponseInDays]         INT              NOT NULL,
    [IsLoaRequired]                                     BIT              NOT NULL,
    [RequestCostAccount]                                MONEY            NOT NULL,
    [Inactive]                                          BIT              NOT NULL,
    [CreatedBy]                                         NVARCHAR (100)   NOT NULL,
    [CreatedDate]                                       DATETIME         NOT NULL,
    [LastModifiedBy]                                    NVARCHAR (100)   NOT NULL,
    [LastModifiedDate]                                  DATETIME         NOT NULL,
    [IdPrevious]                                        UNIQUEIDENTIFIER NULL,
    [UtilityCompanyIdPrevious]                          UNIQUEIDENTIFIER NULL,
    [RequestModeEnrollmentTypeIdPrevious]               UNIQUEIDENTIFIER NULL,
    [RequestModeTypeIdPrevious]                         UNIQUEIDENTIFIER NULL,
    [AddressForPreEnrollmentPrevious]                   NVARCHAR (255)   NULL,
    [EmailTemplatePrevious]                             NVARCHAR (2000)  NULL,
    [InstructionsPrevious]                              NVARCHAR (500)   NULL,
    [UtilitysSlaIdrResponseInDaysPrevious]              INT              NULL,
    [LibertyPowersSlaFollowUpIdrResponseInDaysPrevious] INT              NULL,
    [IsLoaRequiredPrevious]                             BIT              NULL,
    [RequestCostAccountPrevious]                        MONEY            NULL,
    [InactivePrevious]                                  BIT              NULL,
    [CreatedByPrevious]                                 NVARCHAR (100)   NULL,
    [CreatedDatePrevious]                               DATETIME         NULL,
    [LastModifiedByPrevious]                            NVARCHAR (100)   NULL,
    [LastModifiedDatePrevious]                          DATETIME         NULL,
    [SYS_CHANGE_VERSION]                                BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION]                       BIGINT           NULL,
    [SYS_CHANGE_OPERATION]                              NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]                                NVARCHAR (1000)  NULL,
    [IdPrimary]                                         UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [AlwaysRequest]                                     BIT              NULL,
    [AlwaysRequestPrevious]                             BIT              NULL,
    CONSTRAINT [PK_zAuditRequestModeIdr] PRIMARY KEY CLUSTERED ([IdPrimary] ASC)
);



