//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsPerZipCodeByTimeSlouse
    {
        public System.Guid Id { get; set; }
        public System.Guid ZipCodeId { get; set; }
        public decimal NumberOfAccounts { get; set; }
        public Nullable<System.Guid> TimeSliceId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual TimeSlouse TimeSlouse { get; set; }
        public virtual ZipCode ZipCode { get; set; }
    }
}
