//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterType
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UtilityCompanyId { get; set; }
        public string MeterTypeCode { get; set; }
        public string Description { get; set; }
        public System.Guid AccountTypeId { get; set; }
        public string LpStandardMeterType { get; set; }
        public int Sequence { get; set; }
        public bool Inactive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual UtilityCompany UtilityCompany { get; set; }
    }
}
