//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTerm
    {
        public System.Guid Id { get; set; }
        public System.Guid UtilityCompanyId { get; set; }
        public System.Guid MarketId { get; set; }
        public System.Guid BillingTypeId { get; set; }
        public System.Guid BusinessAccountTypeId { get; set; }
        public string PaymentTerm1 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public bool Inactive { get; set; }
    
        public virtual BillingType BillingType { get; set; }
        public virtual BusinessAccountType BusinessAccountType { get; set; }
        public virtual Market Market { get; set; }
        public virtual UtilityCompany UtilityCompany { get; set; }
    }
}
