//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriStateValue
    {
        public TriStateValue()
        {
            this.RequestModeHistoricalUsageParameters = new HashSet<RequestModeHistoricalUsageParameter>();
            this.RequestModeHistoricalUsageParameters1 = new HashSet<RequestModeHistoricalUsageParameter>();
            this.RequestModeHistoricalUsageParameters2 = new HashSet<RequestModeHistoricalUsageParameter>();
            this.RequestModeHistoricalUsageParameters3 = new HashSet<RequestModeHistoricalUsageParameter>();
            this.RequestModeHistoricalUsageParameters4 = new HashSet<RequestModeHistoricalUsageParameter>();
            this.RequestModeHistoricalUsageParameters5 = new HashSet<RequestModeHistoricalUsageParameter>();
            this.RequestModeHistoricalUsageParameters6 = new HashSet<RequestModeHistoricalUsageParameter>();
            this.RequestModeHistoricalUsageParameters7 = new HashSet<RequestModeHistoricalUsageParameter>();
            this.RequestModeHistoricalUsageParameters8 = new HashSet<RequestModeHistoricalUsageParameter>();
            this.RequestModeHistoricalUsageParameters9 = new HashSet<RequestModeHistoricalUsageParameter>();
            this.RequestModeHistoricalUsageParameters10 = new HashSet<RequestModeHistoricalUsageParameter>();
            this.RequestModeHistoricalUsageParameters11 = new HashSet<RequestModeHistoricalUsageParameter>();
            this.RequestModeHistoricalUsageParameters12 = new HashSet<RequestModeHistoricalUsageParameter>();
            this.RequestModeHistoricalUsageParameters121 = new HashSet<RequestModeHistoricalUsageParameter>();
        }
    
        public System.Guid Id { get; set; }
        public string Value { get; set; }
        public int NumericValue { get; set; }
        public string Description { get; set; }
        public bool Inactive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        public virtual ICollection<RequestModeHistoricalUsageParameter> RequestModeHistoricalUsageParameters { get; set; }
        public virtual ICollection<RequestModeHistoricalUsageParameter> RequestModeHistoricalUsageParameters1 { get; set; }
        public virtual ICollection<RequestModeHistoricalUsageParameter> RequestModeHistoricalUsageParameters2 { get; set; }
        public virtual ICollection<RequestModeHistoricalUsageParameter> RequestModeHistoricalUsageParameters3 { get; set; }
        public virtual ICollection<RequestModeHistoricalUsageParameter> RequestModeHistoricalUsageParameters4 { get; set; }
        public virtual ICollection<RequestModeHistoricalUsageParameter> RequestModeHistoricalUsageParameters5 { get; set; }
        public virtual ICollection<RequestModeHistoricalUsageParameter> RequestModeHistoricalUsageParameters6 { get; set; }
        public virtual ICollection<RequestModeHistoricalUsageParameter> RequestModeHistoricalUsageParameters7 { get; set; }
        public virtual ICollection<RequestModeHistoricalUsageParameter> RequestModeHistoricalUsageParameters8 { get; set; }
        public virtual ICollection<RequestModeHistoricalUsageParameter> RequestModeHistoricalUsageParameters9 { get; set; }
        public virtual ICollection<RequestModeHistoricalUsageParameter> RequestModeHistoricalUsageParameters10 { get; set; }
        public virtual ICollection<RequestModeHistoricalUsageParameter> RequestModeHistoricalUsageParameters11 { get; set; }
        public virtual ICollection<RequestModeHistoricalUsageParameter> RequestModeHistoricalUsageParameters12 { get; set; }
        public virtual ICollection<RequestModeHistoricalUsageParameter> RequestModeHistoricalUsageParameters121 { get; set; }
    }
}
