--use OnlineEnrollment
--go

ALTER TABLE Contract ADD BillingAccount VARCHAR(50) DEFAULT NULL
ALTER TABLE Contract ADD MeterDataMgmtAgent VARCHAR(50) DEFAULT NULL
ALTER TABLE Contract ADD MeterInstaller VARCHAR(50) DEFAULT NULL
ALTER TABLE Contract ADD MeterReader VARCHAR(50) DEFAULT NULL
ALTER TABLE Contract ADD MeterOwner VARCHAR(50) DEFAULT NULL
ALTER TABLE Contract ADD MeterServiceProvider VARCHAR(50) DEFAULT NULL
ALTER TABLE Contract ADD NameKey VARCHAR(50) DEFAULT NULL
ALTER TABLE Contract ADD SchedulingCoordinator VARCHAR(50) DEFAULT NULL