//------------------------------------------------------------------------------
// <auto-generated>
//    This file was generated by EnumGenerator.ttinclude
//    Manual changes to this file will be overwritten when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;


namespace LibertyPower.DataAccess.SqlAccess.CustomerManagementEF.AutoEnums
{
	/// <summary>
	/// Auto generated enumeration for ContractDealType lookup table
	/// </summary>
	[GeneratedCode("TextTemplatingFileGenerator", "10")]
	public enum ContractDealTypeEnum
	{
		New = 1,		//New
		Renewal = 2,		//Renewal
		Conversion = 3		//Conversion
	}
}
