CREATE TABLE [dbo].[RateChange] (
    [ID]                         INT              IDENTITY (1, 1) NOT NULL,
    [AccountNumber]              VARCHAR (50)     NOT NULL,
    [EffectiveDate]              DATETIME         NOT NULL,
    [Markup]                     DECIMAL (18, 10) NOT NULL,
    [MeterType]                  VARCHAR (50)     NULL,
    [PreviousRate]               DECIMAL (18, 10) NOT NULL,
    [Rate]                       DECIMAL (18, 10) NOT NULL,
    [RateCode]                   VARCHAR (50)     NULL,
    [RateUpdateType]             INT              NOT NULL,
    [ServiceClass]               VARCHAR (50)     NULL,
    [UtilityID]                  VARCHAR (50)     NOT NULL,
    [Zone]                       VARCHAR (50)     NULL,
    [FileGuid]                   UNIQUEIDENTIFIER NOT NULL,
    [Status]                     INT              NOT NULL,
    [StatusNotes]                VARCHAR (512)    NULL,
    [RateChangeQueueID]          INT              NOT NULL,
    [CreatedBy]                  INT              NOT NULL,
    [DateCreated]                DATETIME         CONSTRAINT [DF_RateUpdate_DateCreated] DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]                 INT              NOT NULL,
    [DateModified]               DATETIME         CONSTRAINT [DF_RateUpdate_DateModified] DEFAULT (getdate()) NOT NULL,
    [ProcessedBy]                INT              NULL,
    [EffectiveBillingCycleStart] DATETIME         NULL,
    [EffectiveBillingCycleEnd]   DATETIME         NULL,
    [Usage]                      DECIMAL (18, 10) NULL,
    [AverageEnergy]              DECIMAL (18, 10) NULL,
    [AncillaryService]           DECIMAL (18, 10) NULL,
    [OtherAncillary]             DECIMAL (18, 10) NULL,
    [RPSPrice]                   DECIMAL (18, 10) NULL,
    [Energy]                     DECIMAL (18, 10) NULL,
    [EnergyLoss]                 DECIMAL (18, 10) NULL,
    [Ucap]                       DECIMAL (18, 10) NULL,
    [Tcap]                       DECIMAL (18, 10) NULL,
    [IcapMethod]                 INT              NULL,
    [IcapScalar]                 DECIMAL (18, 10) NULL,
    [TCapMethod]                 INT              NULL,
    [TcapScalar]                 DECIMAL (18, 10) NULL,
    [ARRCharge]                  DECIMAL (18, 10) NULL,
    [BillingTransactionFee]      DECIMAL (18, 10) NULL,
    [MiscAdder]                  DECIMAL (18, 10) NULL,
    [VREEngineVersion]           VARCHAR (50)     NULL,
    [ContextDate]                DATETIME         CONSTRAINT [DF_RateChange_ContextDate] DEFAULT (getdate()) NOT NULL,
    [RawStartingDate]            DATETIME         NULL,
    [RawEndingDate]              DATETIME         NULL,
    [PlanType]                   INT              NULL,
    [DateFrom1ReadBack]          DATETIME         NULL,
    [DateTo1ReadBack]            DATETIME         NULL,
    [DateFrom2ReadBack]          DATETIME         NULL,
    [DateTo2ReadBack]            DATETIME         NULL,
    [DateFrom3ReadBack]          DATETIME         NULL,
    [DateTo3ReadBack]            DATETIME         NULL,
    [PastUsage1]                 DECIMAL (18, 10) NULL,
    [PastUsage2]                 DECIMAL (18, 10) NULL,
    [PastUsage3]                 DECIMAL (18, 10) NULL,
    [SplitDate]                  DATETIME         NULL,
    [IsRateReady]                BIT              NULL,
    [VreAccountTypeID]           INT              NULL,
    [SimpleIndexAdder]           DECIMAL (18, 10) NULL,
    CONSTRAINT [PK_RateChange] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'0=Unknown; 1=DefaultVariable; 2=CustomVariable; 3=Renewal; 4=CustomBilling', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'RateChange', @level2type = N'COLUMN', @level2name = N'RateUpdateType';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'0=Unsent; 1=SentAccepted; 2=SentRejected', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'RateChange', @level2type = N'COLUMN', @level2name = N'Status';

