//------------------------------------------------------------------------------
// <auto-generated>
//    This file was generated by EnumGenerator.ttinclude
//    Manual changes to this file will be overwritten when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;


namespace LibertyPower.DataAccess.SqlAccess.CustomerManagementEF.AutoEnums
{
	/// <summary>
	/// Auto generated enumeration for EnrollmentType lookup table
	/// </summary>
	[GeneratedCode("TextTemplatingFileGenerator", "10")]
	public enum EnrollmentTypeEnum
	{
		Standard = 1,		//Standard
		MoveIn = 3,		//Move In
		MoveInCurrentlyDeenergized = 4,		//Move In - Currently De-energized
		SelfSelected = 5,		//Self Selected
		OffcyclePriority = 6,		//Offcycle Priority
		StandardFutureMonth = 8,		//Standard (Future Month)
		DonotEnroll = 9		//Do not Enroll
	}
}
