CREATE TABLE [dbo].[OE_ACCOUNT_METERS] (
    [OE_ACCOUNT_ID]  INT          NOT NULL,
    [ACCOUNT_NUMBER] VARCHAR (50) NULL,
    [METER_NUMBER]   VARCHAR (50) NULL
);


GO
CREATE CLUSTERED INDEX [_dta_index_OE_ACCOUNT_METERS_c_99_1662628966__K1_K2]
    ON [dbo].[OE_ACCOUNT_METERS]([OE_ACCOUNT_ID] ASC, [ACCOUNT_NUMBER] ASC) WITH (FILLFACTOR = 90);

