CREATE TABLE [dbo].[OE_EPR_LOGS] (
    [ID]         INT           IDENTITY (1, 1) NOT NULL,
    [REQUEST_ID] NVARCHAR (50) NOT NULL,
    [DATE_LOG]   DATETIME      NULL,
    CONSTRAINT [PK_OE_EPR_LOGS] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

