CREATE TABLE [dbo].[OE_OFFER_MARKETS] (
    [OFFER_ID] NVARCHAR (50) NOT NULL,
    [MARKET]   VARCHAR (25)  NOT NULL
);


GO
CREATE CLUSTERED INDEX [_dta_index_OE_OFFER_MARKETS_c_99_1102626971__K2]
    ON [dbo].[OE_OFFER_MARKETS]([MARKET] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OE_OFFER_MARKETS_99_1102626971__K1]
    ON [dbo].[OE_OFFER_MARKETS]([OFFER_ID] ASC) WITH (FILLFACTOR = 90);

