CREATE TABLE [dbo].[OE_OFFER_ACCOUNTS] (
    [ID]             INT          IDENTITY (1, 1) NOT NULL,
    [OFFER_ID]       VARCHAR (50) NOT NULL,
    [OE_ACCOUNT_ID]  INT          NOT NULL,
    [ACCOUNT_ID]     VARCHAR (50) NULL,
    [ACCOUNT_NUMBER] VARCHAR (50) NULL,
    CONSTRAINT [PK_OE_OFFER_ACCOUNTS] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OE_OFFER_ACCOUNTS_99_1790629422__K2_K5_K3]
    ON [dbo].[OE_OFFER_ACCOUNTS]([OFFER_ID] ASC, [ACCOUNT_NUMBER] ASC, [OE_ACCOUNT_ID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OE_OFFER_ACCOUNTS_99_1790629422__K3_K2]
    ON [dbo].[OE_OFFER_ACCOUNTS]([OE_ACCOUNT_ID] ASC, [OFFER_ID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [idx_account_number]
    ON [dbo].[OE_OFFER_ACCOUNTS]([ACCOUNT_NUMBER] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = OFF);

