CREATE TABLE [dbo].[zOE_OFFER_AUDIT-051110] (
    [ID]                                            INT             IDENTITY (1, 1) NOT NULL,
    [OFFER_ID]                                      NVARCHAR (50)   NOT NULL,
    [PRODUCT]                                       NVARCHAR (50)   NULL,
    [POWER_INDEX]                                   NVARCHAR (10)   NULL,
    [BLOCK_SIZE]                                    NVARCHAR (50)   NULL,
    [PEAK_VALUE]                                    DECIMAL (16, 2) NULL,
    [PEAK_UNIT]                                     NVARCHAR (2)    NULL,
    [OFF_PEAK_VALUE]                                DECIMAL (16, 2) NULL,
    [OFF_PEAK_UNIT]                                 NVARCHAR (2)    NULL,
    [VALUE_24_7]                                    DECIMAL (16, 2) NULL,
    [UNIT_24_7]                                     NVARCHAR (2)    NULL,
    [HENRY_HUB_DAILY]                               NUMERIC (1)     NULL,
    [HENRY_HUB_MONTHLY]                             NUMERIC (1)     NULL,
    [LOOSES_INCLUDED]                               NVARCHAR (50)   NULL,
    [ANCILLARY_SERVICES_INCLUDED]                   NVARCHAR (50)   NULL,
    [ANCILLARY_SERVICES_OPERATING_RESERVE_INCLUDED] NVARCHAR (50)   NULL,
    [CAPACITY]                                      NVARCHAR (50)   NULL,
    [NETWORK_TRANSMISSION_INCLUDED]                 NVARCHAR (50)   NULL,
    [RENEWABLES_INCLUDED]                           NVARCHAR (50)   NULL,
    [BAND_WITH_INCLUDED]                            NVARCHAR (50)   NULL,
    [GAS_INDEX_INCUDED]                             NVARCHAR (50)   NULL,
    [CONSULTANTS_FEE_INCLUDED]                      NVARCHAR (50)   NULL,
    [OTHERS_INCLUDED]                               NVARCHAR (50)   NULL,
    [RENEWABLES_VALUE]                              DECIMAL (16, 2) NULL,
    [BAND_WITH_VALUE]                               DECIMAL (16, 2) NULL,
    [CONSULTANTS_FEE_VALUE]                         DECIMAL (16, 2) NULL,
    [OTHERS_VALUE]                                  NVARCHAR (50)   NULL,
    [LOSSES]                                        DECIMAL (18)    NULL,
    [STATUS]                                        NVARCHAR (50)   NULL,
    [AUDIT_CHANGE_TYPE]                             CHAR (3)        NOT NULL,
    [AUDIT_CHANGE_DATE]                             DATETIME        CONSTRAINT [DF_zOE_OFFER_AUDIT_AUDIT_CHANGE_DATE] DEFAULT (getdate()) NOT NULL,
    [AUDIT_CHANGE_BY]                               VARCHAR (30)    CONSTRAINT [DF_zOE_OFFER_AUDIT_AUDIT_CHANGE_BY] DEFAULT (substring(suser_sname(),(1),(30))) NOT NULL,
    [AUDIT_CHANGE_LOCATION]                         VARCHAR (30)    CONSTRAINT [DF_zOE_OFFER_AUDIT_AUDIT_CHANGE_LOCATION] DEFAULT (substring(host_name(),(1),(30))) NOT NULL,
    CONSTRAINT [PK_zOE_OFFER] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

