CREATE TABLE [dbo].[zOE_ACCOUNT_AUDIT-051110] (
    [ID]                    INT             IDENTITY (1, 1) NOT NULL,
    [ACCOUNT_NUMBER]        VARCHAR (50)    NULL,
    [ACCOUNT_ID]            VARCHAR (50)    NULL,
    [MARKET]                VARCHAR (25)    NULL,
    [UTILITY]               VARCHAR (50)    NULL,
    [METER_TYPE]            VARCHAR (50)    NULL,
    [RATE_CLASS]            VARCHAR (50)    NULL,
    [VOLTAGE]               VARCHAR (50)    NULL,
    [ZONE]                  VARCHAR (50)    NULL,
    [VAL_COMMENT]           NCHAR (256)     NULL,
    [TCAP]                  DECIMAL (18, 9) NULL,
    [ICAP]                  DECIMAL (18, 9) NULL,
    [LOAD_SHAPE_ID]         VARCHAR (50)    NULL,
    [LOSSES]                DECIMAL (18, 9) NULL,
    [ANNUAL_USAGE]          BIGINT          CONSTRAINT [DF__zOE_ACCOUN__ANNUA__625A9A57] DEFAULT ((1)) NULL,
    [USAGE_DATE]            DATETIME        CONSTRAINT [DF_zOE_ACCOUNT_USAGE_DATE] DEFAULT (((1)/(1))/(1900)) NOT NULL,
    [AUDIT_CHANGE_TYPE]     CHAR (3)        NOT NULL,
    [AUDIT_CHANGE_DATE]     DATETIME        CONSTRAINT [DF_zOE_ACCOUNT_AUDIT_audit_change_dt] DEFAULT (getdate()) NOT NULL,
    [AUDIT_CHANGE_BY]       VARCHAR (30)    CONSTRAINT [DF_zOE_ACCOUNT_AUDIT_audit_change_by] DEFAULT (substring(suser_sname(),(1),(30))) NOT NULL,
    [AUDIT_CHANGE_LOCATION] VARCHAR (30)    CONSTRAINT [DF_zOE_ACCOUNT_AUDIT_audit_change_location] DEFAULT (substring(host_name(),(1),(30))) NOT NULL,
    CONSTRAINT [PK_zOE_ACCOUNT] PRIMARY KEY NONCLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_zOE_ACCOUNT_AUDIT_99_823673982__K2_K1_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20]
    ON [dbo].[zOE_ACCOUNT_AUDIT-051110]([ACCOUNT_NUMBER] ASC, [ID] ASC)
    INCLUDE([ACCOUNT_ID], [MARKET], [UTILITY], [METER_TYPE], [RATE_CLASS], [VOLTAGE], [ZONE], [VAL_COMMENT], [TCAP], [ICAP], [LOAD_SHAPE_ID], [LOSSES], [ANNUAL_USAGE], [USAGE_DATE], [AUDIT_CHANGE_TYPE], [AUDIT_CHANGE_DATE], [AUDIT_CHANGE_BY], [AUDIT_CHANGE_LOCATION]) WITH (FILLFACTOR = 90);

