CREATE TABLE [dbo].[zAudit_deal_contract] (
    [contract_nbr]            CHAR (12)      NULL,
    [contract_type]           VARCHAR (15)   NULL,
    [status]                  VARCHAR (15)   NULL,
    [retail_mkt_id]           CHAR (2)       NULL,
    [utility_id]              CHAR (15)      NULL,
    [product_id]              CHAR (20)      NULL,
    [rate_id]                 INT            NULL,
    [rate]                    FLOAT (53)     NULL,
    [customer_name_link]      INT            NULL,
    [customer_address_link]   INT            NULL,
    [customer_contact_link]   INT            NULL,
    [billing_address_link]    INT            NULL,
    [billing_contact_link]    INT            NULL,
    [owner_name_link]         INT            NULL,
    [service_address_link]    INT            NULL,
    [business_type]           VARCHAR (35)   NULL,
    [business_activity]       VARCHAR (35)   NULL,
    [additional_id_nbr_type]  VARCHAR (10)   NULL,
    [additional_id_nbr]       VARCHAR (30)   NULL,
    [contract_eff_start_date] DATETIME       NULL,
    [term_months]             INT            NULL,
    [date_end]                DATETIME       NULL,
    [date_deal]               DATETIME       NULL,
    [date_created]            DATETIME       NULL,
    [date_submit]             DATETIME       NULL,
    [sales_channel_role]      NVARCHAR (100) NULL,
    [username]                NCHAR (100)    NULL,
    [sales_rep]               VARCHAR (5)    NULL,
    [origin]                  VARCHAR (50)   NULL,
    [grace_period]            INT            NULL,
    [chgstamp]                SMALLINT       NULL,
    [audit_change_type]       CHAR (3)       NOT NULL,
    [audit_change_dt]         DATETIME       CONSTRAINT [DF_zAuditdeal_contract__audit_change_dt] DEFAULT (getdate()) NOT NULL,
    [audit_change_by]         VARCHAR (30)   CONSTRAINT [DF_zAuditdeal_contract__audit_change_by] DEFAULT (substring(suser_sname(),(1),(30))) NOT NULL,
    [audit_change_location]   VARCHAR (30)   CONSTRAINT [DF_zAuditdeal_contract__audit_change_location] DEFAULT (substring(host_name(),(1),(30))) NOT NULL
);

