CREATE TABLE [dbo].[DAM_PRICE] (
    [DELIVERY_DATE]          DATETIME     NOT NULL,
    [HOUR_ENDING]            TINYINT      NOT NULL,
    [SETTLEMENT_POINT]       VARCHAR (20) NOT NULL,
    [SETTLEMENT_POINT_PRICE] SMALLMONEY   NOT NULL,
    [CREATED]                DATETIME     CONSTRAINT [DF_DAM_PRICE_CREATED] DEFAULT (getdate()) NULL,
    [ROW_ID]                 INT          IDENTITY (1, 1) NOT NULL,
    [PROCESSED_ID]           INT          NULL,
    [CREATED_BY]             VARCHAR (50) NULL,
    [LOG_ID]                 INT          NULL,
    CONSTRAINT [PK_DAM_PRICE] PRIMARY KEY CLUSTERED ([ROW_ID] ASC),
    CONSTRAINT [FK_DAM_PRICE_LOG_DAM_PRICE_DROPPED] FOREIGN KEY ([LOG_ID]) REFERENCES [dbo].[LOG_DAM_PRICE_DROPPED] ([ROW_ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_DAM_PRICE]
    ON [dbo].[DAM_PRICE]([DELIVERY_DATE] ASC);

