CREATE TABLE [dbo].[LOG_MARKET_PROCESSED] (
    [ROW_ID]         INT           IDENTITY (1, 1) NOT NULL,
    [LOG_DROPPED_ID] INT           NOT NULL,
    [FILE_TYPE_ID]   INT           NULL,
    [FILE_NAME]      VARCHAR (100) NULL,
    [TIME_STAMP]     DATETIME      NULL,
    [SUCCESS]        BIT           CONSTRAINT [DF_LOG_MARKET_PROCESSED_SUCCESS] DEFAULT ((0)) NOT NULL,
    [ERROR_MSG]      VARCHAR (500) NULL,
    [CREATED]        DATETIME      CONSTRAINT [DF_LOG_MARKET_PROCESSED_CREATED] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_LOG_MARKET_PROCESSED] PRIMARY KEY CLUSTERED ([ROW_ID] ASC),
    CONSTRAINT [FK_LOG_MARKET_PROCESSED_LOG_MARKET_DROPPED] FOREIGN KEY ([LOG_DROPPED_ID]) REFERENCES [dbo].[LOG_MARKET_DROPPED] ([ROW_ID]),
    CONSTRAINT [FK_LOG_MARKET_PROCESSED_MARKET_FILE_TYPE] FOREIGN KEY ([FILE_TYPE_ID]) REFERENCES [dbo].[MARKET_FILE_TYPE] ([ROW_ID])
);

