CREATE TABLE [dbo].[LOG_MARKET_DROPPED] (
    [ROW_ID]      INT           IDENTITY (1, 1) NOT NULL,
    [FILE_MAP_ID] INT           NULL,
    [FILE_NAME]   VARCHAR (100) NOT NULL,
    [TIME_STAMP]  DATETIME      NULL,
    [SUCCESS]     BIT           CONSTRAINT [DF_LOG_MARKET_DROPPED_SUCCESS] DEFAULT ((0)) NOT NULL,
    [ERROR_MSG]   VARCHAR (500) NULL,
    [CREATED]     DATETIME      CONSTRAINT [DF_LOG_MARKET_DROPPED_CREATED] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_LOG_MARKET_DROPPED] PRIMARY KEY CLUSTERED ([ROW_ID] ASC),
    CONSTRAINT [FK_LOG_MARKET_DROPPED_MARKET_FILE_MAP] FOREIGN KEY ([FILE_MAP_ID]) REFERENCES [dbo].[MARKET_FILE_MAP] ([ROW_ID])
);

