CREATE TABLE [dbo].[OLE DB Destination] (
    [UIDESIID]  VARCHAR (50)  NULL,
    [ESIID]     VARCHAR (50)  NULL,
    [STARTTIME] VARCHAR (50)  NULL,
    [STOPTIME]  VARCHAR (50)  NULL,
    [ADDTIME]   VARCHAR (50)  NULL,
    [ENTITY_ID] NVARCHAR (50) NULL
);

