CREATE TABLE [dbo].[USAGE_FILE_MAP] (
    [ROW_ID]             INT           IDENTITY (1, 1) NOT NULL,
    [FILE_NAME_LOOKUP]   VARCHAR (50)  NOT NULL,
    [ENTITY_ID]          VARCHAR (15)  NOT NULL,
    [COUNT_FILE_PATTERN] VARCHAR (50)  NOT NULL,
    [FILE_HAS_DATE]      BIT           CONSTRAINT [DF_USAGE_FILE_MAP_FILE_HAS_DATE] DEFAULT ((0)) NOT NULL,
    [DATE_REGEX]         VARCHAR (100) NULL,
    [DATE_FORMAT]        VARCHAR (50)  NULL,
    [IS_SEQUENTIAL]      BIT           CONSTRAINT [DF_USAGE_FILE_MAP_IS_SEQUENTIAL] DEFAULT ((0)) NOT NULL,
    [DISABLED]           BIT           CONSTRAINT [DF_USAGE_FILE_MAP_DISABLED] DEFAULT ((0)) NOT NULL,
    [DATE_CREATED]       DATETIME      CONSTRAINT [DF_USAGE_FILE_MAP_DATE_CREATED] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY]         VARCHAR (50)  NULL,
    CONSTRAINT [PK_USAGE_FILE_MAP] PRIMARY KEY CLUSTERED ([ROW_ID] ASC)
);

