//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsageWebService.Entities
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ServiceAccount", Namespace = "http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    public partial class ServiceAccount : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AccountNumberField;

        private string UtilityCodeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UtilityCode
        {
            get
            {
                return this.UtilityCodeField;
            }
            set
            {
                this.UtilityCodeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EdiUsageRequest", Namespace = "http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    public partial class EdiUsageRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AccountNumberField;

        private string BillingAccountNumberField;

        private string DunsNumberField;

        private string MeterNumberField;

        private string NameKeyField;

        private string StrataField;

        private string UsageTypeField;

        private string UtilityCodeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingAccountNumber
        {
            get
            {
                return this.BillingAccountNumberField;
            }
            set
            {
                this.BillingAccountNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DunsNumber
        {
            get
            {
                return this.DunsNumberField;
            }
            set
            {
                this.DunsNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterNumber
        {
            get
            {
                return this.MeterNumberField;
            }
            set
            {
                this.MeterNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameKey
        {
            get
            {
                return this.NameKeyField;
            }
            set
            {
                this.NameKeyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Strata
        {
            get
            {
                return this.StrataField;
            }
            set
            {
                this.StrataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsageType
        {
            get
            {
                return this.UsageTypeField;
            }
            set
            {
                this.UsageTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UtilityCode
        {
            get
            {
                return this.UtilityCodeField;
            }
            set
            {
                this.UtilityCodeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ScraperUsageRequest", Namespace = "http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    public partial class ScraperUsageRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AccountNumberField;

        private string UtilityCodeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UtilityCode
        {
            get
            {
                return this.UtilityCodeField;
            }
            set
            {
                this.UtilityCodeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AnnualUsageRequest", Namespace = "http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    public partial class AnnualUsageRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AccountNumberField;

        private int UtilityIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UtilityId
        {
            get
            {
                return this.UtilityIdField;
            }
            set
            {
                this.UtilityIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "IsIdrEligibleRequest", Namespace = "http://schemas.datacontract.org/2004/07/UsageWebService.Entities")]
    public partial class IsIdrEligibleRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AccountNumberField;

        private int UtilityIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UtilityId
        {
            get
            {
                return this.UtilityIdField;
            }
            set
            {
                this.UtilityIdField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IUsage")]
public interface IUsage
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUsage/GetUsageDate", ReplyAction = "http://tempuri.org/IUsage/GetUsageDateResponse")]
    System.DateTime GetUsageDate(UsageWebService.Entities.ServiceAccount serviceAccount);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUsage/SubmitHistoricalUsageRequest", ReplyAction = "http://tempuri.org/IUsage/SubmitHistoricalUsageRequestResponse")]
    string SubmitHistoricalUsageRequest(UsageWebService.Entities.EdiUsageRequest ediUsageRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUsage/RunScraper", ReplyAction = "http://tempuri.org/IUsage/RunScraperResponse")]
    string RunScraper(UsageWebService.Entities.ScraperUsageRequest scraperUsageRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUsage/GetAnnualUsage", ReplyAction = "http://tempuri.org/IUsage/GetAnnualUsageResponse")]
    int GetAnnualUsage(UsageWebService.Entities.AnnualUsageRequest annualUsageRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUsage/IsIdrEligible", ReplyAction = "http://tempuri.org/IUsage/IsIdrEligibleResponse")]
    bool IsIdrEligible(UsageWebService.Entities.IsIdrEligibleRequest isIdrEligibleRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUsage/IsServiceRunning", ReplyAction = "http://tempuri.org/IUsage/IsServiceRunningResponse")]
    bool IsServiceRunning();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUsageChannel : IUsage, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UsageClient : System.ServiceModel.ClientBase<IUsage>, IUsage
{

    public UsageClient()
    {
    }

    public UsageClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public UsageClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public UsageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public UsageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public System.DateTime GetUsageDate(UsageWebService.Entities.ServiceAccount serviceAccount)
    {
        return base.Channel.GetUsageDate(serviceAccount);
    }

    public string SubmitHistoricalUsageRequest(UsageWebService.Entities.EdiUsageRequest ediUsageRequest)
    {
        return base.Channel.SubmitHistoricalUsageRequest(ediUsageRequest);
    }

    public string RunScraper(UsageWebService.Entities.ScraperUsageRequest scraperUsageRequest)
    {
        return base.Channel.RunScraper(scraperUsageRequest);
    }

    public int GetAnnualUsage(UsageWebService.Entities.AnnualUsageRequest annualUsageRequest)
    {
        return base.Channel.GetAnnualUsage(annualUsageRequest);
    }

    public bool IsIdrEligible(UsageWebService.Entities.IsIdrEligibleRequest isIdrEligibleRequest)
    {
        return base.Channel.IsIdrEligible(isIdrEligibleRequest);
    }

    public bool IsServiceRunning()
    {
        return base.Channel.IsServiceRunning();
    }
}
