CREATE TABLE [dbo].[AD_DATA_SET_TIMING] (
    [ID]           INT           NOT NULL,
    [DATA_SET]     NVARCHAR (50) NOT NULL,
    [TIMING]       INT           CONSTRAINT [DF__AD_DATA_S__TIMIN__6CD828CA] DEFAULT ((12)) NOT NULL,
    [LAST_ARCHIVE] DATETIME      NULL,
    CONSTRAINT [PK_AD_DATA_SET_TIMING] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

