CREATE TABLE [dbo].[AD_SYSTEM_PARAMETER] (
    [ID]       INT             NOT NULL,
    [ITEM]     VARCHAR (50)    NOT NULL,
    [VALUE]    NUMERIC (10, 5) NOT NULL,
    [GROUP_ID] INT             NOT NULL,
    CONSTRAINT [PK_AD_SYSTEM_PARAMETER_1] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

