CREATE TABLE [dbo].[OE_CONTRACTED_OFFERS] (
    [OFFER_ID]                VARCHAR (50) NOT NULL,
    [REQUEST_ID]              VARCHAR (50) NOT NULL,
    [MARKET_PRICES_DETAIL_ID] INT          NOT NULL,
    [SENT_TO_DEAL_CAPTURE]    INT          CONSTRAINT [DF__OE_CONTRA__SENT___5F7E2DAC] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [OE_CONTRACTED_OFFERS_pk] PRIMARY KEY CLUSTERED ([OFFER_ID] ASC) WITH (FILLFACTOR = 90)
);

