CREATE TABLE [dbo].[OE_OFFER_FLOW_DATES] (
    [ID]                 INT           IDENTITY (1, 1) NOT NULL,
    [FLOW_START_DATE_ID] NVARCHAR (50) DEFAULT (CONVERT([nvarchar](50),newid(),0)) NULL,
    [OFFER_ID]           NVARCHAR (50) NOT NULL,
    [FLOW_START_DATE]    DATETIME      NULL,
    CONSTRAINT [PK_OE_OFFER_FLOW_DATES_AND_TERMS] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_OE_OFFER_FLOW_DATES_99_1182627256__K3_1_2_4]
    ON [dbo].[OE_OFFER_FLOW_DATES]([OFFER_ID] ASC)
    INCLUDE([ID], [FLOW_START_DATE_ID], [FLOW_START_DATE]) WITH (FILLFACTOR = 90);

