CREATE TABLE [dbo].[OE_OFFER_AGGREGATES] (
    [OFFER_ID] VARCHAR (50)    NOT NULL,
    [UTILITY]  VARCHAR (50)    NOT NULL,
    [ZONE]     VARCHAR (50)    NOT NULL,
    [ICAP]     DECIMAL (18, 9) NOT NULL,
    [TCAP]     DECIMAL (18, 9) NOT NULL,
    [LOSSES]   DECIMAL (18, 9) NOT NULL,
    [ACCEPT]   TINYINT         CONSTRAINT [DF_OE_OFFER_AGGREGATES_ACCEPT] DEFAULT ((1)) NOT NULL
);


GO
CREATE CLUSTERED INDEX [_dta_index_OE_OFFER_AGGREGATES_c_99_971150505__K1_K2_K3]
    ON [dbo].[OE_OFFER_AGGREGATES]([OFFER_ID] ASC, [UTILITY] ASC, [ZONE] ASC) WITH (FILLFACTOR = 90);

