CREATE TABLE [dbo].[OE_TERMS_AND_PRICES] (
    [ID]                  INT             IDENTITY (1, 1) NOT NULL,
    [TERMS_AND_PRICES_ID] VARCHAR (50)    NULL,
    [FLOW_START_DATE_ID]  VARCHAR (50)    NULL,
    [TERM]                INT             NULL,
    [PRICE]               DECIMAL (16, 2) NULL,
    CONSTRAINT [PK_OE_TERM_AND_PRICE] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [idx_flow_start_date_id]
    ON [dbo].[OE_TERMS_AND_PRICES]([FLOW_START_DATE_ID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = OFF);

