CREATE TABLE [dbo].[zPROCESS_TRACKING] (
    [ID]             BIGINT        IDENTITY (1, 1) NOT NULL,
    [REQUEST_ID]     VARCHAR (50)  NULL,
    [OFFER_ID]       VARCHAR (50)  NULL,
    [STATUS]         VARCHAR (50)  NULL,
    [ACCOUNT_NUMBER] VARCHAR (50)  NULL,
    [PROCESS]        VARCHAR (100) NULL,
    [PROCESS_STAGE]  VARCHAR (50)  NULL,
    [DATE_INSERT]    DATETIME      CONSTRAINT [DF_zPROCESS_TRACKING_DATE_INSERT2] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_zPROCESS_TRACKING2] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

