//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibertyPower.Business.CustomerManagement.AccountManagement.RateServiceWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerRate", Namespace="http://schemas.datacontract.org/2004/07/RateService")]
    [System.SerializableAttribute()]
    public partial class CustomerRate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LibertyPower.Business.CustomerManagement.AccountManagement.RateServiceWCF.BillingType BillingTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CreditInsuranceFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MeterChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LibertyPower.Business.CustomerManagement.AccountManagement.RateServiceWCF.ProductPlanType ProductTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Rate1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Rate2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Rate3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RateCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RateEffectiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RateEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UtilityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VariableTypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibertyPower.Business.CustomerManagement.AccountManagement.RateServiceWCF.BillingType BillingType {
            get {
                return this.BillingTypeField;
            }
            set {
                if ((this.BillingTypeField.Equals(value) != true)) {
                    this.BillingTypeField = value;
                    this.RaisePropertyChanged("BillingType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CreditInsuranceFlag {
            get {
                return this.CreditInsuranceFlagField;
            }
            set {
                if ((this.CreditInsuranceFlagField.Equals(value) != true)) {
                    this.CreditInsuranceFlagField = value;
                    this.RaisePropertyChanged("CreditInsuranceFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MeterCharge {
            get {
                return this.MeterChargeField;
            }
            set {
                if ((this.MeterChargeField.Equals(value) != true)) {
                    this.MeterChargeField = value;
                    this.RaisePropertyChanged("MeterCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibertyPower.Business.CustomerManagement.AccountManagement.RateServiceWCF.ProductPlanType ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((this.ProductTypeField.Equals(value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rate1 {
            get {
                return this.Rate1Field;
            }
            set {
                if ((this.Rate1Field.Equals(value) != true)) {
                    this.Rate1Field = value;
                    this.RaisePropertyChanged("Rate1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rate2 {
            get {
                return this.Rate2Field;
            }
            set {
                if ((this.Rate2Field.Equals(value) != true)) {
                    this.Rate2Field = value;
                    this.RaisePropertyChanged("Rate2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rate3 {
            get {
                return this.Rate3Field;
            }
            set {
                if ((this.Rate3Field.Equals(value) != true)) {
                    this.Rate3Field = value;
                    this.RaisePropertyChanged("Rate3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RateCode {
            get {
                return this.RateCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RateCodeField, value) != true)) {
                    this.RateCodeField = value;
                    this.RaisePropertyChanged("RateCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RateEffectiveDate {
            get {
                return this.RateEffectiveDateField;
            }
            set {
                if ((this.RateEffectiveDateField.Equals(value) != true)) {
                    this.RateEffectiveDateField = value;
                    this.RaisePropertyChanged("RateEffectiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RateEndDate {
            get {
                return this.RateEndDateField;
            }
            set {
                if ((this.RateEndDateField.Equals(value) != true)) {
                    this.RateEndDateField = value;
                    this.RaisePropertyChanged("RateEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UtilityCode {
            get {
                return this.UtilityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UtilityCodeField, value) != true)) {
                    this.UtilityCodeField = value;
                    this.RaisePropertyChanged("UtilityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VariableTypeID {
            get {
                return this.VariableTypeIDField;
            }
            set {
                if ((this.VariableTypeIDField.Equals(value) != true)) {
                    this.VariableTypeIDField = value;
                    this.RaisePropertyChanged("VariableTypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillingType", Namespace="http://schemas.datacontract.org/2004/07/RateService")]
    public enum BillingType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dual = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RateReady = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BillReady = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SupplierConsolidated = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductPlanType", Namespace="http://schemas.datacontract.org/2004/07/RateService")]
    public enum ProductPlanType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fixed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PortfolioVarialble = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CustomVariable = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HeatRate = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IndexTexas = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BlockIndexed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hybrid = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Index = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ruc = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CustomIndex = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RateServiceWCF.IRateService")]
    public interface IRateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateService/UpdateCustomerRate", ReplyAction="http://tempuri.org/IRateService/UpdateCustomerRateResponse")]
        void UpdateCustomerRate(LibertyPower.Business.CustomerManagement.AccountManagement.RateServiceWCF.CustomerRate customerRate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRateServiceChannel : LibertyPower.Business.CustomerManagement.AccountManagement.RateServiceWCF.IRateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RateServiceClient : System.ServiceModel.ClientBase<LibertyPower.Business.CustomerManagement.AccountManagement.RateServiceWCF.IRateService>, LibertyPower.Business.CustomerManagement.AccountManagement.RateServiceWCF.IRateService {
        
        public RateServiceClient() {
        }
        
        public RateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateCustomerRate(LibertyPower.Business.CustomerManagement.AccountManagement.RateServiceWCF.CustomerRate customerRate) {
            base.Channel.UpdateCustomerRate(customerRate);
        }
    }
}
