CREATE TABLE [dbo].[UtilityLegacy] (
    [ID]                      INT           IDENTITY (1, 1) NOT NULL,
    [UtilityCode]             VARCHAR (50)  NOT NULL,
    [FullName]                VARCHAR (100) NOT NULL,
    [ShortName]               VARCHAR (50)  NOT NULL,
    [MarketID]                INT           NOT NULL,
    [DunsNumber]              VARCHAR (30)  NULL,
    [EntityId]                VARCHAR (15)  NULL,
    [EnrollmentLeadDays]      INT           NULL,
    [BillingType]             VARCHAR (15)  NULL,
    [AccountLength]           INT           NULL,
    [AccountNumberPrefix]     VARCHAR (10)  NULL,
    [LeadScreenProcess]       VARCHAR (15)  NULL,
    [DealScreenProcess]       VARCHAR (15)  NULL,
    [PorOption]               VARCHAR (3)   NULL,
    [Field01Label]            VARCHAR (20)  NULL,
    [Field01Type]             VARCHAR (30)  NULL,
    [Field02Label]            VARCHAR (20)  NULL,
    [Field02Type]             VARCHAR (30)  NULL,
    [Field03Label]            VARCHAR (20)  NULL,
    [Field03Type]             VARCHAR (30)  NULL,
    [Field04Label]            VARCHAR (20)  NULL,
    [Field04Type]             VARCHAR (30)  NULL,
    [Field05Label]            VARCHAR (20)  NULL,
    [Field05Type]             VARCHAR (30)  NULL,
    [Field06Label]            VARCHAR (20)  NULL,
    [Field06Type]             VARCHAR (30)  NULL,
    [Field07Label]            VARCHAR (20)  NULL,
    [Field07Type]             VARCHAR (30)  NULL,
    [Field08Label]            VARCHAR (20)  NULL,
    [Field08Type]             VARCHAR (30)  NULL,
    [Field09Label]            VARCHAR (20)  NULL,
    [Field09Type]             VARCHAR (30)  NULL,
    [Field10Label]            VARCHAR (20)  NULL,
    [Field10Type]             VARCHAR (30)  NULL,
    [DateCreated]             DATETIME      NULL,
    [UserName]                NCHAR (200)   NULL,
    [InactiveInd]             CHAR (1)      NULL,
    [ActiveDate]              DATETIME      NULL,
    [ChgStamp]                SMALLINT      NULL,
    [MeterNumberRequired]     SMALLINT      NULL,
    [MeterNumberLength]       SMALLINT      NULL,
    [AnnualUsageMin]          INT           NULL,
    [Qualifier]               VARCHAR (50)  NULL,
    [EdiCapable]              SMALLINT      NULL,
    [WholeSaleMktID]          VARCHAR (50)  NULL,
    [Phone]                   VARCHAR (30)  NULL,
    [RateCodeRequired]        TINYINT       NULL,
    [HasZones]                TINYINT       NULL,
    [ZoneDefault]             INT           NULL,
    [Field11Label]            VARCHAR (20)  NULL,
    [Field11Type]             VARCHAR (30)  NULL,
    [Field12Label]            VARCHAR (20)  NULL,
    [Field12Type]             VARCHAR (30)  NULL,
    [Field13Label]            VARCHAR (20)  NULL,
    [Field13Type]             VARCHAR (30)  NULL,
    [Field14Label]            VARCHAR (20)  NULL,
    [Field14Type]             VARCHAR (30)  NULL,
    [Field15Label]            VARCHAR (20)  NULL,
    [Field15Type]             VARCHAR (30)  NULL,
    [RateCodeFormat]          VARCHAR (20)  CONSTRAINT [DF_Utility_RateCodeFormat] DEFAULT ((0)) NOT NULL,
    [RateCodeFields]          VARCHAR (50)  CONSTRAINT [DF_Utility_RateCodeFields] DEFAULT ((0)) NOT NULL,
    [LegacyName]              VARCHAR (100) NOT NULL,
    [SSNIsRequired]           BIT           NULL,
    [PricingModeID]           INT           CONSTRAINT [DF_Utility_PricingModeID] DEFAULT ((1)) NULL,
    [isIDR_EDI_Capable]       BIT           NULL,
    [HU_RequestType]          NCHAR (10)    NULL,
    [MultipleMeters]          BIT           NULL,
    [MeterReadOverlap]        BIT           NULL,
    [AutoApproval]            BIT           NULL,
    [DeliveryLocationRefID]   INT           NULL,
    [DefaultProfileRefID]     INT           NULL,
    [SettlementLocationRefID] INT           NULL,
    CONSTRAINT [PK_EftUtility] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

