CREATE TABLE [dbo].[zAuditPurchaseOfReceivables] (
    [IdPrimary]                         UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [Id]                                UNIQUEIDENTIFIER NOT NULL,
    [UtilityCompanyId]                  UNIQUEIDENTIFIER NOT NULL,
    [PorDriverId]                       UNIQUEIDENTIFIER NOT NULL,
    [RateClassId]                       UNIQUEIDENTIFIER NULL,
    [LoadProfileId]                     UNIQUEIDENTIFIER NULL,
    [TariffCodeId]                      UNIQUEIDENTIFIER NULL,
    [IsPorOffered]                      BIT              NOT NULL,
    [IsPorParticipated]                 BIT              NOT NULL,
    [PorRecourseId]                     UNIQUEIDENTIFIER NOT NULL,
    [IsPorAssurance]                    BIT              NOT NULL,
    [PorDiscountRate]                   DECIMAL (18)     NOT NULL,
    [PorFlatFee]                        DECIMAL (18)     NOT NULL,
    [PorDiscountEffectiveDate]          DATETIME         NOT NULL,
    [PorDiscountExpirationDate]         DATETIME         NULL,
    [Inactive]                          BIT              NOT NULL,
    [CreatedBy]                         NVARCHAR (100)   NOT NULL,
    [CreatedDate]                       DATETIME         NOT NULL,
    [LastModifiedBy]                    NVARCHAR (100)   NOT NULL,
    [LastModifiedDate]                  DATETIME         NOT NULL,
    [IdPrevious]                        UNIQUEIDENTIFIER NULL,
    [UtilityCompanyIdPrevious]          UNIQUEIDENTIFIER NULL,
    [PorDriverIdPrevious]               UNIQUEIDENTIFIER NULL,
    [RateClassIdPrevious]               UNIQUEIDENTIFIER NULL,
    [LoadProfileIdPrevious]             UNIQUEIDENTIFIER NULL,
    [TariffCodeIdPrevious]              UNIQUEIDENTIFIER NULL,
    [IsPorOfferedPrevious]              BIT              NULL,
    [IsPorParticipatedPrevious]         BIT              NULL,
    [PorRecourseIdPrevious]             UNIQUEIDENTIFIER NULL,
    [IsPorAssurancePrevious]            BIT              NULL,
    [PorDiscountRatePrevious]           DECIMAL (18)     NULL,
    [PorFlatFeePrevious]                DECIMAL (18)     NULL,
    [PorDiscountEffectiveDatePrevious]  DATETIME         NULL,
    [PorDiscountExpirationDatePrevious] DATETIME         NULL,
    [InactivePrevious]                  BIT              NULL,
    [CreatedByPrevious]                 NVARCHAR (100)   NULL,
    [CreatedDatePrevious]               DATETIME         NULL,
    [LastModifiedByPrevious]            NVARCHAR (100)   NULL,
    [LastModifiedDatePrevious]          DATETIME         NULL,
    [SYS_CHANGE_VERSION]                BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION]       BIGINT           NULL,
    [SYS_CHANGE_OPERATION]              NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]                NVARCHAR (1000)  NULL,
    CONSTRAINT [PK_zAuditPurchaseOfReceivables] PRIMARY KEY CLUSTERED ([IdPrimary] ASC)
);

