CREATE TABLE [dbo].[zAuditTariffCodeAlias] (
    [IdPrimary]                   UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [Id]                          UNIQUEIDENTIFIER NOT NULL,
    [TariffCodeId]                UNIQUEIDENTIFIER NOT NULL,
    [TariffCodeCodeAlias]         NVARCHAR (255)   NOT NULL,
    [Inactive]                    BIT              NOT NULL,
    [CreatedBy]                   NVARCHAR (100)   NOT NULL,
    [CreatedDate]                 DATETIME         NOT NULL,
    [LastModifiedBy]              NVARCHAR (100)   NOT NULL,
    [LastModifiedDate]            DATETIME         NOT NULL,
    [IdPrevious]                  UNIQUEIDENTIFIER NULL,
    [TariffCodeIdPrevious]        UNIQUEIDENTIFIER NULL,
    [TariffCodeCodeAliasPrevious] NVARCHAR (255)   NULL,
    [InactivePrevious]            BIT              NULL,
    [CreatedByPrevious]           NVARCHAR (100)   NULL,
    [CreatedDatePrevious]         DATETIME         NULL,
    [LastModifiedByPrevious]      NVARCHAR (100)   NULL,
    [LastModifiedDatePrevious]    DATETIME         NULL,
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          NVARCHAR (1000)  NULL,
    CONSTRAINT [PK_zAuditTariffCodeAlias] PRIMARY KEY CLUSTERED ([IdPrimary] ASC)
);

