CREATE PROC [dbo].[USP_LOG_DAM_PRICE_DROPPED_UPD]
	@P_ROW_ID INT,
	@P_DATE_STAMP DATETIME,
	@P_ROW_COUNT INT,
	@P_SUCCESS int,
	@P_ERROR_MSG VARCHAR(1000)
AS
	SET NOCOUNT ON;

	-- 12/30/1899 is the date set in script when the package fails processing
	IF @P_DATE_STAMP IS NOT NULL
		IF @P_DATE_STAMP = CAST('12/30/1899 12:00:00 AM' AS DATETIME)
			SET @P_DATE_STAMP = NULL;

	IF @P_ERROR_MSG IS NOT NULL
		IF LEN(@P_ERROR_MSG) = 0
			SET @P_ERROR_MSG = NULL;

	UPDATE LOG_DAM_PRICE_DROPPED 
	SET DATE_STAMP = @P_DATE_STAMP, ROW_COUNT = @P_ROW_COUNT, SUCCESS = convert(bit, @P_SUCCESS), ERROR_MSG = @P_ERROR_MSG
	WHERE ROW_ID = @P_ROW_ID;

