//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace LibertyPower.DataAccess.WebServiceAccess.IstaWebService.IstaEnrollmentService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EnrollmentServiceSoap", Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public partial class EnrollmentService : Microsoft.Web.Services2.WebServicesClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateEnrollmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessEnrollmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitReEnrollmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateHistoricalUsageRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreatePreEnrollmentHistoricalUsageRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EnrollmentService() {
            this.Url = global::LibertyPower.DataAccess.WebServiceAccess.IstaWebService.Properties.Settings.Default.IstaWebService_IstaEnrollmentService_EnrollmentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateEnrollmentCompletedEventHandler CreateEnrollmentCompleted;
        
        /// <remarks/>
        public event ProcessEnrollmentCompletedEventHandler ProcessEnrollmentCompleted;
        
        /// <remarks/>
        public event SubmitReEnrollmentCompletedEventHandler SubmitReEnrollmentCompleted;
        
        /// <remarks/>
        public event CreateHistoricalUsageRequestCompletedEventHandler CreateHistoricalUsageRequestCompleted;
        
        /// <remarks/>
        public event CreatePreEnrollmentHistoricalUsageRequestCompletedEventHandler CreatePreEnrollmentHistoricalUsageRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.libertypowerbilling.com/EnrollmentService/CreateEnrollment", RequestNamespace="https://ws.libertypowerbilling.com/EnrollmentService", ResponseNamespace="https://ws.libertypowerbilling.com/EnrollmentService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateEnrollment([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] EnrollCustomer EnrollCustomer) {
            object[] results = this.Invoke("CreateEnrollment", new object[] {
                        EnrollCustomer});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateEnrollmentAsync(EnrollCustomer EnrollCustomer) {
            this.CreateEnrollmentAsync(EnrollCustomer, null);
        }
        
        /// <remarks/>
        public void CreateEnrollmentAsync(EnrollCustomer EnrollCustomer, object userState) {
            if ((this.CreateEnrollmentOperationCompleted == null)) {
                this.CreateEnrollmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateEnrollmentOperationCompleted);
            }
            this.InvokeAsync("CreateEnrollment", new object[] {
                        EnrollCustomer}, this.CreateEnrollmentOperationCompleted, userState);
        }
        
        private void OnCreateEnrollmentOperationCompleted(object arg) {
            if ((this.CreateEnrollmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateEnrollmentCompleted(this, new CreateEnrollmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.libertypowerbilling.com/EnrollmentService/ProcessEnrollment", RequestNamespace="https://ws.libertypowerbilling.com/EnrollmentService", ResponseNamespace="https://ws.libertypowerbilling.com/EnrollmentService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ProcessEnrollment(int enrollCustId) {
            object[] results = this.Invoke("ProcessEnrollment", new object[] {
                        enrollCustId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessEnrollmentAsync(int enrollCustId) {
            this.ProcessEnrollmentAsync(enrollCustId, null);
        }
        
        /// <remarks/>
        public void ProcessEnrollmentAsync(int enrollCustId, object userState) {
            if ((this.ProcessEnrollmentOperationCompleted == null)) {
                this.ProcessEnrollmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessEnrollmentOperationCompleted);
            }
            this.InvokeAsync("ProcessEnrollment", new object[] {
                        enrollCustId}, this.ProcessEnrollmentOperationCompleted, userState);
        }
        
        private void OnProcessEnrollmentOperationCompleted(object arg) {
            if ((this.ProcessEnrollmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessEnrollmentCompleted(this, new ProcessEnrollmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.libertypowerbilling.com/EnrollmentService/SubmitReEnrollment", RequestNamespace="https://ws.libertypowerbilling.com/EnrollmentService", ResponseNamespace="https://ws.libertypowerbilling.com/EnrollmentService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SubmitReEnrollment([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ReEnrollment ReEnrollment) {
            this.Invoke("SubmitReEnrollment", new object[] {
                        ReEnrollment});
        }
        
        /// <remarks/>
        public void SubmitReEnrollmentAsync(ReEnrollment ReEnrollment) {
            this.SubmitReEnrollmentAsync(ReEnrollment, null);
        }
        
        /// <remarks/>
        public void SubmitReEnrollmentAsync(ReEnrollment ReEnrollment, object userState) {
            if ((this.SubmitReEnrollmentOperationCompleted == null)) {
                this.SubmitReEnrollmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitReEnrollmentOperationCompleted);
            }
            this.InvokeAsync("SubmitReEnrollment", new object[] {
                        ReEnrollment}, this.SubmitReEnrollmentOperationCompleted, userState);
        }
        
        private void OnSubmitReEnrollmentOperationCompleted(object arg) {
            if ((this.SubmitReEnrollmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitReEnrollmentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.libertypowerbilling.com/EnrollmentService/CreateHistoricalUsageRequest" +
            "", RequestNamespace="https://ws.libertypowerbilling.com/EnrollmentService", ResponseNamespace="https://ws.libertypowerbilling.com/EnrollmentService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateHistoricalUsageRequest(int enrollCustId, string historicalUsageType) {
            this.Invoke("CreateHistoricalUsageRequest", new object[] {
                        enrollCustId,
                        historicalUsageType});
        }
        
        /// <remarks/>
        public void CreateHistoricalUsageRequestAsync(int enrollCustId, string historicalUsageType) {
            this.CreateHistoricalUsageRequestAsync(enrollCustId, historicalUsageType, null);
        }
        
        /// <remarks/>
        public void CreateHistoricalUsageRequestAsync(int enrollCustId, string historicalUsageType, object userState) {
            if ((this.CreateHistoricalUsageRequestOperationCompleted == null)) {
                this.CreateHistoricalUsageRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateHistoricalUsageRequestOperationCompleted);
            }
            this.InvokeAsync("CreateHistoricalUsageRequest", new object[] {
                        enrollCustId,
                        historicalUsageType}, this.CreateHistoricalUsageRequestOperationCompleted, userState);
        }
        
        private void OnCreateHistoricalUsageRequestOperationCompleted(object arg) {
            if ((this.CreateHistoricalUsageRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateHistoricalUsageRequestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.libertypowerbilling.com/EnrollmentService/CreatePreEnrollmentHistorica" +
            "lUsageRequest", RequestNamespace="https://ws.libertypowerbilling.com/EnrollmentService", ResponseNamespace="https://ws.libertypowerbilling.com/EnrollmentService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreatePreEnrollmentHistoricalUsageRequest([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] PreEnrollmentHURequest PreEnrollmentHURequest) {
            this.Invoke("CreatePreEnrollmentHistoricalUsageRequest", new object[] {
                        PreEnrollmentHURequest});
        }
        
        /// <remarks/>
        public void CreatePreEnrollmentHistoricalUsageRequestAsync(PreEnrollmentHURequest PreEnrollmentHURequest) {
            this.CreatePreEnrollmentHistoricalUsageRequestAsync(PreEnrollmentHURequest, null);
        }
        
        /// <remarks/>
        public void CreatePreEnrollmentHistoricalUsageRequestAsync(PreEnrollmentHURequest PreEnrollmentHURequest, object userState) {
            if ((this.CreatePreEnrollmentHistoricalUsageRequestOperationCompleted == null)) {
                this.CreatePreEnrollmentHistoricalUsageRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePreEnrollmentHistoricalUsageRequestOperationCompleted);
            }
            this.InvokeAsync("CreatePreEnrollmentHistoricalUsageRequest", new object[] {
                        PreEnrollmentHURequest}, this.CreatePreEnrollmentHistoricalUsageRequestOperationCompleted, userState);
        }
        
        private void OnCreatePreEnrollmentHistoricalUsageRequestOperationCompleted(object arg) {
            if ((this.CreatePreEnrollmentHistoricalUsageRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreatePreEnrollmentHistoricalUsageRequestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public partial class EnrollCustomer {
        
        private LibertyCustomerTypeOptions customerTypeField;
        
        private string customerNameField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string salutationField;
        
        private string dBAField;
        
        private string federalTaxIdField;
        
        private string billingContactField;
        
        private string billingAddress1Field;
        
        private string billingAddress2Field;
        
        private string billingCityField;
        
        private string billingStateField;
        
        private string billingZipField;
        
        private string billingPhoneField;
        
        private string billingEmailField;
        
        private bool isTaxableField;
        
        private bool isLifeSupportField;
        
        private bool isSpanishBillField;
        
        private string digitalSignatureField;
        
        private string commentsField;
        
        private bool notificationWaiverField;
        
        private BillingTypeOptions billingTypeField;
        
        private string customerAccountNumberField;
        
        private string customerGroupField;
        
        private bool disableTransactionsField;
        
        private PrintLayoutOptions printLayoutField;
        
        private bool applyLateFeesField;
        
        private System.Nullable<int> billingCustomerIDField;
        
        private System.Nullable<int> masterCustomerIDField;
        
        private System.Nullable<decimal> lateFeeRateField;
        
        private System.Nullable<decimal> lateFeeMaxAmountField;
        
        private System.Nullable<int> aRTermsField;
        
        private System.Nullable<int> lateFeeGracePeriodField;
        
        private string tDSPDunsField;
        
        private string eSPDunsField;
        
        private bool submitHURequestField;
        
        private System.DateTime contractStartDateField;
        
        private System.DateTime contractEndDateField;
        
        private EnrollRate enrollRateField;
        
        private EnrollDefaultRate enrollDefaultRateField;
        
        private EnrollPremise enrollPremiseField;
        
        private string historicalUsageTypeField;
        
        private bool pORFlagField;
        
        private bool creditInsuranceFlagField;
        
        /// <remarks/>
        public LibertyCustomerTypeOptions CustomerType {
            get {
                return this.customerTypeField;
            }
            set {
                this.customerTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string Salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        public string DBA {
            get {
                return this.dBAField;
            }
            set {
                this.dBAField = value;
            }
        }
        
        /// <remarks/>
        public string FederalTaxId {
            get {
                return this.federalTaxIdField;
            }
            set {
                this.federalTaxIdField = value;
            }
        }
        
        /// <remarks/>
        public string BillingContact {
            get {
                return this.billingContactField;
            }
            set {
                this.billingContactField = value;
            }
        }
        
        /// <remarks/>
        public string BillingAddress1 {
            get {
                return this.billingAddress1Field;
            }
            set {
                this.billingAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string BillingAddress2 {
            get {
                return this.billingAddress2Field;
            }
            set {
                this.billingAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string BillingCity {
            get {
                return this.billingCityField;
            }
            set {
                this.billingCityField = value;
            }
        }
        
        /// <remarks/>
        public string BillingState {
            get {
                return this.billingStateField;
            }
            set {
                this.billingStateField = value;
            }
        }
        
        /// <remarks/>
        public string BillingZip {
            get {
                return this.billingZipField;
            }
            set {
                this.billingZipField = value;
            }
        }
        
        /// <remarks/>
        public string BillingPhone {
            get {
                return this.billingPhoneField;
            }
            set {
                this.billingPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string BillingEmail {
            get {
                return this.billingEmailField;
            }
            set {
                this.billingEmailField = value;
            }
        }
        
        /// <remarks/>
        public bool IsTaxable {
            get {
                return this.isTaxableField;
            }
            set {
                this.isTaxableField = value;
            }
        }
        
        /// <remarks/>
        public bool IsLifeSupport {
            get {
                return this.isLifeSupportField;
            }
            set {
                this.isLifeSupportField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSpanishBill {
            get {
                return this.isSpanishBillField;
            }
            set {
                this.isSpanishBillField = value;
            }
        }
        
        /// <remarks/>
        public string DigitalSignature {
            get {
                return this.digitalSignatureField;
            }
            set {
                this.digitalSignatureField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public bool NotificationWaiver {
            get {
                return this.notificationWaiverField;
            }
            set {
                this.notificationWaiverField = value;
            }
        }
        
        /// <remarks/>
        public BillingTypeOptions BillingType {
            get {
                return this.billingTypeField;
            }
            set {
                this.billingTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerAccountNumber {
            get {
                return this.customerAccountNumberField;
            }
            set {
                this.customerAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerGroup {
            get {
                return this.customerGroupField;
            }
            set {
                this.customerGroupField = value;
            }
        }
        
        /// <remarks/>
        public bool DisableTransactions {
            get {
                return this.disableTransactionsField;
            }
            set {
                this.disableTransactionsField = value;
            }
        }
        
        /// <remarks/>
        public PrintLayoutOptions PrintLayout {
            get {
                return this.printLayoutField;
            }
            set {
                this.printLayoutField = value;
            }
        }
        
        /// <remarks/>
        public bool ApplyLateFees {
            get {
                return this.applyLateFeesField;
            }
            set {
                this.applyLateFeesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BillingCustomerID {
            get {
                return this.billingCustomerIDField;
            }
            set {
                this.billingCustomerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MasterCustomerID {
            get {
                return this.masterCustomerIDField;
            }
            set {
                this.masterCustomerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> LateFeeRate {
            get {
                return this.lateFeeRateField;
            }
            set {
                this.lateFeeRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> LateFeeMaxAmount {
            get {
                return this.lateFeeMaxAmountField;
            }
            set {
                this.lateFeeMaxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ARTerms {
            get {
                return this.aRTermsField;
            }
            set {
                this.aRTermsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LateFeeGracePeriod {
            get {
                return this.lateFeeGracePeriodField;
            }
            set {
                this.lateFeeGracePeriodField = value;
            }
        }
        
        /// <remarks/>
        public string TDSPDuns {
            get {
                return this.tDSPDunsField;
            }
            set {
                this.tDSPDunsField = value;
            }
        }
        
        /// <remarks/>
        public string ESPDuns {
            get {
                return this.eSPDunsField;
            }
            set {
                this.eSPDunsField = value;
            }
        }
        
        /// <remarks/>
        public bool SubmitHURequest {
            get {
                return this.submitHURequestField;
            }
            set {
                this.submitHURequestField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ContractStartDate {
            get {
                return this.contractStartDateField;
            }
            set {
                this.contractStartDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ContractEndDate {
            get {
                return this.contractEndDateField;
            }
            set {
                this.contractEndDateField = value;
            }
        }
        
        /// <remarks/>
        public EnrollRate EnrollRate {
            get {
                return this.enrollRateField;
            }
            set {
                this.enrollRateField = value;
            }
        }
        
        /// <remarks/>
        public EnrollDefaultRate EnrollDefaultRate {
            get {
                return this.enrollDefaultRateField;
            }
            set {
                this.enrollDefaultRateField = value;
            }
        }
        
        /// <remarks/>
        public EnrollPremise EnrollPremise {
            get {
                return this.enrollPremiseField;
            }
            set {
                this.enrollPremiseField = value;
            }
        }
        
        /// <remarks/>
        public string HistoricalUsageType {
            get {
                return this.historicalUsageTypeField;
            }
            set {
                this.historicalUsageTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool PORFlag {
            get {
                return this.pORFlagField;
            }
            set {
                this.pORFlagField = value;
            }
        }
        
        /// <remarks/>
        public bool CreditInsuranceFlag {
            get {
                return this.creditInsuranceFlagField;
            }
            set {
                this.creditInsuranceFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public enum LibertyCustomerTypeOptions {
        
        /// <remarks/>
        RES,
        
        /// <remarks/>
        SMB,
        
        /// <remarks/>
        LCI,
        
        /// <remarks/>
        GOVT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public enum BillingTypeOptions {
        
        /// <remarks/>
        SupplierConsolidated,
        
        /// <remarks/>
        BillReady,
        
        /// <remarks/>
        RateReady,
        
        /// <remarks/>
        Dual,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public enum PrintLayoutOptions {
        
        /// <remarks/>
        Standard,
        
        /// <remarks/>
        Extended,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public partial class EnrollRate {
        
        private PlanTypeOptions planTypeField;
        
        private string lDCRateCodeField;
        
        private EnrollRateDetail[] enrollRateDetailListField;
        
        /// <remarks/>
        public PlanTypeOptions PlanType {
            get {
                return this.planTypeField;
            }
            set {
                this.planTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LDCRateCode {
            get {
                return this.lDCRateCodeField;
            }
            set {
                this.lDCRateCodeField = value;
            }
        }
        
        /// <remarks/>
        public EnrollRateDetail[] EnrollRateDetailList {
            get {
                return this.enrollRateDetailListField;
            }
            set {
                this.enrollRateDetailListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public enum PlanTypeOptions {
        
        /// <remarks/>
        Fixed,
        
        /// <remarks/>
        PortfolioVariable,
        
        /// <remarks/>
        CustomVariable,
        
        /// <remarks/>
        HeatRate,
        
        /// <remarks/>
        MCPE,
        
        /// <remarks/>
        CustomBilling,
        
        /// <remarks/>
        Ruc,
        
        /// <remarks/>
        CustomIndex,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public partial class EnrollRateDetail {
        
        private int rateTemplateIDField;
        
        private System.DateTime rateEffectiveDateField;
        
        private System.DateTime rateExpirationDateField;
        
        private decimal rateAmountField;
        
        private System.Nullable<int> usageClassIDField;
        
        private System.Nullable<int> rateVariableTypeIDField;
        
        /// <remarks/>
        public int RateTemplateID {
            get {
                return this.rateTemplateIDField;
            }
            set {
                this.rateTemplateIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RateEffectiveDate {
            get {
                return this.rateEffectiveDateField;
            }
            set {
                this.rateEffectiveDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RateExpirationDate {
            get {
                return this.rateExpirationDateField;
            }
            set {
                this.rateExpirationDateField = value;
            }
        }
        
        /// <remarks/>
        public decimal RateAmount {
            get {
                return this.rateAmountField;
            }
            set {
                this.rateAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> UsageClassID {
            get {
                return this.usageClassIDField;
            }
            set {
                this.usageClassIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RateVariableTypeID {
            get {
                return this.rateVariableTypeIDField;
            }
            set {
                this.rateVariableTypeIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public partial class PreEnrollmentHURequest {
        
        private string customerNameField;
        
        private string eSIIDField;
        
        private string tDSPDunsField;
        
        private string eSPDunsField;
        
        private string billingAccountNumberField;
        
        private string nameKeyField;
        
        private string meterNumberField;
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ESIID {
            get {
                return this.eSIIDField;
            }
            set {
                this.eSIIDField = value;
            }
        }
        
        /// <remarks/>
        public string TDSPDuns {
            get {
                return this.tDSPDunsField;
            }
            set {
                this.tDSPDunsField = value;
            }
        }
        
        /// <remarks/>
        public string ESPDuns {
            get {
                return this.eSPDunsField;
            }
            set {
                this.eSPDunsField = value;
            }
        }
        
        /// <remarks/>
        public string BillingAccountNumber {
            get {
                return this.billingAccountNumberField;
            }
            set {
                this.billingAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string NameKey {
            get {
                return this.nameKeyField;
            }
            set {
                this.nameKeyField = value;
            }
        }
        
        /// <remarks/>
        public string MeterNumber {
            get {
                return this.meterNumberField;
            }
            set {
                this.meterNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public partial class ReEnrollment {
        
        private int customerIDField;
        
        private string eSIIDField;
        
        private System.DateTime requestDateField;
        
        private System.DateTime contractStartDateField;
        
        private System.DateTime contractStopDateField;
        
        private bool creditInsuranceFlagField;
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string ESIID {
            get {
                return this.eSIIDField;
            }
            set {
                this.eSIIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ContractStartDate {
            get {
                return this.contractStartDateField;
            }
            set {
                this.contractStartDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ContractStopDate {
            get {
                return this.contractStopDateField;
            }
            set {
                this.contractStopDateField = value;
            }
        }
        
        /// <remarks/>
        public bool CreditInsuranceFlag {
            get {
                return this.creditInsuranceFlagField;
            }
            set {
                this.creditInsuranceFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public partial class EnrollCustomerPremiseMeterServiceProvider {
        
        private int idField;
        
        private int enrollPremiseIDField;
        
        private string ownerDUNSField;
        
        private string installerDUNSField;
        
        private string readerDUNSField;
        
        private string maintenanceProviderDUNSField;
        
        private string dataManagementAgentDUNSField;
        
        private string schedulingCoordinatorDUNSField;
        
        private bool installPendingField;
        
        private System.Nullable<PackageOptions> packageOptionField;
        
        private System.Nullable<UsageCodes> usageCodeField;
        
        private int marketIDField;
        
        private string tdspDunsField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int EnrollPremiseID {
            get {
                return this.enrollPremiseIDField;
            }
            set {
                this.enrollPremiseIDField = value;
            }
        }
        
        /// <remarks/>
        public string OwnerDUNS {
            get {
                return this.ownerDUNSField;
            }
            set {
                this.ownerDUNSField = value;
            }
        }
        
        /// <remarks/>
        public string InstallerDUNS {
            get {
                return this.installerDUNSField;
            }
            set {
                this.installerDUNSField = value;
            }
        }
        
        /// <remarks/>
        public string ReaderDUNS {
            get {
                return this.readerDUNSField;
            }
            set {
                this.readerDUNSField = value;
            }
        }
        
        /// <remarks/>
        public string MaintenanceProviderDUNS {
            get {
                return this.maintenanceProviderDUNSField;
            }
            set {
                this.maintenanceProviderDUNSField = value;
            }
        }
        
        /// <remarks/>
        public string DataManagementAgentDUNS {
            get {
                return this.dataManagementAgentDUNSField;
            }
            set {
                this.dataManagementAgentDUNSField = value;
            }
        }
        
        /// <remarks/>
        public string SchedulingCoordinatorDUNS {
            get {
                return this.schedulingCoordinatorDUNSField;
            }
            set {
                this.schedulingCoordinatorDUNSField = value;
            }
        }
        
        /// <remarks/>
        public bool InstallPending {
            get {
                return this.installPendingField;
            }
            set {
                this.installPendingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<PackageOptions> PackageOption {
            get {
                return this.packageOptionField;
            }
            set {
                this.packageOptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<UsageCodes> UsageCode {
            get {
                return this.usageCodeField;
            }
            set {
                this.usageCodeField = value;
            }
        }
        
        /// <remarks/>
        public int MarketID {
            get {
                return this.marketIDField;
            }
            set {
                this.marketIDField = value;
            }
        }
        
        /// <remarks/>
        public string TdspDuns {
            get {
                return this.tdspDunsField;
            }
            set {
                this.tdspDunsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public enum PackageOptions {
        
        /// <remarks/>
        UNK,
        
        /// <remarks/>
        BASIC,
        
        /// <remarks/>
        NEXT,
        
        /// <remarks/>
        REAL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public enum UsageCodes {
        
        /// <remarks/>
        UNK,
        
        /// <remarks/>
        INTERVAL,
        
        /// <remarks/>
        LOADPROFILE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public partial class EnrollPremiseTaxPercentage {
        
        private TaxAssessmentOptions taxAssessmentValueField;
        
        private decimal percentageField;
        
        /// <remarks/>
        public TaxAssessmentOptions TaxAssessmentValue {
            get {
                return this.taxAssessmentValueField;
            }
            set {
                this.taxAssessmentValueField = value;
            }
        }
        
        /// <remarks/>
        public decimal Percentage {
            get {
                return this.percentageField;
            }
            set {
                this.percentageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public enum TaxAssessmentOptions {
        
        /// <remarks/>
        State = 1,
        
        /// <remarks/>
        County = 2,
        
        /// <remarks/>
        City = 4,
        
        /// <remarks/>
        Special = 8,
        
        /// <remarks/>
        PUC = 16,
        
        /// <remarks/>
        GRT = 32,
        
        /// <remarks/>
        Franchise = 64,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public partial class EnrollPremise {
        
        private string esiIdField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private EnrollmentTypeOptions enrollmentTypeField;
        
        private System.DateTime specialReadDateField;
        
        private string meterNumberField;
        
        private System.Nullable<int> lBMPIDField;
        
        private string billingAccountNumberField;
        
        private string nameKeyField;
        
        private TaxAssessmentOptions[] taxAssessmentListField;
        
        private EnrollPremiseTaxPercentage[] enrollPremiseTaxPercentageListField;
        
        private EnrollCustomerPremiseMeterServiceProvider meterServiceProviderField;
        
        private int marketIDField;
        
        private bool isLDC_UnMeteredAcctField;
        
        /// <remarks/>
        public string EsiId {
            get {
                return this.esiIdField;
            }
            set {
                this.esiIdField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public EnrollmentTypeOptions EnrollmentType {
            get {
                return this.enrollmentTypeField;
            }
            set {
                this.enrollmentTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SpecialReadDate {
            get {
                return this.specialReadDateField;
            }
            set {
                this.specialReadDateField = value;
            }
        }
        
        /// <remarks/>
        public string MeterNumber {
            get {
                return this.meterNumberField;
            }
            set {
                this.meterNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LBMPID {
            get {
                return this.lBMPIDField;
            }
            set {
                this.lBMPIDField = value;
            }
        }
        
        /// <remarks/>
        public string BillingAccountNumber {
            get {
                return this.billingAccountNumberField;
            }
            set {
                this.billingAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string NameKey {
            get {
                return this.nameKeyField;
            }
            set {
                this.nameKeyField = value;
            }
        }
        
        /// <remarks/>
        public TaxAssessmentOptions[] TaxAssessmentList {
            get {
                return this.taxAssessmentListField;
            }
            set {
                this.taxAssessmentListField = value;
            }
        }
        
        /// <remarks/>
        public EnrollPremiseTaxPercentage[] EnrollPremiseTaxPercentageList {
            get {
                return this.enrollPremiseTaxPercentageListField;
            }
            set {
                this.enrollPremiseTaxPercentageListField = value;
            }
        }
        
        /// <remarks/>
        public EnrollCustomerPremiseMeterServiceProvider MeterServiceProvider {
            get {
                return this.meterServiceProviderField;
            }
            set {
                this.meterServiceProviderField = value;
            }
        }
        
        /// <remarks/>
        public int MarketID {
            get {
                return this.marketIDField;
            }
            set {
                this.marketIDField = value;
            }
        }
        
        /// <remarks/>
        public bool IsLDC_UnMeteredAcct {
            get {
                return this.isLDC_UnMeteredAcctField;
            }
            set {
                this.isLDC_UnMeteredAcctField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public enum EnrollmentTypeOptions {
        
        /// <remarks/>
        SWITCH,
        
        /// <remarks/>
        OFF_CYCLE_SWITCH,
        
        /// <remarks/>
        MOVE_IN,
        
        /// <remarks/>
        PRIORITY_MOVE_IN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.libertypowerbilling.com/EnrollmentService")]
    public partial class EnrollDefaultRate {
        
        private PlanTypeOptions planTypeField;
        
        private string lDCRateCodeField;
        
        private EnrollRateDetail[] enrollRateDetailListField;
        
        private System.DateTime switchDateField;
        
        /// <remarks/>
        public PlanTypeOptions PlanType {
            get {
                return this.planTypeField;
            }
            set {
                this.planTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LDCRateCode {
            get {
                return this.lDCRateCodeField;
            }
            set {
                this.lDCRateCodeField = value;
            }
        }
        
        /// <remarks/>
        public EnrollRateDetail[] EnrollRateDetailList {
            get {
                return this.enrollRateDetailListField;
            }
            set {
                this.enrollRateDetailListField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SwitchDate {
            get {
                return this.switchDateField;
            }
            set {
                this.switchDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CreateEnrollmentCompletedEventHandler(object sender, CreateEnrollmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateEnrollmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateEnrollmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ProcessEnrollmentCompletedEventHandler(object sender, ProcessEnrollmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessEnrollmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessEnrollmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SubmitReEnrollmentCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CreateHistoricalUsageRequestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CreatePreEnrollmentHistoricalUsageRequestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591