//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateClass
    {
        public RateClass()
        {
            this.RateClassAlias = new HashSet<RateClassAlia>();
            this.PurchaseOfReceivables = new HashSet<PurchaseOfReceivable>();
            this.UtilityBillingTypes = new HashSet<UtilityBillingType>();
            this.LpBillingTypes = new HashSet<LpBillingType>();
            this.IdrRules = new HashSet<IdrRule>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid UtilityCompanyId { get; set; }
        public string RateClassCode { get; set; }
        public string Description { get; set; }
        public System.Guid AccountTypeId { get; set; }
        public bool Inactive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int RateClassId { get; set; }
        public System.Guid LpStandardRateClassId { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual LpStandardRateClass LpStandardRateClass { get; set; }
        public virtual ICollection<RateClassAlia> RateClassAlias { get; set; }
        public virtual ICollection<PurchaseOfReceivable> PurchaseOfReceivables { get; set; }
        public virtual ICollection<UtilityBillingType> UtilityBillingTypes { get; set; }
        public virtual ICollection<LpBillingType> LpBillingTypes { get; set; }
        public virtual UtilityCompany UtilityCompany { get; set; }
        public virtual ICollection<IdrRule> IdrRules { get; set; }
    }
}
