//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchToSearchCriteria
    {
        public System.Guid Id { get; set; }
        public System.Guid SearchId { get; set; }
        public System.Guid SearchCriteriaId { get; set; }
    
        public virtual Search Search { get; set; }
        public virtual SearchCriteria SearchCriteria { get; set; }
    }
}
