//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Year
    {
        public Year()
        {
            this.MeterReadSchedules = new HashSet<MeterReadSchedule>();
            this.MeterReadCalendars = new HashSet<MeterReadCalendar>();
        }
    
        public System.Guid Id { get; set; }
        public int Year1 { get; set; }
        public bool Inactive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        public virtual ICollection<MeterReadSchedule> MeterReadSchedules { get; set; }
        public virtual ICollection<MeterReadCalendar> MeterReadCalendars { get; set; }
    }
}
