//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class zAuditRequestModeHistoricalUsage
    {
        public System.Guid Id { get; set; }
        public System.Guid UtilityCompanyId { get; set; }
        public System.Guid RequestModeEnrollmentTypeId { get; set; }
        public System.Guid RequestModeTypeId { get; set; }
        public string AddressForPreEnrollment { get; set; }
        public string EmailTemplate { get; set; }
        public string Instructions { get; set; }
        public int UtilitysSlaHistoricalUsageResponseInDays { get; set; }
        public int LibertyPowersSlaFollowUpHistoricalUsageResponseInDays { get; set; }
        public bool IsLoaRequired { get; set; }
        public Nullable<bool> IcapAndHuPreEnrollmentRequestModeDifferenceIdentifiedAndOkdByUser { get; set; }
        public bool Inactive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<System.Guid> IdPrevious { get; set; }
        public Nullable<System.Guid> UtilityCompanyIdPrevious { get; set; }
        public Nullable<System.Guid> RequestModeEnrollmentTypeIdPrevious { get; set; }
        public Nullable<System.Guid> RequestModeTypeIdPrevious { get; set; }
        public string AddressForPreEnrollmentPrevious { get; set; }
        public string EmailTemplatePrevious { get; set; }
        public string InstructionsPrevious { get; set; }
        public Nullable<int> UtilitysSlaHistoricalUsageResponseInDaysPrevious { get; set; }
        public Nullable<int> LibertyPowersSlaFollowUpHistoricalUsageResponseInDaysPrevious { get; set; }
        public Nullable<bool> IsLoaRequiredPrevious { get; set; }
        public Nullable<bool> InactivePrevious { get; set; }
        public string CreatedByPrevious { get; set; }
        public Nullable<System.DateTime> CreatedDatePrevious { get; set; }
        public string LastModifiedByPrevious { get; set; }
        public Nullable<System.DateTime> LastModifiedDatePrevious { get; set; }
        public Nullable<long> SYS_CHANGE_VERSION { get; set; }
        public Nullable<long> SYS_CHANGE_CREATION_VERSION { get; set; }
        public string SYS_CHANGE_OPERATION { get; set; }
        public string SYS_CHANGE_COLUMNS { get; set; }
        public System.Guid IdPrimary { get; set; }
    }
}
