//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipCode
    {
        public ZipCode()
        {
            this.AccountsPerZipCodeByTimeSlice = new HashSet<AccountsPerZipCodeByTimeSlouse>();
            this.DemographicDatas = new HashSet<DemographicData>();
            this.SimilarZipCodesMedianAgeIncomeNetWorthPopulationDensities = new HashSet<SimilarZipCodesMedianAgeIncomeNetWorthPopulationDensity>();
        }
    
        public System.Guid Id { get; set; }
        public string ZipCode1 { get; set; }
        public string Description { get; set; }
        public System.Guid StateId { get; set; }
    
        public virtual ICollection<AccountsPerZipCodeByTimeSlouse> AccountsPerZipCodeByTimeSlice { get; set; }
        public virtual ICollection<DemographicData> DemographicDatas { get; set; }
        public virtual ICollection<SimilarZipCodesMedianAgeIncomeNetWorthPopulationDensity> SimilarZipCodesMedianAgeIncomeNetWorthPopulationDensities { get; set; }
        public virtual USState USState { get; set; }
    }
}
