CREATE TABLE [dbo].[zRenewals_maxALL] (
    [zAudit_account_id]         INT            IDENTITY (1, 1) NOT NULL,
    [account_id]                CHAR (12)      NULL,
    [account_number]            VARCHAR (30)   NULL,
    [account_type]              VARCHAR (35)   NULL,
    [status]                    VARCHAR (15)   NULL,
    [sub_status]                VARCHAR (15)   NULL,
    [customer_id]               VARCHAR (10)   NULL,
    [entity_id]                 CHAR (15)      NULL,
    [contract_nbr]              CHAR (12)      NULL,
    [contract_type]             VARCHAR (25)   NULL,
    [retail_mkt_id]             CHAR (2)       NULL,
    [utility_id]                CHAR (15)      NULL,
    [product_id]                CHAR (20)      NULL,
    [rate_id]                   INT            NULL,
    [rate]                      FLOAT (53)     NULL,
    [account_name_link]         INT            NULL,
    [customer_name_link]        INT            NULL,
    [customer_address_link]     INT            NULL,
    [customer_contact_link]     INT            NULL,
    [billing_address_link]      INT            NULL,
    [billing_contact_link]      INT            NULL,
    [owner_name_link]           INT            NULL,
    [service_address_link]      INT            NULL,
    [business_type]             VARCHAR (35)   NULL,
    [business_activity]         VARCHAR (35)   NULL,
    [additional_id_nbr_type]    VARCHAR (10)   NULL,
    [additional_id_nbr]         VARCHAR (30)   NULL,
    [contract_eff_start_date]   DATETIME       NULL,
    [term_months]               INT            NULL,
    [date_end]                  DATETIME       NULL,
    [date_deal]                 DATETIME       NULL,
    [date_created]              DATETIME       NULL,
    [date_submit]               DATETIME       NULL,
    [sales_channel_role]        NVARCHAR (100) NULL,
    [username]                  NCHAR (200)    NULL,
    [sales_rep]                 VARCHAR (100)  NOT NULL,
    [origin]                    VARCHAR (50)   NULL,
    [annual_usage]              INT            NULL,
    [date_flow_start]           DATETIME       NULL,
    [date_por_enrollment]       DATETIME       NULL,
    [date_deenrollment]         DATETIME       NULL,
    [date_reenrollment]         DATETIME       NULL,
    [tax_status]                VARCHAR (20)   NULL,
    [tax_rate]                  FLOAT (53)     NULL,
    [credit_score]              REAL           NULL,
    [credit_agency]             VARCHAR (30)   NULL,
    [por_option]                VARCHAR (50)   NULL,
    [billing_type]              VARCHAR (15)   NULL,
    [chgstamp]                  SMALLINT       NULL,
    [usage_req_status]          VARCHAR (20)   NULL,
    [Created]                   DATETIME       NULL,
    [CreatedBy]                 NVARCHAR (200) NULL,
    [Modified]                  DATETIME       NULL,
    [ModifiedBy]                NVARCHAR (200) NULL,
    [audit_change_type]         CHAR (3)       NOT NULL,
    [audit_change_dt]           DATETIME       NOT NULL,
    [audit_change_by]           VARCHAR (30)   NOT NULL,
    [audit_change_location]     VARCHAR (30)   NOT NULL,
    [ColumnsUpdated]            VARCHAR (MAX)  NULL,
    [ColumnsChanged]            VARCHAR (MAX)  NULL,
    [evergreen_option_id]       INT            NULL,
    [evergreen_commission_end]  DATETIME       NULL,
    [residual_option_id]        INT            NULL,
    [residual_commission_end]   DATETIME       NULL,
    [initial_pymt_option_id]    INT            NULL,
    [sales_manager]             VARCHAR (100)  NULL,
    [evergreen_commission_rate] FLOAT (53)     NULL
);

