CREATE TABLE [dbo].[ETL_UtilityInfoForWO08132013] (
    [Index]                                        VARCHAR (50)  NULL,
    [MARKET]                                       VARCHAR (50)  NULL,
    [ISO]                                          VARCHAR (250) NULL,
    [UTILITY]                                      VARCHAR (250) NULL,
    [UTILITY ACRONYM ]                             VARCHAR (250) NULL,
    [Service Account Pattern]                      VARCHAR (250) NULL,
    [Service Account Pattern Description]          VARCHAR (250) NULL,
    [Service Account Add Leading Zero]             VARCHAR (50)  NULL,
    [Service Account Truncate Last]                VARCHAR (50)  NULL,
    [Service Account Required for EDI Request]     VARCHAR (50)  NULL,
    [Meter Number Pattern]                         VARCHAR (250) NULL,
    [Meter Number Pattern Description]             VARCHAR (250) NULL,
    [Meter Number Add Leading Zero]                VARCHAR (50)  NULL,
    [Meter Number Truncate Last]                   VARCHAR (50)  NULL,
    [Meter Number Required for EDI Request]        VARCHAR (50)  NULL,
    [Billing Account Pattern]                      VARCHAR (250) NULL,
    [Billing Account Pattern Description]          VARCHAR (250) NULL,
    [Billing Account Add Leading Zero]             VARCHAR (50)  NULL,
    [Billing Account Truncate Last]                VARCHAR (50)  NULL,
    [Billing Account Required for EDI Request]     VARCHAR (50)  NULL,
    [Name Key Pattern]                             VARCHAR (250) NULL,
    [Name Key Pattern Description]                 VARCHAR (250) NULL,
    [Name Key Add Leading Zero]                    VARCHAR (50)  NULL,
    [Name Key Truncate Last]                       VARCHAR (50)  NULL,
    [Name Key Required for EDI Request]            VARCHAR (50)  NULL,
    [Service Address ZIP Pattern]                  VARCHAR (250) NULL,
    [Service Address ZIP Description]              VARCHAR (250) NULL,
    [Service Address ZIP Add Leading Zero]         VARCHAR (50)  NULL,
    [Service Address ZIP Truncate Last]            VARCHAR (50)  NULL,
    [Service Address ZIP Required for EDI Request] VARCHAR (50)  NULL,
    [Strata Pattern]                               VARCHAR (250) NULL,
    [Strata Description]                           VARCHAR (250) NULL,
    [Strata Add Leading Zero]                      VARCHAR (50)  NULL,
    [Strata Truncate Last]                         VARCHAR (50)  NULL,
    [Strata Required for EDI Request]              VARCHAR (50)  NULL,
    [UtilityCode]                                  NVARCHAR (50) NULL
);

