CREATE TABLE [dbo].[zAuditNameKeyPattern] (
    [Id]                                   UNIQUEIDENTIFIER NOT NULL,
    [UtilityCompanyId]                     UNIQUEIDENTIFIER NOT NULL,
    [NameKeyPattern]                       NVARCHAR (255)   NULL,
    [NameKeyPatternDescription]            NVARCHAR (255)   NOT NULL,
    [NameKeyAddLeadingZero]                INT              NULL,
    [NameKeyTruncateLast]                  INT              NULL,
    [NameKeyRequiredForEDIRequest]         BIT              NOT NULL,
    [Inactive]                             BIT              NOT NULL,
    [CreatedBy]                            NVARCHAR (100)   NOT NULL,
    [CreatedDate]                          DATETIME         NOT NULL,
    [LastModifiedBy]                       NVARCHAR (100)   NOT NULL,
    [LastModifiedDate]                     DATETIME         NOT NULL,
    [IdPrevious]                           UNIQUEIDENTIFIER NULL,
    [UtilityCompanyIdPrevious]             UNIQUEIDENTIFIER NULL,
    [NameKeyPatternPrevious]               NVARCHAR (255)   NULL,
    [NameKeyPatternDescriptionPrevious]    NVARCHAR (255)   NULL,
    [NameKeyAddLeadingZeroPrevious]        INT              NULL,
    [NameKeyTruncateLastPrevious]          INT              NULL,
    [NameKeyRequiredForEDIRequestPrevious] BIT              NULL,
    [InactivePrevious]                     BIT              NULL,
    [CreatedByPrevious]                    NVARCHAR (100)   NULL,
    [CreatedDatePrevious]                  DATETIME         NULL,
    [LastModifiedByPrevious]               NVARCHAR (100)   NULL,
    [LastModifiedDatePrevious]             DATETIME         NULL,
    [SYS_CHANGE_VERSION]                   BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_OPERATION]                 NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]                   NVARCHAR (1000)  NULL,
    [IdPrimary]                            UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [PK_zAuditNameKeyPattern] PRIMARY KEY CLUSTERED ([IdPrimary] ASC)
);

