CREATE TABLE [dbo].[zAuditServiceAddressZipPattern] (
    [Id]                                             UNIQUEIDENTIFIER NOT NULL,
    [UtilityCompanyId]                               UNIQUEIDENTIFIER NOT NULL,
    [ServiceAddressZipPattern]                       NVARCHAR (255)   NULL,
    [ServiceAddressZipPatternDescription]            NVARCHAR (255)   NOT NULL,
    [ServiceAddressZipAddLeadingZero]                INT              NULL,
    [ServiceAddressZipTruncateLast]                  INT              NULL,
    [ServiceAddressZipRequiredForEDIRequest]         BIT              NOT NULL,
    [Inactive]                                       BIT              NOT NULL,
    [CreatedBy]                                      NVARCHAR (100)   NOT NULL,
    [CreatedDate]                                    DATETIME         NOT NULL,
    [LastModifiedBy]                                 NVARCHAR (100)   NOT NULL,
    [LastModifiedDate]                               DATETIME         NOT NULL,
    [IdPrevious]                                     UNIQUEIDENTIFIER NULL,
    [UtilityCompanyIdPrevious]                       UNIQUEIDENTIFIER NULL,
    [ServiceAddressZipPatternPrevious]               NVARCHAR (255)   NULL,
    [ServiceAddressZipPatternDescriptionPrevious]    NVARCHAR (255)   NULL,
    [ServiceAddressZipAddLeadingZeroPrevious]        INT              NULL,
    [ServiceAddressZipTruncateLastPrevious]          INT              NULL,
    [ServiceAddressZipRequiredForEDIRequestPrevious] BIT              NULL,
    [InactivePrevious]                               BIT              NULL,
    [CreatedByPrevious]                              NVARCHAR (100)   NULL,
    [CreatedDatePrevious]                            DATETIME         NULL,
    [LastModifiedByPrevious]                         NVARCHAR (100)   NULL,
    [LastModifiedDatePrevious]                       DATETIME         NULL,
    [SYS_CHANGE_VERSION]                             BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION]                    BIGINT           NULL,
    [SYS_CHANGE_OPERATION]                           NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]                             NVARCHAR (1000)  NULL,
    [IdPrimary]                                      UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [PK_zAuditServiceAddressZipPattern] PRIMARY KEY CLUSTERED ([IdPrimary] ASC)
);

