CREATE TABLE [dbo].[zAuditServiceAccountPattern] (
    [Id]                                          UNIQUEIDENTIFIER NOT NULL,
    [UtilityCompanyId]                            UNIQUEIDENTIFIER NOT NULL,
    [ServiceAccountPattern]                       NVARCHAR (255)   NULL,
    [ServiceAccountPatternDescription]            NVARCHAR (255)   NOT NULL,
    [ServiceAccountAddLeadingZero]                INT              NULL,
    [ServiceAccountTruncateLast]                  INT              NULL,
    [ServiceAccountRequiredForEDIRequest]         BIT              NOT NULL,
    [Inactive]                                    BIT              NOT NULL,
    [CreatedBy]                                   NVARCHAR (100)   NOT NULL,
    [CreatedDate]                                 DATETIME         NOT NULL,
    [LastModifiedBy]                              NVARCHAR (100)   NOT NULL,
    [LastModifiedDate]                            DATETIME         NOT NULL,
    [IdPrevious]                                  UNIQUEIDENTIFIER NULL,
    [UtilityCompanyIdPrevious]                    UNIQUEIDENTIFIER NULL,
    [ServiceAccountPatternPrevious]               NVARCHAR (255)   NULL,
    [ServiceAccountPatternDescriptionPrevious]    NVARCHAR (255)   NULL,
    [ServiceAccountAddLeadingZeroPrevious]        INT              NULL,
    [ServiceAccountTruncateLastPrevious]          INT              NULL,
    [ServiceAccountRequiredForEDIRequestPrevious] BIT              NULL,
    [InactivePrevious]                            BIT              NULL,
    [CreatedByPrevious]                           NVARCHAR (100)   NULL,
    [CreatedDatePrevious]                         DATETIME         NULL,
    [LastModifiedByPrevious]                      NVARCHAR (100)   NULL,
    [LastModifiedDatePrevious]                    DATETIME         NULL,
    [SYS_CHANGE_VERSION]                          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION]                 BIGINT           NULL,
    [SYS_CHANGE_OPERATION]                        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]                          NVARCHAR (1000)  NULL,
    [IdPrimary]                                   UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [PK_zAuditServiceAccountPattern] PRIMARY KEY CLUSTERED ([IdPrimary] ASC)
);

