CREATE TABLE [dbo].[zAuditUtilityBillingType] (
    [IdPrimary]                           UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [Id]                                  UNIQUEIDENTIFIER NOT NULL,
    [UtilityCompanyId]                    UNIQUEIDENTIFIER NOT NULL,
    [PorDriverId]                         UNIQUEIDENTIFIER NOT NULL,
    [RateClassId]                         UNIQUEIDENTIFIER NULL,
    [LoadProfileId]                       UNIQUEIDENTIFIER NULL,
    [TariffCodeId]                        UNIQUEIDENTIFIER NULL,
    [UtilityOfferedBillingTypeId]         UNIQUEIDENTIFIER NOT NULL,
    [Inactive]                            BIT              NOT NULL,
    [CreatedBy]                           NVARCHAR (100)   NOT NULL,
    [CreatedDate]                         DATETIME         NOT NULL,
    [LastModifiedBy]                      NVARCHAR (100)   NOT NULL,
    [LastModifiedDate]                    DATETIME         NOT NULL,
    [IdPrevious]                          UNIQUEIDENTIFIER NULL,
    [UtilityCompanyIdPrevious]            UNIQUEIDENTIFIER NULL,
    [PorDriverIdPrevious]                 UNIQUEIDENTIFIER NULL,
    [RateClassIdPrevious]                 UNIQUEIDENTIFIER NULL,
    [LoadProfileIdPrevious]               UNIQUEIDENTIFIER NULL,
    [TariffCodeIdPrevious]                UNIQUEIDENTIFIER NULL,
    [UtilityOfferedBillingTypeIdPrevious] UNIQUEIDENTIFIER NULL,
    [InactivePrevious]                    BIT              NULL,
    [CreatedByPrevious]                   NVARCHAR (100)   NULL,
    [CreatedDatePrevious]                 DATETIME         NULL,
    [LastModifiedByPrevious]              NVARCHAR (100)   NULL,
    [LastModifiedDatePrevious]            DATETIME         NULL,
    [SYS_CHANGE_VERSION]                  BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION]         BIGINT           NULL,
    [SYS_CHANGE_OPERATION]                NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]                  NVARCHAR (1000)  NULL,
    CONSTRAINT [PK_zAuditUtilityBillingType] PRIMARY KEY CLUSTERED ([IdPrimary] ASC)
);

