CREATE TABLE [dbo].[zAuditRequestModeTypeToRequestModeTypeGenre] (
    [Id]                             UNIQUEIDENTIFIER NOT NULL,
    [RequestModeTypeId]              UNIQUEIDENTIFIER NOT NULL,
    [RequestModeTypeGenreId]         UNIQUEIDENTIFIER NOT NULL,
    [Inactive]                       BIT              NOT NULL,
    [CreatedBy]                      NVARCHAR (100)   NOT NULL,
    [CreatedDate]                    DATETIME         NOT NULL,
    [LastModifiedBy]                 NVARCHAR (100)   NOT NULL,
    [LastModifiedDate]               DATETIME         NOT NULL,
    [IdPrevious]                     UNIQUEIDENTIFIER NULL,
    [RequestModeTypeIdPrevious]      UNIQUEIDENTIFIER NULL,
    [RequestModeTypeGenreIdPrevious] UNIQUEIDENTIFIER NULL,
    [InactivePrevious]               BIT              NULL,
    [CreatedByPrevious]              NVARCHAR (100)   NULL,
    [CreatedDatePrevious]            DATETIME         NULL,
    [LastModifiedByPrevious]         NVARCHAR (100)   NULL,
    [LastModifiedDatePrevious]       DATETIME         NULL,
    [SYS_CHANGE_VERSION]             BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION]    BIGINT           NULL,
    [SYS_CHANGE_OPERATION]           NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]             NVARCHAR (1000)  NULL,
    [IdPrimary]                      UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [PK_zAuditRequestModeTypeToRequestModeTypeGenre] PRIMARY KEY CLUSTERED ([IdPrimary] ASC)
);

