CREATE TABLE [dbo].[zAuditMeterType] (
    [Id]                          UNIQUEIDENTIFIER NOT NULL,
    [UtilityCompanyId]            UNIQUEIDENTIFIER NULL,
    [MeterTypeCode]               NVARCHAR (255)   NOT NULL,
    [Description]                 NVARCHAR (255)   NOT NULL,
    [AccountTypeId]               UNIQUEIDENTIFIER NOT NULL,
    [LpStandardMeterType]         NVARCHAR (255)   NOT NULL,
    [Sequence]                    INT              NOT NULL,
    [Inactive]                    BIT              NOT NULL,
    [CreatedBy]                   NVARCHAR (100)   NOT NULL,
    [CreatedDate]                 DATETIME         NOT NULL,
    [LastModifiedBy]              NVARCHAR (100)   NOT NULL,
    [LastModifiedDate]            DATETIME         NOT NULL,
    [IdPrevious]                  UNIQUEIDENTIFIER NULL,
    [UtilityCompanyIdPrevious]    UNIQUEIDENTIFIER NULL,
    [MeterTypeCodePrevious]       NVARCHAR (255)   NULL,
    [DescriptionPrevious]         NVARCHAR (255)   NULL,
    [AccountTypeIdPrevious]       UNIQUEIDENTIFIER NULL,
    [LpStandardMeterTypePrevious] NVARCHAR (255)   NULL,
    [SequencePrevious]            INT              NULL,
    [InactivePrevious]            BIT              NULL,
    [CreatedByPrevious]           NVARCHAR (100)   NULL,
    [CreatedDatePrevious]         DATETIME         NULL,
    [LastModifiedByPrevious]      NVARCHAR (100)   NULL,
    [LastModifiedDatePrevious]    DATETIME         NULL,
    [SYS_CHANGE_VERSION]          BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION] BIGINT           NULL,
    [SYS_CHANGE_OPERATION]        NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]          NVARCHAR (1000)  NULL,
    [IdPrimary]                   UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [PK_zAuditMeterType] PRIMARY KEY CLUSTERED ([IdPrimary] ASC)
);

