CREATE TABLE [dbo].[zAuditStrataPattern] (
    [Id]                                  UNIQUEIDENTIFIER NOT NULL,
    [UtilityCompanyId]                    UNIQUEIDENTIFIER NOT NULL,
    [StrataPattern]                       NVARCHAR (255)   NULL,
    [StrataPatternDescription]            NVARCHAR (255)   NOT NULL,
    [StrataAddLeadingZero]                INT              NULL,
    [StrataTruncateLast]                  INT              NULL,
    [StrataRequiredForEDIRequest]         BIT              NOT NULL,
    [Inactive]                            BIT              NOT NULL,
    [CreatedBy]                           NVARCHAR (100)   NOT NULL,
    [CreatedDate]                         DATETIME         NOT NULL,
    [LastModifiedBy]                      NVARCHAR (100)   NOT NULL,
    [LastModifiedDate]                    DATETIME         NOT NULL,
    [IdPrevious]                          UNIQUEIDENTIFIER NULL,
    [UtilityCompanyIdPrevious]            UNIQUEIDENTIFIER NULL,
    [StrataPatternPrevious]               NVARCHAR (255)   NULL,
    [StrataPatternDescriptionPrevious]    NVARCHAR (255)   NULL,
    [StrataAddLeadingZeroPrevious]        INT              NULL,
    [StrataTruncateLastPrevious]          INT              NULL,
    [StrataRequiredForEDIRequestPrevious] BIT              NULL,
    [InactivePrevious]                    BIT              NULL,
    [CreatedByPrevious]                   NVARCHAR (100)   NULL,
    [CreatedDatePrevious]                 DATETIME         NULL,
    [LastModifiedByPrevious]              NVARCHAR (100)   NULL,
    [LastModifiedDatePrevious]            DATETIME         NULL,
    [SYS_CHANGE_VERSION]                  BIGINT           NULL,
    [SYS_CHANGE_CREATION_VERSION]         BIGINT           NULL,
    [SYS_CHANGE_OPERATION]                NCHAR (1)        NULL,
    [SYS_CHANGE_COLUMNS]                  NVARCHAR (1000)  NULL,
    [IdPrimary]                           UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    CONSTRAINT [PK_zAuditStrataPattern] PRIMARY KEY CLUSTERED ([IdPrimary] ASC)
);

