//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibertyPower.DataAccess.SqlAccess.TransactionsSql.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdrFileLogDetail
    {
        public IdrFileLogDetail()
        {
            this.IdrFileVsHuDiscrepancies = new HashSet<IdrFileVsHuDiscrepancy>();
        }
    
        public int ID { get; set; }
        public string Tab { get; set; }
        public string UtilityCode { get; set; }
        public string Information { get; set; }
        public Nullable<byte> IsProcessed { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public byte Status { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<short> FormatType { get; set; }
        public Nullable<decimal> AverageDifference { get; set; }
        public string MeterNumber { get; set; }
        public string RecorderNumber { get; set; }
    
        public virtual IdrFileLogHeader IdrFileLogHeader { get; set; }
        public virtual ICollection<IdrFileVsHuDiscrepancy> IdrFileVsHuDiscrepancies { get; set; }
    }
}
