//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibertyPower.DataAccess.SqlAccess.TransactionsSql.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdrFileLogHeader
    {
        public IdrFileLogHeader()
        {
            this.IdrFileLogDetails = new HashSet<IdrFileLogDetail>();
        }
    
        public int ID { get; set; }
        public string FileGuid { get; set; }
        public string FileName { get; set; }
        public Nullable<short> Attempts { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<byte> FileType { get; set; }
        public string Notes { get; set; }
        public byte Status { get; set; }
        public Nullable<bool> IsARawFile { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<IdrFileLogDetail> IdrFileLogDetails { get; set; }
    }
}
