CREATE TABLE [Staging].[PECOECLHU] (
    [ID]                          INT           IDENTITY (1, 1) NOT NULL,
    [EDCDUNSNumber]               VARCHAR (50)  NULL,
    [CustomerAccountNumber]       VARCHAR (50)  NULL,
    [MeterReadCycle]              VARCHAR (50)  NULL,
    [CustomerName1]               VARCHAR (50)  NULL,
    [CustomerName2]               VARCHAR (50)  NULL,
    [ServiceAddress1]             VARCHAR (50)  NULL,
    [ServiceAddress2]             VARCHAR (50)  NULL,
    [ServiceCity]                 VARCHAR (50)  NULL,
    [ServiceState]                VARCHAR (50)  NULL,
    [ServiceZip]                  VARCHAR (50)  NULL,
    [BillingName1]                VARCHAR (50)  NULL,
    [BillingAddress1]             VARCHAR (50)  NULL,
    [BillingAddress2]             VARCHAR (50)  NULL,
    [BillingCity]                 VARCHAR (50)  NULL,
    [BillingState]                VARCHAR (50)  NULL,
    [BillingZip]                  VARCHAR (50)  NULL,
    [BillingCountryCode]          VARCHAR (50)  NULL,
    [ContactName1]                VARCHAR (50)  NULL,
    [ContactAddress1]             VARCHAR (50)  NULL,
    [ContactAddress2]             VARCHAR (50)  NULL,
    [ContactCity]                 VARCHAR (50)  NULL,
    [ContactState]                VARCHAR (50)  NULL,
    [ContactZip]                  VARCHAR (50)  NULL,
    [ContractCountryCode]         VARCHAR (50)  NULL,
    [RateCode]                    VARCHAR (50)  NULL,
    [RateSubclass]                VARCHAR (50)  NULL,
    [ProfileGroup]                VARCHAR (50)  NULL,
    [TotalKWH]                    VARCHAR (50)  NULL,
    [NumberofMonths]              VARCHAR (50)  NULL,
    [PeakDemand12mo]              VARCHAR (50)  NULL,
    [LoadFactor]                  VARCHAR (50)  NULL,
    [CurrentPLC]                  VARCHAR (50)  NULL,
    [OldCustomerAccountNumber]    VARCHAR (50)  NULL,
    [UsagePeriod1]                VARCHAR (50)  NULL,
    [DemandPeriod1]               VARCHAR (50)  NULL,
    [Period1]                     VARCHAR (50)  NULL,
    [UsagePeriod2]                VARCHAR (50)  NULL,
    [DemandPeriod2]               VARCHAR (50)  NULL,
    [Period2]                     VARCHAR (50)  NULL,
    [UsagePeriod3]                VARCHAR (50)  NULL,
    [DemandPeriod3]               VARCHAR (50)  NULL,
    [Period3]                     VARCHAR (50)  NULL,
    [UsagePeriod4]                VARCHAR (50)  NULL,
    [DemandPeriod4]               VARCHAR (50)  NULL,
    [Period4]                     VARCHAR (50)  NULL,
    [UsagePeriod5]                VARCHAR (50)  NULL,
    [DemandPeriod5]               VARCHAR (50)  NULL,
    [Period5]                     VARCHAR (50)  NULL,
    [UsagePeriod6]                VARCHAR (50)  NULL,
    [DemandPeriod6]               VARCHAR (50)  NULL,
    [Period6]                     VARCHAR (50)  NULL,
    [UsagePeriod7]                VARCHAR (50)  NULL,
    [DemandPeriod7]               VARCHAR (50)  NULL,
    [Period7]                     VARCHAR (50)  NULL,
    [UsagePeriod8]                VARCHAR (50)  NULL,
    [DemandPeriod8]               VARCHAR (50)  NULL,
    [Period8]                     VARCHAR (50)  NULL,
    [UsagePeriod9]                VARCHAR (50)  NULL,
    [DemandPeriod9]               VARCHAR (50)  NULL,
    [Period9]                     VARCHAR (50)  NULL,
    [UsagePeriod10]               VARCHAR (50)  NULL,
    [DemandPeriod10]              VARCHAR (50)  NULL,
    [Period10]                    VARCHAR (50)  NULL,
    [UsagePeriod11]               VARCHAR (50)  NULL,
    [DemandPeriod11]              VARCHAR (50)  NULL,
    [Period11]                    VARCHAR (50)  NULL,
    [UsagePeriod12]               VARCHAR (50)  NULL,
    [DemandPeriod12]              VARCHAR (50)  NULL,
    [Period12]                    VARCHAR (50)  NULL,
    [CurrentNSPL]                 VARCHAR (50)  NULL,
    [MeterFlag]                   VARCHAR (50)  NULL,
    [RevisionDate]                VARCHAR (50)  NULL,
    [PrimaryPhoneNumber]          VARCHAR (50)  NULL,
    [SecondaryPhoneNumber]        VARCHAR (50)  NULL,
    [POLRIndicator]               VARCHAR (50)  NULL,
    [IntervalMeterIndicator]      VARCHAR (50)  NULL,
    [FutureNSPL]                  VARCHAR (50)  NULL,
    [FuturePLC]                   VARCHAR (50)  NULL,
    [CriticalPeakPricingRider]    VARCHAR (50)  NULL,
    [NetMetering_Renewablesrider] VARCHAR (50)  NULL,
    [TaxStatusIndicator]          VARCHAR (50)  NULL,
    [OffPeakPeriod1]              VARCHAR (50)  NULL,
    [OnPeakPeriod1]               VARCHAR (50)  NULL,
    [OffPeakPeriod2]              VARCHAR (50)  NULL,
    [OnPeakPeriod2]               VARCHAR (50)  NULL,
    [OffPeakperiod3]              VARCHAR (50)  NULL,
    [OnPeakperiod3]               VARCHAR (50)  NULL,
    [OffPeakPeriod4]              VARCHAR (50)  NULL,
    [OnPeakPeriod4]               VARCHAR (50)  NULL,
    [OffPeakPeriod5]              VARCHAR (50)  NULL,
    [OnPeakPeriod5]               VARCHAR (50)  NULL,
    [OffPeakPeriod6]              VARCHAR (50)  NULL,
    [OnPeakPeriod6]               VARCHAR (50)  NULL,
    [OffPeakPeriod7]              VARCHAR (50)  NULL,
    [OnPeakPeriod7]               VARCHAR (50)  NULL,
    [OffPeakPeriod8]              VARCHAR (50)  NULL,
    [OnPeakPeriod8]               VARCHAR (50)  NULL,
    [OffPeakPeriod9]              VARCHAR (50)  NULL,
    [OnPeakPeriod9]               VARCHAR (50)  NULL,
    [OffPeakPeriod10]             VARCHAR (50)  NULL,
    [OnPeakPeriod10]              VARCHAR (50)  NULL,
    [OffPeakPeriod11]             VARCHAR (50)  NULL,
    [OnPeakPeriod11]              VARCHAR (50)  NULL,
    [OffPeakPeriod12]             VARCHAR (50)  NULL,
    [OnPeakPeriod12]              VARCHAR (50)  NULL,
    [PostalServiceAddress1]       VARCHAR (100) NULL,
    [PostalServiceAddress2]       VARCHAR (100) NULL,
    [PostalServiceCity]           VARCHAR (50)  NULL,
    [PostalServiceState]          VARCHAR (50)  NULL,
    [PostalServiceZip]            VARCHAR (50)  NULL,
    [PostalServiceZipPlus4]       VARCHAR (50)  NULL,
    [Filler]                      VARCHAR (50)  NULL,
    [ContextDate]                 DATETIME      NOT NULL,
    [DateCreated]                 DATETIME      DEFAULT (getdate()) NOT NULL,
    [IsValid]                     BIT           DEFAULT ((1)) NOT NULL,
    [FileImportID]                INT           NULL,
    CONSTRAINT [PECOECL_id_fk] FOREIGN KEY ([FileImportID]) REFERENCES [dbo].[FileImport] ([ID])
);


GO

CREATE NONCLUSTERED INDEX [PECOECLHU_CustomerAccountNumber] ON [Staging].[PECOECLHU]
(
       [CustomerAccountNumber] ASC
)
INCLUDE (     [ContextDate]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

