


-- =============================================
-- Author:		Rick Deigsler
-- Create date: 8/16/2008
-- Description:	
-- =============================================
CREATE PROCEDURE [dbo].[usp_clone_offer_ins] 

@p_offer_id			varchar(50),
@p_offer_id_clone	varchar(50)

AS

DECLARE	@w_PRODUCT											nvarchar(50),
		@w_POWER_INDEX										nvarchar(10),
		@w_BLOCK_SIZE										nvarchar(50),
		@w_PEAK_VALUE										decimal(16,2),
		@w_PEAK_UNIT										nvarchar(2),
		@w_OFF_PEAK_VALUE									decimal(16,2),
		@w_OFF_PEAK_UNIT									nvarchar(2),
		@w_VALUE_24_7										decimal(16,2),
		@w_UNIT_24_7										nvarchar(2),
		@w_HENRY_HUB_DAILY									numeric,
		@w_HENRY_HUB_MONTHLY								numeric,
		@w_LOOSES_INCLUDED									nvarchar(50),
		@w_ANCILLARY_SERVICES_INCLUDED						nvarchar(50),
		@w_ANCILLARY_SERVICES_OPERATING_RESERVE_INCLUDED	nvarchar(50),
		@w_CAPACITY											nvarchar(50),
		@w_NETWORK_TRANSMISSION_INCLUDED					nvarchar(50),
		@w_RENEWABLES_INCLUDED								nvarchar(50),
		@w_BAND_WITH_INCLUDED								nvarchar(50),
		@w_GAS_INDEX_INCUDED								nvarchar(50),
		@w_CONSULTANTS_FEE_INCLUDED							nvarchar(50),
		@w_OTHERS_INCLUDED									nvarchar(50),
		@w_RENEWABLES_VALUE									decimal(16,2),
		@w_BAND_WITH_VALUE									decimal(16,2),
		@w_CONSULTANTS_FEE_VALUE							decimal(16,2),
		@w_OTHERS_VALUE										nvarchar(50),
		@w_LOSSES											decimal(18,0),
		@w_STATUS											nvarchar(50),
		@w_DATE_CREATED										datetime

SELECT		@w_PRODUCT = PRODUCT, @w_POWER_INDEX = POWER_INDEX, 
			@w_BLOCK_SIZE = BLOCK_SIZE, @w_PEAK_VALUE = PEAK_VALUE, 
			@w_PEAK_UNIT = PEAK_UNIT, @w_OFF_PEAK_VALUE = OFF_PEAK_VALUE, 
			@w_OFF_PEAK_UNIT = OFF_PEAK_UNIT, @w_VALUE_24_7 = VALUE_24_7, 
			@w_UNIT_24_7 = UNIT_24_7, @w_HENRY_HUB_DAILY = HENRY_HUB_DAILY, 
			@w_HENRY_HUB_MONTHLY = HENRY_HUB_MONTHLY, @w_LOOSES_INCLUDED = LOOSES_INCLUDED, 
			@w_ANCILLARY_SERVICES_INCLUDED = ANCILLARY_SERVICES_INCLUDED, 
			@w_ANCILLARY_SERVICES_OPERATING_RESERVE_INCLUDED = ANCILLARY_SERVICES_OPERATING_RESERVE_INCLUDED, 
			@w_CAPACITY = CAPACITY, @w_NETWORK_TRANSMISSION_INCLUDED = NETWORK_TRANSMISSION_INCLUDED, 
			@w_RENEWABLES_INCLUDED = RENEWABLES_INCLUDED, @w_BAND_WITH_INCLUDED = BAND_WITH_INCLUDED, 
			@w_GAS_INDEX_INCUDED = GAS_INDEX_INCUDED, @w_CONSULTANTS_FEE_INCLUDED = CONSULTANTS_FEE_INCLUDED, 
			@w_OTHERS_INCLUDED = OTHERS_INCLUDED, @w_RENEWABLES_VALUE = RENEWABLES_VALUE, 
			@w_BAND_WITH_VALUE = BAND_WITH_VALUE, @w_CONSULTANTS_FEE_VALUE = CONSULTANTS_FEE_VALUE, 
			@w_OTHERS_VALUE = OTHERS_VALUE, @w_LOSSES = LOSSES, @w_STATUS = 'Usage Complete', @w_DATE_CREATED = GETDATE()
FROM		OE_OFFER
WHERE		OFFER_ID = @p_offer_id

INSERT INTO	OE_OFFER (OFFER_ID, PRODUCT, POWER_INDEX, BLOCK_SIZE, PEAK_VALUE, PEAK_UNIT, OFF_PEAK_VALUE, 
			OFF_PEAK_UNIT, VALUE_24_7, UNIT_24_7, HENRY_HUB_DAILY, HENRY_HUB_MONTHLY, LOOSES_INCLUDED, 
			ANCILLARY_SERVICES_INCLUDED, ANCILLARY_SERVICES_OPERATING_RESERVE_INCLUDED, CAPACITY, 
			NETWORK_TRANSMISSION_INCLUDED, RENEWABLES_INCLUDED, BAND_WITH_INCLUDED, GAS_INDEX_INCUDED, 
			CONSULTANTS_FEE_INCLUDED, OTHERS_INCLUDED, RENEWABLES_VALUE, BAND_WITH_VALUE, CONSULTANTS_FEE_VALUE,
			OTHERS_VALUE, LOSSES, STATUS, DATE_CREATED, IS_REFRESH)
VALUES		(@p_offer_id_clone, @w_PRODUCT, @w_POWER_INDEX, @w_BLOCK_SIZE, @w_PEAK_VALUE, @w_PEAK_UNIT,
			@w_OFF_PEAK_VALUE, @w_OFF_PEAK_UNIT, @w_VALUE_24_7, @w_UNIT_24_7, @w_HENRY_HUB_DAILY,
			@w_HENRY_HUB_MONTHLY, @w_LOOSES_INCLUDED, @w_ANCILLARY_SERVICES_INCLUDED, @w_ANCILLARY_SERVICES_OPERATING_RESERVE_INCLUDED,
			@w_CAPACITY, @w_NETWORK_TRANSMISSION_INCLUDED, @w_RENEWABLES_INCLUDED, @w_BAND_WITH_INCLUDED,
			@w_GAS_INDEX_INCUDED, @w_CONSULTANTS_FEE_INCLUDED, @w_OTHERS_INCLUDED, @w_RENEWABLES_VALUE,
			@w_BAND_WITH_VALUE, @w_CONSULTANTS_FEE_VALUE, @w_OTHERS_VALUE, @w_LOSSES, @w_STATUS, @w_DATE_CREATED, 1)



