
-- =============================================
-- Author:		Rick Deigsler
-- Create date: 2/29/2008
-- Description:	
-- =============================================
CREATE PROCEDURE [dbo].[usp_pricing_request_by_id_sel]

@p_pricing_request_id		varchar(50)

AS

SELECT	ID, REQUEST_ID, 
		ISNULL(CUSTOMER_NAME, '') AS CUSTOMER_NAME, 
		ISNULL(OPPORTUNITY_NAME, '') AS OPPORTUNITY_NAME, 
		ISNULL(DUE_DATE, '') AS DUE_DATE, 
		ISNULL(CREATION_DATE, '') AS CREATION_DATE,
		ISNULL([TYPE], '') AS [TYPE], 
		ISNULL(SALES_REPRESENTATIVE, '') AS SALES_REPRESENTATIVE, 
		ISNULL(STATUS, '') AS STATUS, 
		ISNULL(TOTAL_NUMBER_OF_ACCOUNTS, 0) AS TOTAL_NUMBER_OF_ACCOUNTS, 
		ISNULL(ANNUAL_ESTIMATED_MHW, 0) AS ANNUAL_ESTIMATED_MHW,
		ISNULL(COMMENTS, '') AS COMMENTS, 
		ISNULL(CHANGE_REASON, '') AS CHANGE_REASON, 
		ISNULL(HOLD_TIME, '') AS HOLD_TIME, 
		ISNULL(ANALYST, '') AS ANALYST, 
		ISNULL(APPROVE_COMMENTS, '') AS APPROVE_COMMENTS, 
		ISNULL(APPROVE_DATE, '') AS APPROVE_DATE,
		ISNULL(SALES_CHANNEL, '') AS SALES_CHANNEL,
		ISNULL(ACCOUNT_TYPE, '') AS ACCOUNT_TYPE,
		ISNULL(REFRESH_STATUS, '') AS REFRESH_STATUS
FROM	OE_PRICING_REQUEST WITH (NOLOCK)
WHERE	REQUEST_ID = @p_pricing_request_id




