CREATE PROC [dbo].[usp_PricingRequestOfferHistory_GetOffersForMostRecentPricingRequest]
@RequestId NVARCHAR(255)
AS
BEGIN

DECLARE @MaxDate DATETIME
--DECLARE @RequestId NVARCHAR(255)
--SET @RequestId = 'asdf'

SELECT
	@MaxDate = MAX(OPROH.DATE_CREATED)
FROM
	OE_PRICING_REQUEST_OFFER_HISTORY (NOLOCK) OPROH
	INNER JOIN OE_PRICING_REQUEST (NOLOCK) OPR
		ON OPROH.PRICE_REQUEST_ID = OPR.ID
			AND OPR.REQUEST_ID = @RequestId


SELECT
	OPROH.ID PricingReqestOfferHistoryId,
	OPROHO.ID PricingRequestOfferHistoryOfferId,
	OPR.ID PricingRequestId,
	OPR.REQUEST_ID,
	OPROHO.OFFER_ID OfferId,
	OO.OFFER_ID
FROM
	OE_PRICING_REQUEST_OFFER_HISTORY (NOLOCK) OPROH
	INNER JOIN OE_PRICING_REQUEST (NOLOCK) OPR
		ON OPROH.PRICE_REQUEST_ID = OPR.ID
			AND RTRIM(LTRIM(OPR.REQUEST_ID)) = RTRIM(LTRIM(@RequestId))
			AND OPROH.DATE_CREATED = @MaxDate
	LEFT OUTER JOIN OE_PRICING_REQUEST_OFFER_HISTORY_OFFER (NOLOCK) OPROHO
		ON OPROH.ID = OPROHO.PRICING_REQUEST_OFFER_HISTORY_ID
	LEFT OUTER JOIN OE_OFFER (NOLOCK) OO
		ON OPROHO.OFFER_ID = OO.ID

END
