//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibertyPower.DataAccess.WebServiceAccess.IstaWebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://uat.ws.libertypowerbilling.com/CustomerService.asmx")]
        public string IstaWebService_IstaCustomerService_CustomerService {
            get {
                return ((string)(this["IstaWebService_IstaCustomerService_CustomerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://uat.ws.libertypowerbilling.com/CustomerService.asmx")]
        public string IstaWebService_CustomerService_CustomerService {
            get {
                return ((string)(this["IstaWebService_CustomerService_CustomerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ua.ws.libertypowerbilling.com/RateService.asmx")]
        public string IstaWebService_com_libertypowerbilling_ws_uat_RateService {
            get {
                return ((string)(this["IstaWebService_com_libertypowerbilling_ws_uat_RateService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://uat.ws.libertypowerbilling.com/InvoiceService.asmx")]
        public string IstaWebService_IstaInvoiceService_InvoiceService {
            get {
                return ((string)(this["IstaWebService_IstaInvoiceService_InvoiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ua.ws.libertypowerbilling.com/EnrollmentService.asmx")]
        public string IstaWebService_IstaEnrollmentService_EnrollmentService {
            get {
                return ((string)(this["IstaWebService_IstaEnrollmentService_EnrollmentService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.services.ista-billing.com/api/Rate.asmx")]
        public string IstaWebService_IstaBillingService_Rate {
            get {
                return ((string)(this["IstaWebService_IstaBillingService_Rate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://lpcnocws4:8077/Request.svc")]
        public string IstaWebService_RequestService_Request {
            get {
                return ((string)(this["IstaWebService_RequestService_Request"]));
            }
        }
    }
}
