//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibertyPower.DataAccess.SqlAccess.TransactionsSql.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdrAccountStageInfo
    {
        public IdrAccountStageInfo()
        {
            this.IdrAccountDetails = new HashSet<IdrAccountDetail>();
            this.IdrAccountVsHuDiscrepancies = new HashSet<IdrAccountVsHuDiscrepancy>();
        }
    
        public int Id { get; set; }
        public string AccountNumber { get; set; }
        public string UtilityCode { get; set; }
        public string Stage { get; set; }
        public byte Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<IdrAccountDetail> IdrAccountDetails { get; set; }
        public virtual ICollection<IdrAccountVsHuDiscrepancy> IdrAccountVsHuDiscrepancies { get; set; }
    }
}
