//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibertyPower.DataAccess.SqlAccess.TransactionsSql.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdrUtilityRawParser
    {
        public int Id { get; set; }
        public int UtilityId { get; set; }
        public string ParserType { get; set; }
        public bool IsAccountNumberInFile { get; set; }
        public string FileStartstWith { get; set; }
    }
}
