CREATE PROCEDURE [dbo].[USP_LOG_DAM_PRICE_DROPPED_INS]
	@P_FILENAME VARCHAR(100),
	@P_CREATED_BY VARCHAR(50)
AS
	SET NOCOUNT ON;

	INSERT INTO [LOG_DAM_PRICE_DROPPED] ([FILE_NAME], [CREATED_BY])
	VALUES (@P_FILENAME, @P_CREATED_BY);

	RETURN @@IDENTITY;
