CREATE TABLE [dbo].[LOG_DAM_PRICE_DROPPED] (
    [ROW_ID]       INT            IDENTITY (1, 1) NOT NULL,
    [FILE_NAME]    VARCHAR (100)  NULL,
    [DATE_STAMP]   DATETIME       NULL,
    [SUCCESS]      BIT            CONSTRAINT [DF_LOG_DAM_PRICE_DROPPED_SUCCESS] DEFAULT ((0)) NOT NULL,
    [ERROR_MSG]    VARCHAR (1000) NULL,
    [DATE_CREATED] DATETIME       CONSTRAINT [DF_LOG_DAM_PRICE_DROPPED_DATE_CREATED] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY]   VARCHAR (50)   NULL,
    [ROW_COUNT]    INT            NULL,
    CONSTRAINT [PK_LOG_DAM_PRICE_DROPPED] PRIMARY KEY CLUSTERED ([ROW_ID] ASC)
);

