CREATE TABLE [dbo].[SETLPOINTHISTORY] (
    [UIDSETLPOINT]     NUMERIC (19) NOT NULL,
    [STARTTIME]        DATETIME     NOT NULL,
    [STOPTIME]         DATETIME     NULL,
    [UIDSETLPOINTTYPE] NUMERIC (19) NULL,
    [CMZONECODE]       VARCHAR (64) NULL,
    [LSTIME]           DATETIME     NULL,
    [CREATED]          DATETIME     CONSTRAINT [DF_SETLPOINTHISTORY_CREATED] DEFAULT (getdate()) NULL,
    [ROW_ID]           INT          IDENTITY (1, 1) NOT NULL,
    [PROCESSED_ID]     INT          NULL,
    CONSTRAINT [PK_SETLPOINTHISTORY] PRIMARY KEY CLUSTERED ([ROW_ID] ASC)
);

