CREATE TABLE [dbo].[SETTLEMENTPOINT] (
    [UIDSETLPOINT]  NUMERIC (19) NOT NULL,
    [SETLPOINTCODE] VARCHAR (12) NOT NULL,
    [LSTIME]        DATETIME     NULL,
    [CREATED]       DATETIME     CONSTRAINT [DF_SETTLEMENTPOINT_CREATED] DEFAULT (getdate()) NULL,
    [ROW_ID]        INT          IDENTITY (1, 1) NOT NULL,
    [PROCESSED_ID]  INT          NULL,
    CONSTRAINT [PK_SETTLEMENTPOINT] PRIMARY KEY CLUSTERED ([ROW_ID] ASC)
);

