CREATE TABLE [dbo].[USAGE_FILE_TYPE] (
    [ROW_ID]        INT           IDENTITY (1, 1) NOT NULL,
    [FILE_TYPE]     VARCHAR (50)  NOT NULL,
    [FILE_HAS_DATE] BIT           CONSTRAINT [DF_USAGE_FILE_TYPE_FILE_HAS_DATE] DEFAULT ((0)) NOT NULL,
    [DATE_REGEX]    VARCHAR (100) NULL,
    [DATE_FORMAT]   VARCHAR (50)  NULL,
    [LOAD_ORDER]    TINYINT       NOT NULL,
    [DATE_CREATED]  DATETIME      CONSTRAINT [DF_USAGE_FILE_TYPE_DATE_CREATED] DEFAULT (getdate()) NOT NULL,
    [CREATED_BY]    VARCHAR (50)  NULL,
    CONSTRAINT [PK_USAGE_FILE_TYPE] PRIMARY KEY CLUSTERED ([ROW_ID] ASC)
);

