-- IN ORACLE

CREATE TABLE "LIBERTY"."PA_PROSPECT_TEMP" 
   (	"BATCH_NUMBER" VARCHAR2(50 BYTE), 
	"QUOTE_NUMBER" VARCHAR2(50 BYTE), 
	"PA_EXT_ID" VARCHAR2(32 BYTE), 
	"CUSTOMER_ID" VARCHAR2(32 BYTE), 
	"LOSS_FACTOR_NAME" VARCHAR2(32 BYTE), 
	"PROSPECT_NAME" VARCHAR2(256 BYTE), 
	"EDC_RATE_CLASS" VARCHAR2(32 BYTE), 
	"STRATA" VARCHAR2(32 BYTE), 
	"ACCOUNT_CALENDAR_ASSIGNMENT" VARCHAR2(32 BYTE), 
	"EDC" VARCHAR2(32 BYTE), 
	"ZONE" VARCHAR2(32 BYTE), 
	"STATUS" VARCHAR2(512 BYTE), 
	"CREATE_DTS" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 37748736 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "NERO_DATA" ;
  
  
  /********************************************************/


CREATE TABLE "LIBERTY"."PA_USAGE_HISTORY_TEMP" 
   (	
   "BATCH_NUMBER" VARCHAR2(50 BYTE), 
	"QUOTE_NUMBER" VARCHAR2(50 BYTE), 
  "PA_EXT_ID" VARCHAR2(32 BYTE), 
	"USAGE_BEGIN_DATE" DATE, 
	"USAGE_END_DATE" DATE, 
	"USAGE_VAL" NUMBER(14,4), 
	"CREATE_DTS" DATE
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 35651584 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "NERO_DATA" ;

  
  /*****************************************************************/

create or replace
PROCEDURE         PA_PROSPECT_TEMP_MOVE
    (
    p_BATCH_NUMBER IN VARCHAR2,
    p_QUOTE_NUMBER IN VARCHAR2
    ) AS
    
BEGIN
 
/* move prospect date from temp to acual location*/
  INSERT  INTO  LIBERTY.PA_PROSPECT
  SELECt  *
  FROM    LIBERTY.PA_PROSPECT_TEMP
  WHERE   QUOTE_NUMBER = p_QUOTE_NUMBER
  AND     BATCH_NUMBER = p_BATCH_NUMBER;
  
  COMMIT;
  
  DELETE   FROM LIBERTY.PA_PROSPECT_TEMP t1
  WHERE   QUOTE_NUMBER = p_QUOTE_NUMBER
  AND     BATCH_NUMBER = p_BATCH_NUMBER;

  COMMIT;

   
EXCEPTION
   WHEN OTHERS
   THEN
      RAISE;
      
END PA_PROSPECT_TEMP_MOVE;

/*******************************************************************/

create or replace
PROCEDURE         PA_USAGE_HISTORY_TEMP_MOVE
    (
    p_BATCH_NUMBER IN VARCHAR2,
    p_QUOTE_NUMBER IN VARCHAR2
    ) AS
    
BEGIN
 
/* move prospect date from temp to acual location*/
  INSERT  INTO  LIBERTY.PA_USAGE_HISTORY
  SELECt  PA_EXT_ID, USAGE_BEGIN_DATE, USAGE_END_DATE, USAGE_VAL, CREATE_DTS
  FROM    LIBERTY.PA_USAGE_HISTORY_TEMP
  WHERE   QUOTE_NUMBER = p_QUOTE_NUMBER
  AND     BATCH_NUMBER = p_BATCH_NUMBER;
  
  COMMIT;
  
  DELETE   FROM LIBERTY.PA_USAGE_HISTORY_TEMP t1
  WHERE   QUOTE_NUMBER = p_QUOTE_NUMBER
  AND     BATCH_NUMBER = p_BATCH_NUMBER;

  COMMIT;

   
EXCEPTION
   WHEN OTHERS
   THEN
      RAISE;
      
END PA_USAGE_HISTORY_TEMP_MOVE;

/*************************************************************************************/
----FORECASTING
  --
  UPDATE PA_PROSPECT P
    SET STATUS = (SELECT STATUS FROM PA_PROSPECT_REJECT R
                    WHERE R.BATCH_NUMBER = p_BATCH_NUMBER 
                    AND   R.QUOTE_NUMBER = p_QUOTE_NUMBER
                    AND    R.BATCH_NUMBER = P.BATCH_NUMBER
                      AND R.QUOTE_NUMBER = P.QUOTE_NUMBER
                      AND R.PA_EXT_ID = P.PA_EXT_ID);
