CREATE TABLE [Staging].[OfferEngineEPICPEG1] (
    [ID]                INT          IDENTITY (1, 1) NOT NULL,
    [Said]              VARCHAR (50) NULL,
    [MeterDescription]  VARCHAR (50) NULL,
    [Commodity]         VARCHAR (50) NULL,
    [EntityName]        VARCHAR (50) NULL,
    [ServiceAddress]    VARCHAR (50) NULL,
    [ServiceCity]       VARCHAR (50) NULL,
    [ServiceState]      VARCHAR (50) NULL,
    [ServicePostal]     VARCHAR (50) NULL,
    [MailAddress]       VARCHAR (50) NULL,
    [MailCity]          VARCHAR (50) NULL,
    [MailState]         VARCHAR (50) NULL,
    [MailPostal]        VARCHAR (50) NULL,
    [RateSchedule]      VARCHAR (50) NULL,
    [PriorReadDate]     VARCHAR (50) NULL,
    [CurrentReadDate]   VARCHAR (50) NULL,
    [NumberofDays]      VARCHAR (50) NULL,
    [Revenue]           VARCHAR (50) NULL,
    [Kwh]               VARCHAR (50) NULL,
    [Demand]            VARCHAR (50) NULL,
    [OffPeakkwh]        VARCHAR (50) NULL,
    [PartPeakkwh]       VARCHAR (50) NULL,
    [OnPeakkwh]         VARCHAR (50) NULL,
    [OffPeakDemand]     VARCHAR (50) NULL,
    [PartPeakDemand]    VARCHAR (50) NULL,
    [OnPeakDemand]      VARCHAR (50) NULL,
    [statusDescription] VARCHAR (50) NULL,
    [MeterNumber]       VARCHAR (50) NULL,
    [MeterConstant]     VARCHAR (50) NULL,
    [SasStatusId]       VARCHAR (50) NULL,
    [RequestId]         VARCHAR (50) NULL,
    [ContextDate]       DATETIME     NOT NULL,
    [DateCreated]       DATETIME     DEFAULT (getdate()) NOT NULL,
    [FileImportID]      INT          NULL,
    CONSTRAINT [OFFEPICPEG1_id_fk] FOREIGN KEY ([FileImportID]) REFERENCES [dbo].[FileImport] ([ID])
);

